### ISSUE TITLE
Find New Title

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#1]
TODO:
- [x] Find a new catchy title which is not used yet and will not cause us copyright problems.
- [x] find a good sub title

**Comment by Waog** [comment]
We didn't decide for a title yet.
I neither found a game named **Towel Defence** nor **Towel Defense** (american vs. British english) on my first small google research. I like to call it Towel Defence.

Do we need a subtitle at all? This primary makes sense if we plan to make a second part of this game. That's not my plan yet. Without a background story (Issue #53) I don't have an idea for a subtitle at all.

Meinungen?

**Comment by ghost** [comment]
OK, "Towel Defence" is cool.

Could be good to find a kind of "claim" but i'm at the same point like u, no idea for the moment... will maybe come in the next days. 

TOWEL DEFENCE
-the battle of the year!
-don't get wet!
-avoid the drops, turn the water hydrant off!
-use the force...
-don't let water embarrassing you!

**Comment by Waog** [comment]
I like _don't get wet_ out of the above most, because it's more catchy than the others.
But I'm not sure if i like it more than _no secondary title_.

**Comment by Waog** [comment]
ok... so no secondary title. I'm ok with that.
