### ISSUE TITLE
kleine Animation MainMenu

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#10]
Depends on Issue #9.

Auch mit Programmierung abstimmen, weil Partikel-Effekte helfen könnten.

**Comment by ghost** [comment]
was hälste davon, anstatt das logo mit Blitz zu animieren...

ein art Bildschirm an machen (switch on)?
http://youtu.be/oaZixS-3uXk?t=2s
(nur den flash am ende... aber umgekert wie ob es angeschalten würde)

**Comment by Waog** [comment]
das geht auch wieder in Richtung Retro-Spielautomat im Kasino. ich bin von der Idee allgemein nicht so so begeistert.

Ich dachte der Plan war ursprünglich, dass das Main-Menu richtig geil und catchy aussieht, so dass man voll lust bekommt zu spielen. Ich denke der Retro-Automat bewirkt (außer bei ein paar hipstern und indie-freaks) eher das gegenteil. Aber vielleicht schätze ich es auch falsch ein.

Und die Blitz-Animation könnte auch technisch problematisch sein. Wenn das am Ende 10 Animations-Frames à 1424x1168 haben, dann kosten die richtig viel speicher und ladezeit für so einen kurzen effekt. der speicher verbrauch könnte ein problem auf mobilen geräten sein. Hast du technisch eine bessere idee? ich nicht.

**Comment by ghost** [comment]
"Retro-Spielautomat im Kasino" euh... nicht ganz... (hat es mit der  DDR trauma zu tun? hahaha joke)
Retro ist die neue Mode mien Freund :) (ausserdem ist "Tron" 1982 und "Tron legacy" 2010 ein knaller...)

ok, vergiss es mit switch on...

denke trotzdem es wäre besser mit frame statt particles...

beispiel:
![tumblr_n436vakaix1qfwm02o1_400](https://cloud.githubusercontent.com/assets/7753856/3498195/236dbbc0-05f3-11e4-9a69-d8afa82860c9.gif)

**Comment by Waog** [comment]
- **ddr trauma:** vielleicht :laughing: 
- **tron 2010** fand ich sehr geil... allerdings eher wegen den geilen modernen effekten (und dem sound track) als wegen den paar retro-elementen.... und die haben die retro-ellemente sehr gut in das moderne zeug eingearbeitet, anstatt es einfach nur genauso zu machen wie es vor 20 jahren war.
- **frames statt particles:** frames und partikel schließen sich nicht gegenseitig aus... wir können auch beides gleichzeitig machen. Frames haben den oben genannten performance/speicher-nachteil, d.h. du müsstest mit kleinen grafiken und wenigen frames auskommen. Partikel sind, damit es nicht immer genau gleich aussieht (das wiederholt sich ja 1x pro sekunde oder so), sondern abwechslungsreich bleibt. Ich muss dafür nicht unbedingt _partikel_ nehmen, aber beispielsweise bei den frame-blitzen könnte ich die immer zufällig auswählen/rotieren/spiegeln/verschieben, damit die nicht immer genau gleich aussehen und der nutzer nicht so schnell kapiert, dass es sich immer nur wiederholt. Oder man könnte z.B. immer einen _dicken blitz_ mit frames machen und gleichzeitig kleine funken etc. mit partikeln. Das macht es auch abwechslungsreicher und macht vermutlich auch weniger arbeit, als wenn du jeden funken einzeln in photoshop platzieren musst.

**Comment by ghost** [comment]
gute Lösung :)
