### ISSUE TITLE
improve fontain

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#104]
- different states of the fontain don't differ enough
- last state is so different from _no fontain_

**Comment by ghost** [comment]
![1](https://cloud.githubusercontent.com/assets/7753856/7500405/c7ebe220-f42d-11e4-9a55-c24374352927.gif)
![2](https://cloud.githubusercontent.com/assets/7753856/7500406/ca193ebc-f42d-11e4-9bb7-5c8d62f37fc0.gif)
![3](https://cloud.githubusercontent.com/assets/7753856/7500409/cc009342-f42d-11e4-83ab-40c2209b21e9.gif)

liegt in dropbox: 150505 > Hydrant step1,2,3...

**Comment by Waog** [comment]
habe die fontainen eingebaut.

die großen tropfen aus der ersten animation sehen nicht gut aus... man versteht nicht so richtig warum da ständig weiße punkte blinken...
