### ISSUE TITLE
comic intro HRES pics

### ISSUE THREAD

**Issue by ghost** [Waog/towelGuy#106]

**Comment by Waog** [comment]
okay, die ersten experimente klappen. ich brauche die bilder in folgendem format. kannst du die mal so hochladen?:
- jeweils ausschnitte von **1024x1024** größe
- **sprechende dateinamen**, damit ich nicht lange suchen muss. Am besten: Comic0x0, Comic0x1, Comic0x2, ... Comic3x2 etc. also nach dem schema **Comic[X]x[Y]**

**Comment by Waog** [comment]
Ich habe jetzt erstmal gelesen, dass 1024x1024 für die meisten mobile geräte okay ist. Aber vielleicht müsen wir später noch auf 512x512 reduzieren, mal sehen.

**Comment by Waog** [comment]
http://iphonedevelopment.blogspot.de/2010/10/cutting-large-images-into-tiles-for.html

**Comment by Waog** [comment]
http://multiplans.net/en_Slicing.htm

**Comment by Waog** [comment]
done
