### ISSUE TITLE
comic intro - animations

### ISSUE THREAD

**Issue by ghost** [Waog/towelGuy#107]
vignette 4: Glitzy
v5: Stripes
v8: Typo or Picture 
v15: "!" bubble and "Glitypokiies"
19: Hydrant wackelt
20: Boooooom!

!!! All animation muss works as "loops"

**Comment by Waog** [comment]
okay, alles eingebaut... Die streifen aus Bild 5 sehen noch etwas komisch aus. Ich glaube die müssen wir nochmal zusammen machen.

**Comment by Waog** [comment]
was haben wir hier jetzt gesagt? sollen die streifen so bleiben? oder machst du mir nochmal eine Version, mit Streifen die zum Mittelpunkt zeigen?

**Comment by ghost** [comment]
habe in DroP BOX die Stripes fürs Comic gelegt in: Intro > zoom_stripes.png
sag bescheid ob es passt, sonst mach ich ein neuet...

**Comment by Waog** [comment]
okay, hab sie eingebaut und hochgeladen... finde es sieht so mittelmäßig aus, aber weiß nicht wie ichs besser machen soll.

**Comment by ghost** [comment]
Ich glaube den Zentrum vom Stripes sollte eigentlich auf die große Tropfen/impact zentriert werden (und nicht zentriert mit dem Comic "case")
und villeicht die Stripes skalierung (ganz groß/fade out) nicht so groß
macht Sinn?

**Comment by Waog** [comment]
okay, bau ich ein

**Comment by Waog** [comment]
so besser?

**Comment by ghost** [comment]
yey, finde besser so.
