### ISSUE TITLE
Drops animation

### ISSUE THREAD

**Issue by ghost** [Waog/towelGuy#112]
drop gif: 3 frames anim  (and maybe differents forms)

---

easter egg??? random raining Frogs or so?

**Comment by ghost** [comment]
![drop_3kb](https://cloud.githubusercontent.com/assets/7753856/7479478/2a235260-f362-11e4-83d8-1212de8c522e.png)

Liegt ein PNG in drop box: 150505 > drop_3KB.png
ist eine animation mit 3 frames. Kannst du erstmal das einsetzen und probieren ob es visuel ok ist.
(man könnte auch eine zweite Variante mit leichtem Unterschied mit die Farbtöne, aber muss nicht sein...)

**Comment by Waog** [comment]
eingebaut
