### ISSUE TITLE
"too Slow" message

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#124]
... in win screen.
wee need:
- idea
- graphics
- programming

**Comment by Waog** [comment]
under der tatel blinkt in der gleichen schriftart:
"Too Slow: X'YZs" ... proper allignment

**Comment by ghost** [comment]
so finde ich ok:
- grüner balken, timer blinkt drinn villeicht.
- blendet ein "TOO SLOW!" in klein (?50%) -> (animation) vergrössert sich (110%....150%...bis 300%?) blendet sich aus.

![screen shot 2015-05-07 at 20 41 40](https://cloud.githubusercontent.com/assets/7753856/7523072/7ebfc810-f4f9-11e4-83dc-2f66dddb6180.png)

Wat meinste?

**Comment by Waog** [comment]
Als Bild siehts gut aus, aber:
- ich weiß nicht obs gut aussieht, wenn der weiße halbtransparente hintergrund mit animiert (skaliert) wird.

Sonst zwei Kleinigkeiten, die meinetwegen nicht unbedingt geändert werden müssen:
- die Zeit wird tendentiell eher zweiteilig (Sekunden und Millisekunden).
- Die Zeit (grüner hintergrund) sticht sehr stark in den Augen... kann man da etwas mehr richtung grau gehen? (sättigung senken?).

Und das "TOO SLOW" wäre geil als bitmap font zu haben... ich dachte daran auch solche nachrichten im gameplay einzubauen... "FASTER!", "OUTCH" etc...

**Comment by Waog** [comment]
noch zu tun:
- own time + grüner balken einblenden (nach ca. 1 sekunde im bildschirm)
- "TOO SLOW!" erst nach ca. 1 sekunde einblenden.

**Comment by Waog** [comment]
done
