### ISSUE TITLE
PNG compression

### ISSUE THREAD

**Issue by ghost** [Waog/towelGuy#126]
Yo, 
kannst du irgenwie ein test in Construct 2 machen um zu wissen ob es wirklich die PNGs komprimiert? (und wenn ja von vieviel?)

hab das jefunden:
https://www.scirra.com/blog/66/image-compression-in-construct-2

Von meine Seite, ich könnte alle PNG extra web speichern, und es würde drastich die KB reduzieren...  ob es wat bringt?
![screen shot 2015-05-05 at 20 13 30](https://cloud.githubusercontent.com/assets/7753856/7479797/3c9627e0-f364-11e4-929c-b41f26287ef9.png)

**Comment by Waog** [comment]
erstmal müssen wir die pixel-anzahl verkleinern... die dateigröße ist nicht so wichtig... dadurch dauert nur das laden ganz am anfang länger. Aber dafür finden wir sicher auch ne lösung...

**Comment by Waog** [comment]
Also ich kann mit meinen Tools auf ca. 30% der Original-Größe optimieren. Du kommst durch speichern für Web in Photoshop auf unter 1%. Kannst du mal gucken, ob du irgendwie mehrere files auf einmal optimieren kannst, anstatt jedes einzeln? Wir werden immer ~100 Files optimieren müssen. Und das jedes mal bevor ich hochlade...

**Comment by ghost** [comment]
hattest du nicht ein Ordner irgendwo vorbereitet und gelegt? ist nicht in Drop box...

**Comment by Waog** [comment]
habs jetzt verschoben. Hauptebene > 01_export
