### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#130]
@nostoner Wie läufts? Viel zu tun?

**Comment by ghost** [comment]
Yey! 
leider ja, muss Morgen nach Österreich bis Samstag wegen Arbeit.
Gebe gaz wenn ich zurück bin am Sonntag :)

**Comment by ghost** [comment]
Hey yo! wie läuft es bei dir?
wie sieht es aus mit deine Zeit? wollen wir uns demnächst treffen?

ich versuche am WE meine issues zu machen...

**Comment by Waog** [comment]
passt zeitlich grade sehr gut... bin jetzt penner, hab viel freizeit. Wenn du willst können wir jetzt auch mehr Zeit verbringen als Abends mal eine Stunde... hilft vllt bei der Motivation :)

**Comment by ghost** [comment]
Penner könnte ein guter job sein 8/
muss leider jeden Tag arbeiten bis ca. 18h30 (wenn nichts so viel los ist, haha), aber danach habe ich Zeit :)

eigentlich wartest du mehr oder weniger auf graphics von mir, also ICH soll voll gaz geben...

**Comment by Waog** [comment]
Je nachdem, ob du lieber alleine grafiken machst, oder lieber gesellschaft hast und jemanden der ständig sagt "icons sind besser als texte!"

sag einfach bescheid wann du vorbei kommen willst, meine tür steht dir offen. und vergiss nicht dein grafik-tablet (oder was du so brauchst) mitzubringen.

Achso, abends ab 18:30 habe ich oft training... Montag, Mittwoch und Donnerstag Abend sind meistens blockiert bei mir.

**Comment by ghost** [comment]
hey, haste Zeit heute Abend?

**Comment by ghost** [comment]
und Morgen anbend oder Samstag, vielleicht Zeit?

**Comment by ghost** [comment]
Hey yo!
sag mir einfach bescheid wenn du Zeit hast. Wäre eigentlich cool diese Woche noch...
(Tags über, bin ich leider auf Arbeit)

**Comment by Waog** [comment]
Hey, hab den nächsten Monat leider keine Zeit, ich meld mich dannach mal.

**Comment by ghost** [comment]
okay, mach es...

**Comment by Waog** [comment]
Bin wieder da und bereit zu rocken, wann hast du Zeit?

**Comment by ghost** [comment]
yey, cool... habe Zeit am Freitag abend oder W.E.

Was hältst von Samstag nachmittag?

**Comment by Waog** [comment]
Freitag Abend passt nicht, aber Samstag Nachmittag sehr gut. Ab 15:00 bei mir?

**Comment by ghost** [comment]
yey, cool! Samstag bei dir... see ya!

**Comment by Waog** [comment]
okay, game ist hochgeladen... url wie bisher.

wann willst du hier sein?

**Comment by ghost** [comment]
18h30 is ok für dich? 

```
 Oliver Stadie <notifications@github.com> schrieb am 15:59 Montag, 14.September 2015:
```

 okay, game ist hochgeladen... url wie bisher.wann willst du hier sein?—

**Comment by ghost** [comment]
schik mir nochmal die URL bitte...

**Comment by Waog** [comment]
nein, bin erst 22h selbst vom training wieder hier. also nicht vorher.

Gib mal ne email-addy für die URL.

**Comment by ghost** [comment]
nostoner@yahoo.com

**Comment by ghost** [comment]
22h??????? willst mich töten... :) ok 22h

**Comment by ghost** [comment]
brauche die URL nicht mehr, habs gefunden...

**Comment by Waog** [comment]
:+1:

**Comment by ghost** [comment]
Ah ja...noch wat...
bei SCORE:
warum haben wir die Mama und das Kind auf der Bank? weiss ich nicht mehr...
Eigentlich, die sollten nur im WIN tabell sein.

**Comment by Waog** [comment]
BÄM... Milestone fertig!
