### ISSUE TITLE
Replace RR Logo after exporting

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#135]

**Comment by Waog** [comment]
maybe this works better:
![image](https://cloud.githubusercontent.com/assets/5098472/13620184/302f045a-e58e-11e5-970d-dfe1a9efa280.png)

**Comment by Waog** [comment]
Es Klappt!
![image](https://cloud.githubusercontent.com/assets/5098472/14143796/622f19e4-f68d-11e5-92a0-042f8d024d0a.png)

Kannst du mal die Bilder in `Dropbox > 02_Loader` mit ordentlichen Grafiken ersetzen? Auflösung aber so lassen.

**Comment by ghost** [comment]
> Dropbox

**Comment by Waog** [comment]
done
