### ISSUE TITLE
Laser zu kurz

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#139]
Im Gameplay muss der bllitz vom player bis zum hydrant durchreichen...

**Comment by Waog** [comment]
- fragmente die aneinander passen
- kürzestes fragment ist so lang wie blutz am guy
- gzzzzrrt

**Comment by ghost** [comment]
yo! liegt in drop box...

electricity_1.png, electricity_2.png, electricity_4.png, electricity_4_small.png
sag bescheid ob es passt...

**Comment by Waog** [comment]
sieht kacke aus:
![image](https://cloud.githubusercontent.com/assets/5098472/10638023/1d7f452e-7809-11e5-8fe4-a6e9539a1d1f.png)
![image](https://cloud.githubusercontent.com/assets/5098472/10638039/2ff3d256-7809-11e5-9e5f-5f5198981a5e.png)
![image](https://cloud.githubusercontent.com/assets/5098472/10638050/43a43548-7809-11e5-9cd0-356cfe80c413.png)

**Comment by Waog** [comment]
Dass es kacke aussieht hat aus meiner Sicht folgende Gründe, die man beheben kann:
- Die Blitz-Tiles sehen Grafisch anders aus, als die vom Guy (andere Auflösung(?), durchgehend, anstatt Verzweigend)
- Die Blitz-Tiles sind durchgehend. Ich denke es sähe besser aus, wenn sie so aus Fragmenten beständen. Also Lücken dazwischen haben. So sieht es aus wie eine Herz-Frequenz im Krankenhaus.
- Verschiedene Höhen von Guy und Hydrant. Das sieht man vor allem im letzten Bild. Erst geht der Blitz nach unten... dann waagerecht, und dann ist der Hydrant noch tiefer.
- Vllt muss bei der Guy Animation der Attack-Blitz noch angepasst werden, damit die Tiles ordentlich ans Ende ranpassen.

**Comment by Waog** [comment]
done
