### ISSUE TITLE
Hydrant spinning (electricity)

### ISSUE THREAD

**Issue by ghost** [Waog/towelGuy#142]
yo! ich hatte das noch vergessen:
eigentlich wenn man gewonnen hat, (in der Zeit wo der Hero tanzt, im game play mode) gibt es immer electricity herum die Hydrant, und es dreht sich. Eigentlich der Strom sollte nicht mehr da sein...
Wir hatten ein grafik dafür oder brauchst du noch was?

**Comment by Waog** [comment]
Finde eigentlich cool, dass auf dem Sieger-Bildschirm Party abgeht... Soll der unbedingt aufhören sich zu drehen?

**Comment by Waog** [comment]
fixed
