### ISSUE TITLE
Remove Mama and Kind from Score Screen

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#143]
Nostoner in #130:

> Ah ja...noch wat...
> bei SCORE:
> warum haben wir die Mama und das Kind auf der Bank? weiss ich nicht mehr...
> Eigentlich, die sollten nur im WIN tabell sein.

**Comment by Waog** [comment]
Finde ich unwichtig... ists dir wichtig, dass ich sie entferne? sieht der bildschirm dann nciht zu langweilig aus?

**Comment by ghost** [comment]
the devil is in the detail... (ich wünsche mir das für Weihnachten 2011, thx!)

**Comment by Waog** [comment]
done
