### ISSUE TITLE
Discussion Finetuning Round 1

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#144]

**Comment by ghost** [comment]
YO!
wie sieht es aus? könntest du Yvan ereichen für die Soudeffects? Möglich sich am Samstag zu treffen?

**Comment by Waog** [comment]
er hat noch nicht geantwortet. Ich vermute wir müssen es um eine woche verschieben...

**Comment by ghost** [comment]
YO!
und jetzt, wat neuet gehört?

**Comment by Waog** [comment]
Nee, ich frag nochmal nach. Hatte jetzt Spontan meine Diplomverteidigung, deshalb nix am Game gemacht. Bald gehts wieder weiter :)

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
YO! (ich bin ein russicher Bot...)
und jetzt, wat neuet gehört?
...
nope...?

**Comment by Waog** [comment]
Okay, kam zwei mal keine Antwort. Ich denke wir suchen uns besser jemand anderen für die Sounds. :\

**Comment by ghost** [comment]
habe villeicht jemand gefunden:
https://soundcloud.com/p0rncop/deep-impact

hoffe er meldet sich demnächst :)

**Comment by Waog** [comment]
Der song klingt geil :D 
Wäre zufriedne mit was derartigem :+1:

**Comment by Waog** [comment]
macht der auch sound effekte, oder nur musik?

**Comment by Waog** [comment]
habe die aktuellste version mal hochgeladen...

**Comment by ghost** [comment]
hello, sieht allet gut aus :)
ich treffe mich diese Woche noch mit dem "Porn Cop" sound man. Ich denke sound effekte sollte gar nicht so schwerig für ihm sein...
ich melde mich nochmal am Freitag. Haste zeit am WE für nem treffen?

**Comment by Waog** [comment]
jo, SA und SO je vor 16 uhr und sonntag abend... so ab 21h. wann passts bei dir?

**Comment by Waog** [comment]
okay, samstag ist unser wohnzimmer besetzt. also da müssten wir uns woanders treffen.

**Comment by ghost** [comment]
yooooo!
ist eigentlich dieses WE blöd, ich treffe mich jetzt nächste Woche mit der sound maker. Lass uns lieber nächste WE treffen oder?

**Comment by Waog** [comment]
Wir haben auch ohne den Sound noch einige Baustellen. Also wenn du Zeit hast, dann können wir uns trotzdem treffen!

**Comment by Waog** [comment]
Und wie siehts aus?

**Comment by ghost** [comment]
Shalom! meiner Seite (Sound maker) ist nicht mehr erflogreich als damals für dich ahahah (vielleicht wegen Weihnachten/Silvester Zeit?) lass uns trotdem treffen nächste Woche falls du in Berlin bleibst...
oder?

**Comment by Waog** [comment]
Habs erst jetzt gelesen. Wann hast du wieder Zeit? Ich kann mich anpassen.

Wär cool, wenn du sogar viel Zeit hättest, dann können wir mal ne 8 Stunden-Session oder so machen!?

**Comment by ghost** [comment]
schade, habe nicht mehr Urlaub :/
"8 Stunden-Session" lassuns dann am WE treffen wenn es für dich passt. Samstag nachmittag?
Ich versuche auch noch diese Woche den "Soundmaker" ein bisschen zu nerven, villeicht lohnt es sich...

**Comment by Waog** [comment]
Habe Samstag etwa bis 20:00 Zeit. 12-20h bei mir?

**Comment by ghost** [comment]
13h ist besser für mich... dann komme ich am Samstag zu dir, bis dann!

**Comment by Waog** [comment]
nice... bring dein zeug mit, was du zum arbeiten brauchst :)

**Comment by ghost** [comment]
haste das Spiel neu hochgeladen? kannste mir nochmal die URL schicken please...
würde gerne Morgen das Testen lassen :)

**Comment by ghost** [comment]
THIS IS A MANUAL SPAM:
Hey bim bap! kannnnnnste das Spiel nochmal hochladen, würde gerne die URL an der Soundman schicken...

thx

**Comment by Waog** [comment]
http://waog.itch.io/towel-defence?secret=Nn0hqKgV8FkOCVcaAdAK9Gwaz4

**Comment by ghost** [comment]
cool!
ich schreibe ihm gleich und versuche ihm mit zu nehmen am Samstag (14h)... falls wat ist, sag ich wieder bescheid.

**Comment by ghost** [comment]
habe verspätung, sorry...
bin bei dir zwischen 14h30-15h
Soundman hat sich nicht gemeldet, grrrrrr...

**Comment by ghost** [comment]
wollten wir uns eigentlich Morgen treffen?

**Comment by Waog** [comment]
jo 14:00.

**Comment by Waog** [comment]
habe nen debug-modus & cheat-hilfe eingebaut. Kannst ihn aktivieren, indem du die vier ecken im hauptmenü nacheinander anklickst:
![image](https://cloud.githubusercontent.com/assets/5098472/12557068/60086788-c389-11e5-98ae-4887667c4c3f.png)

**Comment by ghost** [comment]
ahahahah excellent, habe gerade probiert :+1:

**Comment by Waog** [comment]
Nächstes Meeting, 6.2. 14:00

**Comment by Waog** [comment]
finally! habe die iPhone-Performance auf 50 FPS gesteigert :)
Treffen am Samstag geht klar? Was macht unser Kumpel porncop?

**Comment by ghost** [comment]
YEYYYY!!!! gelio...
für Caccorn, sollte man vergessen. Nicht neuet gehört...

**Comment by Waog** [comment]
Okay, habe ein paar große technische Änderungen vorgenommen. Es könnten sich dadurch neue Bugs und unabsichtliche Änderungen eingeschlichen haben. Wär gut, wenn du nochmal ein wenig durchtestest und neue Issues aufmachst für alles was du so bemerkst .

**Comment by ghost** [comment]
with the power of the grey skull, mach mich ADMIN auf "red skittles" und " Towel Defence" bei Facebook...

YO!

**Comment by Waog** [comment]
wer bist du? Norman Steinberg?

**Comment by ghost** [comment]
ne... HERRRR NOOOOORMAN STEINBERG! :)

**Comment by Waog** [comment]
weil facebook schlau ist, kann ich nur ne email-addresse angeben um dich zum admin zu machen. mit welcher hast du dich angemeldet?

**Comment by ghost** [comment]
nostoner@yahoo.com

**Comment by Waog** [comment]
solltest jetzt alles editieren können

**Comment by ghost** [comment]
es ist so schön... ich fühle mich Brandenburg...

**Comment by Waog** [comment]
HA! hab die Minute geknackt!
![image](https://cloud.githubusercontent.com/assets/5098472/12869900/bf5778ee-cd2c-11e5-84f8-d9aac233c402.png)

**Comment by Waog** [comment]
hab neue cheats eingebaut:
![image](https://cloud.githubusercontent.com/assets/5098472/12870112/cd56b460-cd35-11e5-99c2-2a617daf3a0f.png)

**Comment by ghost** [comment]
yey, coolio! see ya next wwwwweeeeekkkkkkk....

**Comment by ghost** [comment]
übrigens, habe die sekunde geknackt!!!!! 
![bf5778ee-cd2c-11e5-84f8-d9aac233c402 copy](https://cloud.githubusercontent.com/assets/7753856/12870188/c05aca22-cd39-11e5-9205-070c0385ce31.png)

salute e loves

**Comment by Waog** [comment]
sogar mit 4 leben... krass, musst du mir mal beibringen :D

**Comment by Waog** [comment]
diesem samstag kein meeting, hab besuch

**Comment by ghost** [comment]
stimmt, habe José gesagt, falls er im Berlin kommt, kann er bei dir pennen... hoooo hoooo hoooo

am bestens wäre gut wenn du schreibst "diesem samstag, kann ich leider kein meeting machen, habe besuch..." sonst klingt es wie: "Deutschland braucht mehr Raum, wir sind besser, blah blah" also wie ein früstrierte DIKTATOR.

wir hören uns...

nächste mail für josé setzte dich in CC.
welche email von dir kann ich benutzen?

**Comment by Waog** [comment]
Lieber @nostoner,

leider habe ich diesen Samstag keine Zeit. Ich habe wieder lange Training und Besuch übers Wochenende.

Aber vielleicht können wir uns ja nächste Woche Samstag treffen? Ich vermisse dich.

In Liebe
dein @Waog :heart: :heart:

**Comment by ghost** [comment]
![sparkle-7](https://cloud.githubusercontent.com/assets/7753856/13285130/378a57a8-daf9-11e5-8080-b7bfa4b61e76.jpg)

wie? du triffst dich mit andere Leute als icke? bin sehr traurig...
5.März ist auch cool für mich.

Ich vermisse dich nicht wirklich aber:
 :heart: :heart::heart: :heart::heart: :heart: trotzdem.

@nostoner

**Comment by Waog** [comment]
Dann 5. März 14:00?

**Comment by ghost** [comment]
yey cool... (und vielleicht bis dahin gibt es was von José zu hören :)

**Comment by Waog** [comment]
Wie siehts am Freitag bei dir aus? Hast du Zeit?

**Comment by ghost** [comment]
yey, Freitag 15h? bei dir?

**Comment by Waog** [comment]
oki :)

musik ist schon eingebaut und hochgeladen... ist viel cooler das spiel jetzt :)

**Comment by ghost** [comment]
kann leider am Freitag nicht, passt es für dich am Samstag? 14h?

**Comment by Waog** [comment]
Ja, aber besser erst 14:30 :)

**Comment by ghost** [comment]
ok, komme dann um 15h :)

**Comment by ghost** [comment]
FInde ganz gut, dass die Animation mit "Flood fingaz" auftaucht wenn mann nicht genug aktiv ist :+1:

**Comment by Waog** [comment]
Wann sehen wir uns wieder? Hast du schon Freitag Zeit?

**Comment by ghost** [comment]
yey, Morgen um 14h bei dir?

**Comment by Waog** [comment]
Okay, bis morgen :)

**Comment by Waog** [comment]
Achso, wie lange dann? Wär gut wenn ich vorher weiß, obs 2 oder 8 Stunden werden.

**Comment by ghost** [comment]
14 bis 18 wäre schon wat, oder?

**Comment by Waog** [comment]
:+1:

**Comment by Waog** [comment]
wie siehts aus? hast du morgen oder samstag zeit?

**Comment by ghost** [comment]
hideehoo!
habe leider diese Woche keine Zeit für ein treffen (ich versuche trotzdem meine Issues weiter zu arbeiten). 
Nächste Woche sieht auch ziemlich schlecht aus (WE ist auch busy days), aber Freitag würde passen...

**Comment by Waog** [comment]
Geht Freitag ab 16:00?

**Comment by ghost** [comment]
Hi Oli,
muss für Freitag leider absagen, wir Pitchen gerade auf Arbeit (ist kacke! burkkkk! pfui! hilfe...) 
Verschieben wir es für nächste Woche? wenn es für dich geht...

haste eigentlich vielleicht wat vom Publisher gehört?

best,
C

**Comment by Waog** [comment]
Hi @nostoner,
wie siehts diesen Freitag oder Samstag bei dir aus? Oder wenn du Zeit hast, auch gerne schon früher.

Von 4 Publishern hat - nach über einer Woche - noch kein einziger geantwortet :\
Publisher Communikation protokoliere ich im groben übrigens hier #3 

Ich habe auch mal eine Antwort an José verfasst und das file n der Dropbox aktualisiert. Kannst du sie mal gegenlesen, bevor ich abschicke?

Gruß,
oli

**Comment by Waog** [comment]
Publisher Communikation protokoliere ich im groben übrigens hier #3 
Wenn du kannst können wir uns übrigens gerne auch immer schon vor Freitag treffen.

**Comment by ghost** [comment]
Hellöp,
Samstag ist mir lieber, 14h passt für dich?

für José, ich habe den Text im Blau leicht verändert. Ich würde es so schreiben, aber ist up to you :)

**Comment by Waog** [comment]
hoi,

Samstag 14:00 passt bei mir. Bis wann dann etwa?

Habe deine remarks teilweise eingearbeitet und die Mail an euch beide geschickt.

**Comment by ghost** [comment]
cool. bis 18-19h?

**Comment by Waog** [comment]
:+1:

**Comment by Waog** [comment]
okay, neuste version ist hochgeladen.

**Comment by ghost** [comment]
:+1:

**Comment by ghost** [comment]
schaffe diese Woche wieder nicht für nem treffen... nächste Freitag? 14h bei dir?

**Comment by Waog** [comment]
Freitag 14:00 ist super :+1:

**Comment by Waog** [comment]
Wie lange?

**Comment by ghost** [comment]
bis 18h-19h?

**Comment by Waog** [comment]
oki

**Comment by Waog** [comment]
oh, einen tag vorher ist ja herrentag... bin noch nicht sicher, wann ich Freitag wieder bei Bewußtsein bin. Kannst du vorsichtshalber nochmal anrufen, bevor du zu mir losfährst?

**Comment by ghost** [comment]
ahahaha, ja klaro 👍

**Comment by Waog** [comment]
wie siehts diese woche aus bei dir? hast du zeit?

**Comment by ghost** [comment]
Freitag ist nicht so gut für mich.., Samstag 14h bei dir?

**Comment by Waog** [comment]
14:00 schaff ich nicht, ab 15:00 wär okay.

**Comment by ghost** [comment]
ok goody, dann 15h am Samstag bei dir 👍

**Comment by Waog** [comment]
wie siehts aus? ich warte noch auf grafiken

**Comment by ghost** [comment]
War nicht da letzte Woche und bin jetzt krank!... shitty!
 hoffe ich bekomme es ihn diese Woche...

**Comment by Waog** [comment]
wie siehts aus diese Woche? Hast du Zeit?

**Comment by ghost** [comment]
Samstag 15h bei dir? für 3-4 Stunden? passt für dich?

**Comment by Waog** [comment]
:+1: cool, passt! bis Samstag.

**Comment by ghost** [comment]
https://freesound.org/people/timgormly/sounds/162814/

**Comment by Waog** [comment]
milestone finished, moved discussion to #218
