### ISSUE TITLE
Comic intro - buttons sound/music

### ISSUE THREAD

**Issue by ghost** [Waog/towelGuy#147]
habe gerade wat gesehen (villeicht ist mit absicht von dir :) im Comic intro, wenn man auf den button sound oder music click, der click wird auch als "weiter" (für comic stripe) benutzt, sollte eigentlich nicht oder?

**Comment by Waog** [comment]
jo, hab ich vorhin auch bemerkt und sollte nicht, nein. ich versuchs mal auszubauen...

**Comment by Waog** [comment]
okay, fixed
