### ISSUE TITLE
Powerup 1: nian cat

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#148]
niancat + rainbow + shild
- niancat als spritesheet (ohne regenbogen)
- regenbogen als 4-5 pixel breiten streifen (so breit wie im original)
- schild für feste höhe (2-3 visuals)
  -- `ggf. fade in und fade out fürs schild
1. niancat blinkt und erscheint am boden
2. player sammelt niancat
3. player erhält schild und niancat flieg vertical hoch in himmel (ohne regenbogen)
4. niancat fliegt los mit regenbogen
5. niancat kommt nochmal (weiter weg / kleiner) ins bild und fliegt nochmal durch den himmel

regenbogenschild hällt 1-3 tropfen ab (balancing) oder verschwindet nach fester zeit.

**Comment by ghost** [comment]
![screen shot 2016-01-19 at 21 48 39](https://cloud.githubusercontent.com/assets/7753856/12431636/d6d2dd40-bef6-11e5-8c72-abeaaf700541.png)
YO!

habe das momentan so gespaltet:

0- Nyan Bubble (über unser hero)
1- Nyan Static (png mit 2x Bilder anim, augen blinken Bild2>2>2>2>1>2>2...)
2- Nyan_going_up (png 3x Bilder anim Bild1>2>3>2>3...) 
3- Nyan_fly (gif animated timing mussen wir anpassen, villeicht mussen wir wieder an die anim dran)
3 + Nyan Rainbow: kann man den rainbow durch programmierung aus blenden?

4- Nyan small + Nyan rainbow small im Background (nach nen paar sekunden)

probier mal ob du damit anfangen kannst, dann können wir es noch zusammmen anpassen...

**Comment by Waog** [comment]
machs mal in dropbox rein ;)

**Comment by ghost** [comment]
ist eigentlich schon da... (02 Gameplay>Nyan_...)

**Comment by Waog** [comment]
so, nian cat ist eingebaut :)
