### ISSUE TITLE
Powerup 2: Tetris

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#149]
Erstmal ein Tetris-Stein (Z-Förmig) der vom himmel kommt, sich immer über spieler bewegt und ab bestimmter höhe schnell runterfällt. Bleibt 1-2 Sekunden liegen und verschwindet dann.

Wenn es gut funktioniert, dann auch alle anderen tetrissteine
- Beide Dreh-Richtungen  
  ![image](https://cloud.githubusercontent.com/assets/5098472/12373379/88ffc28a-bc77-11e5-8833-40a345e0f76f.png)

**Comment by ghost** [comment]
habe ein PNG im Drop gelegt: Tetris_brick_1.png
bei diese Forme, gibt es kein Schatten/High light, aslo wir brauchen nicht "zwei positionen" :)
probiert mal damit und sag bescheid...

**Comment by Waog** [comment]
fertig :)

**Comment by ghost** [comment]
könnte Tetris nirgendwo sehen, ich weine in mein Zimmer.... huhu

**Comment by Waog** [comment]
Tetris kommt nach 15, 30 oder 45 Sekunden, wenn man dann genug Schaden gemacht hat (25%, 50% oder 75%)
