### ISSUE TITLE
Content CreditsMenu

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#15]

**Comment by Waog** [comment]
TODOs:
- [x] CreditsMenu Background, with text "Credits" and some space for content and Back-Button
- [x] Some BitmapFont (depends on Issue #30)
- [ ] Content (i.e. Text, depends on Issue #52)
- [x] Contributor Avatars
- [x] any other logos?
- [ ] after all of the above is ready, label this issue as `Task: Programming`

**Comment by Waog** [comment]
Integrated some example content in the credits menu...
- Weblinks are possible but the technical solution sucks.
- BitmapFonts can be used in default mode, alternatively sprites with the text or system fonts.

**Comment by ghost** [comment]
![layer 43 copy](https://cloud.githubusercontent.com/assets/7753856/3307572/7351e6f0-f66e-11e3-843f-19e01924b4d2.png)
small test...

**Comment by Waog** [comment]
hmm... ich hätte ganz gerne meinen avatar (siehe github oder skype) im credits screen. Kriegen wir das irgendwie hin, oder passt der zu schlecht zum restlichen style?

**Comment by ghost** [comment]
Ich finde das leider nicht ganz genau passend...

willste unbedingt Schlaghose? :)
können auch ohne Avatar machen...

**Comment by Waog** [comment]
Ging mehr um den Wiedererkennungswert. Das ist halt fast überall seit vielen Jahren mein Avatar.

Aber ja, schlaghose wäre gut :) und ich trage nur weiße klamotten. nix blaues.

**Comment by ghost** [comment]
Ok!
 aber gesicht ist ok? (ich finde es nicht soooo schlecht wenn man so venig pixel zu verfügung hat :)

**Comment by Waog** [comment]
Jap, hast mich gut getroffen, hab gedacht ich gucke in nen spiegel :D

**Comment by ghost** [comment]
![screen shot 2014-06-24 at 12 13 28](https://cloud.githubusercontent.com/assets/7753856/3369944/6caa5052-fb88-11e3-93bd-d15d8a24f6cc.png)

bin mir gar nicht ganz sicher für die Richtung... 
- könnte man tropfen als anim einfügen (als sprite), magste die idee mit Regenschirme? (willste lieber ein schwarzes? ich mag cyan :), willste links bündig sein?...)
- ein neuen BG einfügen anstat NYC, ein Büro, in Berlin (mit Oberbaumbrücke und schlechtes Wetter), oder wat anderes?
- brauchen wir ein Copyright oder Creative Common #9 ?

liegt im DropBox als Platzhalter...

**Comment by Waog** [comment]
Mir gefällt es gut. Aber was soll inhaltlich in den große textblock? Außerdem hätte ich gerne noch folgende Dinge mit drin:
- Uns beide als "Link" den man anklicken kann... es sollte irgendwie grafisch ersichtlich sein, dass man uns anklicken kann.
- irgendwie ein Dankeschön an den MiniGameJam und an pizza.de

Zu deinen Fragen:
- ja, tropfen gehen
- ja, ich mag die regenschirme, mir reicht cyan :) Dein Avatar und Regenschrm haben noch zu wenig Kontrast vom Hintergrund. Vllt solltest du zumindest das Haus hinter dir hell machen, oder das Problem löst sich von alleine durch einen neuen hintergrund oder die link-hervorhebung.
- ich mag den NYC-Hintergrund eigentlich. Ich finde nicht dass da jetzt unbedingt ein Verweis auf Berlin rein muss... es passt auch wenn wir uns im Setting des Gameplays befinden.
- Kenne mich mit Copyrights und Creative Commons nicht sooo gut aus. Also ich habe keine Lust Geld dafür zu bezahlen, um das irgendwo zu registrieren, oder anspruch darauf anzumelden. Lizenzen machen glaube ich auch erstmal wenig Sinn... die vergeben wir individuell an die Seiten die unser Spiel hosten (see #3), oder die User müssen direkt auf unseren Seiten spielen. Was "copyright" genau bedeutet weiß ich nicht... wenn du das weiter diskutieren willst, dann mach mal bitte nen neuen Issue dafür auf.

**Comment by ghost** [comment]
- "inhaltlich in den große textblock?"
  kenne Ahnung, wat wie "Danke mama, ich hab dich soooo lieb..." (joke...)
  ist ein Text Platzhalter, wenn man nicht wess wat man schreiben muss, aber man weiss das irgendwat noch kommt (könnte auch logo sein... ist eigentlich egal)
- "Uns beide als "Link" jep :) was wie ein button wo steht "url" oder "website"... 
- finde MiniGameJam und villeicht co.up ok, aber "pizza.de" nicht so der knaller, wirkt seltsam in einem Spiel...

**Comment by Waog** [comment]
- **lorem ipsum:** ja ich kenne lorem ipsum, aber ich wüßte nicht womit wir den text ersetzen sollen.
- **Link:** Bei meinen ersten experimenten habe ich es auf Mobil-Geräten _nicht_ hinbekommen, dass ein tap auf den link irgendetwas bringt (links scheinen auf mobile nicht zu gehen). D.h. wir müssen entweder verschiedene Credits-Menüs für Desktop und Mobile anbieten, oder du musst dir eine "subtilere" Lösung einfallen lassen, bei der wir am ende Behaupten können "war ja auch gar nicht als link gedacht" :)
- **Dankes-Worte:** gerade pizza.de finde ich ganz gut... das ist unser einziger namenshafter sponsor/supporter. Vielleicht erwähnen wir die alle in dem Lorem Ipsum Text? Hier mal ein erster entwurf:
  - Thanks to _Berlin MiniGameJam_ for the initial platform. Thanks to _co.up_ for providing their rooms. Thanks to _pizza.de_ for the free food.

:-1: Ich mag den eigenen entwurf gar nicht, aber vielleicht hilft er als inspiration.

**Comment by ghost** [comment]
- LINK: Link: d.h. für browser/Desktop haste das hin gekriegt, aber nicht mobile? (oder zusammen gleichzeitig?)
  können immer eine Blase machen mit kurze URL von dir und mir... oder so was... (ist aber nicht so geilo.)
- Dankes Worte: hab erstmal das so gebaut nur graphic mässig, aber finde den text auch nicht so den knaller (Gestaltung und Inhalt)... "dann mach doch besser christophe!" :) euh... arbeite dran :)
  bin immer mehr Skeptisch mit "pizza.de".Es ist/war nicht unser sponsor, und hat nichts mit uns (und die Version 2.0 dieser Spiel) zu tun eigentlich. Dann lieber was für "Samuel und Stefano" oder noch besser für meine Frau...

muss man noch nachdenken.

![bg_game_small-sze_72dpi](https://cloud.githubusercontent.com/assets/7753856/3422005/db62ddf4-ff0f-11e3-87e7-24a44521a677.gif)

fande cooler by night. wip...
- ist es nicht besser unsere @emalis adresse zu schreiben? da es "Contact" ist? (Nachteil ist, dass es nicht sehr profi aussieht. Ein bisschen wie :"das ist mein erstes Spiel hu hu")

WIP WIP WIP

**Comment by Waog** [comment]
- **link:** desktop link geht, mobile nicht und wird vielleicht auch nie gehen. Das mit den Blasen verstehe ich nicht genau.
- **dankesworte:** pizza.de hat für mich den gleichen stellenwert wie co.up (außer dass co.up keine sau kennt). Also entweder beide raus, oder beide rein. Mit Sam und Stefano müssen wir eh nochmal reden... ob wir das Spiel jetzt überhaupt so verwenden und veröffentlichen dürfen bzw. wie... aber sonst: _dann mach doch besser christophe!_
- **WIP:** bei nacht sieht sehr cool aus. gefällt mir gut.
- **kontaktdaten:** stimme zu, emails sähe doof aus. Das problem ist, wir haben halt keine Firma, kein Label, kein nix... ich würde es bei link und name belassen... vermutlich kann man statt einem weblink auch einen link machen mit der email-addy... also wenn man die bilder anklickt passiert auf dem desktop das gleiche wie hier: http://de.selfhtml.org/html/verweise/anzeige/a_href_mailto.htm

**Comment by ghost** [comment]
- link: ok. Fürs Blase, wir könnten nur die URL drinn schreiben... egal, sieht blöd aus. vergiss es :)
- dankesworte: dann bin ich für: "beide raus"! und für Sam und Stefano, gerne nochmal darüber sprechen... würde gerne wissen was sie davon halten, aber in alle Fälle  "verwenden und veröffentlichen dürfen" sicher...
- Kontaktdaten: ok

**Comment by ghost** [comment]
brauchen wir noch kleine zusätzliche animations? wir ein bisschen beweglich? UFO im Himmel? autos? oder so was?...

**Comment by Waog** [comment]
Sieht schon gut aus das Menü, also wegen mir muss da nix mehr gemacht werden. Aber wenn du Kapazitäten hast und mit allen Mandatory Tasks fertig bist, dann kannst du gerne noch Bewegung reinbringen:
- Autos oder Ufos fänd ich glaube ich zu "relevant". Also wenn da Animationen kommen, dann sollten es nur kleine Details sein, nichts was wie Aufmerksamkeit von Text oder den Links ablenkt. Vielleicht ein Stern der ein wenig flimmert, oder eine Wolke die sich ganz langsam fortbewegt.
- Animierte Avatare fänd ich auch gut, ja. Wie du schon sagst sollte das aber nur _ein bisschen_ sein.
- und wir müssen mal gucken wie die Regentropfen aussehen, wenn ich die als Partikel eingebaut habe... zur Not übernehmen wir deine Animation 1:1, aber ich schätze Partikel sehen besser aus.

**Comment by ghost** [comment]
hab Stars so gemacht
![stars](https://cloud.githubusercontent.com/assets/7753856/3523414/f29610b2-0758-11e4-9e37-af35682b82dd.gif)
es liegt och in drop box... finde cool wenn est 3-5 im bildschirm stehen mit unterschiedliche frequenz

**Comment by Waog** [comment]
:+1:  alrighty, baue ich ein

**Comment by ghost** [comment]
![credits](https://cloud.githubusercontent.com/assets/7753856/3528967/b92e6de2-0794-11e4-9203-2e05aa0dfdda.gif)
sieht jetzt so aus...

willste wat bestimmt für dich; Daumen hoch? Hand auf die Hüfte oder auch ein "Grüß" hand?

**Comment by Waog** [comment]
am sack kratzen.... nee scherz

n breites grinsen wäre cool, damit könnte ich mich identifizieren und/oder n peace :v:

**Comment by Waog** [comment]
geilo sogar die spiegelbilder bewegen sich mit... sehe ich jetzt erst... sehr geil :+1:

**Comment by ghost** [comment]
sieht so aus... und liegt im Drop Box (us.png)
![us](https://cloud.githubusercontent.com/assets/7753856/3537379/e88cfd94-081e-11e4-8f77-9f0c4cae582f.gif)

**Comment by Waog** [comment]
sieht gut aus :+1: 
aber was sind das für weiße dinger da recht neben mir?

kannst du die beiden als getrennte spritesheets machen? Dann kann ich die mit unterschiedlicher frequenz animieren.

**Comment by ghost** [comment]
rechts unten bei dir ist die Schrift aufs Subway treppen.. ich kann es ein bisschen dunkler machen wenn du alergisch bist :)

ok mach ich getrennt...

**Comment by Waog** [comment]
ähm... ja, ich sehe jetzt, dass es irgenwie am hintergrund ist und nix mit credits-text oder avataren zu tun hat. Aber ich hatte das Gitter bisher irgendwie nicht als subway-eingang interpretiert.

Und dass das schrift sein soll, war für mich noch weniger zu erkennen. Habe jetzt gedacht das ist Overlay-Schrift mit dem Text "_.."

Ich würde vorschlagen lass weg, oder mach irgend n dickes schild da hin, was breiter ist als 1 pixel :smile:

**Comment by ghost** [comment]
Oli.png und Chrs.png liegen jetzt im Drop Box separat...

ahaha " __ . .. . " jeder weiss das es "subway" bedeutet ;) hab das einchach dukler jemacht (ein grosser streifen sieht nicht so gut aus...) im neuen "bg_credits"

**Comment by Waog** [comment]
ja, war ne bildungslücke von mir... hätte beim morse-aphabet in der schule besser aufpassen müssen.

alrighty, ich baue das so ein :)

**Comment by Waog** [comment]
sag mal, irgendwo gabs doch auch schon den text fürs credits menü!? Mit _thx to stefano und sam, und game jam usw_ ... ich finde das nicht mehr, wo ist das?

**Comment by ghost** [comment]
hab das noch nichtim Drop Box gespeichert, da wir noch nicht ganz sicher waren mit was wir mit die Beide machen...
" Mit Sam und Stefano müssen wir eh nochmal reden... ob wir das Spiel jetzt überhaupt so verwenden und veröffentlichen dürfen bzw. wie... "
aber ich lege es dann erstmal soim drop...

**Comment by ghost** [comment]
thnaks1.png und thanks2.png sind drinn.Versteht man beide aber, das erste ist visuel viel besser (kürzer, pass genau gut zwischen die Türme)...

**Comment by Waog** [comment]
ich baue erstmal thanks2.png ein...

**Comment by Waog** [comment]
habe grafiken die schon in dropbox lagen eingebaut.

**Comment by ghost** [comment]
Da es Texte (Headlines und so) in English in der Zeitung Win und Lose gibt
![newspaper_small_lose](https://cloud.githubusercontent.com/assets/7753856/3955226/7543129c-26ff-11e4-882d-dca5ebad1422.png)
(Beispiel Lose)

hab an eine Freudin aus London  (Rémy) als "Lektorat" gefragt ob Sie drauf schauen könnte (damit wir keinen "broken English" haben) würde mich freuen wenn wir Sie  aufs THANKS liste haben...

und da könnte auch wegen sound #31 was kommen... (falls wir nicht alles selber machen)

wat denkste?

**Comment by Waog** [comment]
kein problem. Rémy kann in die credits.

**Comment by ghost** [comment]
coolio...

**Comment by Waog** [comment]
see #66
