### ISSUE TITLE
Powerup 3: 1up

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#150]
Kopf oder Herz kommt vom Himmel und gibt 1 Herz zurück.
- Grafik nötig.

**Comment by ghost** [comment]
![1up](https://cloud.githubusercontent.com/assets/7753856/12431973/c7f90e96-bef8-11e5-8d09-9710abbcc44c.png)

habe es erstmal so gemacht. Probiere mal damit. es Liegt in drop box.

wäre cool wenn ein shadow auf dem boden liegt (1-2 pixel) plus mini" bounce" auf dem Boden

**Comment by Waog** [comment]
Soll es so rotieren wie ne münze?

**Comment by ghost** [comment]
"rotieren" lieber nicht, könnte sehr cheap aussehen. 

Ich dachte mehr:
-entweder es kommt vom himmel, dann bounce auf dem Boden und bleibt villeicht 4sec.
 blinkt 3 mal, und verschwindet wenn du es nicht genommen hat

-oder: es kommt vom himmel, du muss unten stehen sonst explodiert es auf dem Boden (mit partikeln?)

-oder es blinkt auf dem Boden (+ sound design) 3 mal, steht 3-4 sek und wenn du es nicht genommen hast, verschwindet es wieder

**Comment by Waog** [comment]
eingebaut
