### ISSUE TITLE
Highscore Help

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#152]
we need a highscore help for some technical reasons... i implemented it, but we need some better graphics for this. See `dropbox > winscreen` for examples.

**We need graphics for:**
- [x] Speech Bubble (Green Frame as sepeate graphic, like CI green mint)
- [x] Help-Text as png ("Touch me!")

![image](https://cloud.githubusercontent.com/assets/5098472/12591237/1d995216-c467-11e5-90c3-f5d0f6abe400.png)

**Comment by ghost** [comment]
in drop > 02_win_screen...
3 elements:
-Bubble
-Text
-Green outline

**Comment by Waog** [comment]
brauche nur den grünen Rahmen von der speech bubble. Rahmen ums schild bitte weglassen.

**Comment by ghost** [comment]
done...

**Comment by Waog** [comment]
okay, ist drin
![image](https://cloud.githubusercontent.com/assets/5098472/12845551/fdc256ca-cc06-11e5-90a1-e7ae2441ad16.png)
