### ISSUE TITLE
HS sharing on facebook

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#153]
I implemented sharing the highscores on facebook. We still need graphics and texts for this. 

**Required Graphics:**
- [x] Share on Facebook Button (consider legal rights, before drawing an on version)
- [ ] One or more (random?) Wall-Images to Share.
  - [X] the images already finished
  - [ ] one simple picture (maybe black background + guy with electricity. Maybe guy + hydrant from mainmenu?)
  - [ ] something to emphasize the action factor of the game
  - [ ] gameplay screenshot like

**Required sharing text**
- [x] see images for current text

**Currently it looks like this:**

![image](https://cloud.githubusercontent.com/assets/5098472/12591520/6f59125c-c468-11e5-8911-bf1a3a8a4884.png)

![image](https://cloud.githubusercontent.com/assets/5098472/12591622/f5786072-c468-11e5-9d4e-5b9be462eddd.png)

![image](https://cloud.githubusercontent.com/assets/5098472/12591699/5ebb3b04-c469-11e5-80c0-659b2c936d99.png)

**Comment by ghost** [comment]
Facebook icon in drop > 02_win_screen
2 Facebook icon:
-normal
-(event)roll over

**Comment by ghost** [comment]
Drop Box > Logos > FB...

6 Variant for Facebook Pictures sharing.

**Comment by ghost** [comment]
SHARING text:
wir haben jetzt, 
"I defeated the hydrant!"
finde aber die Punch Line vom Newspaper ziemlich gut:
"A new super hero in Town!!!"

kann man noch überlegen...

**Comment by Waog** [comment]
habs erstmal so eingebaut. Die bilder finde ich aber zu langweilig. Ich würde keins davon anklicken, außer das aus dem Main Menu und das Newspaper... einfach nur häuser sind zu öde

**Comment by ghost** [comment]
"Die bilder finde ich aber zu langweilig."... na ja, lass uns dann Bilder von dir unter die Dusche machen, ahahahah

**Comment by Waog** [comment]
add a graphic with guy attacking hydrant... emphazising the **action** part of the game

**Comment by ghost** [comment]
FB button don't work for me...

**Comment by Waog** [comment]
jo, werde da eh noch mal dran basteln

**Comment by Waog** [comment]
FB share should work now...

**Comment by Waog** [comment]
Vorschlag:
![image](https://cloud.githubusercontent.com/assets/5098472/13812349/f4d48f9e-eb7b-11e5-9fb0-86b583f1aa8a.png)

**Comment by Waog** [comment]
Ingame implementation ready. FB wall images moved to #217
