### ISSUE TITLE
TETRIS Staubpartikeln auf dem Boden

### ISSUE THREAD

**Issue by ghost** [Waog/towelGuy#155]
wie es im Titel steht...

**Comment by Waog** [comment]
okay, hab was eingebaut. Vllt kannst du mir noch ne schönere Farbe für die Partikel sagen.
![image](https://cloud.githubusercontent.com/assets/5098472/12850917/83ee64a8-cc27-11e5-973d-9e29f47361c9.png)

**Comment by Waog** [comment]
@nostoner findet meine farben richtig sehr geil
