### ISSUE TITLE
Main Menu Logo mit 80% Transparenz einbauen

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#157]
bitte einmal das Main Menu Logo mit 80% Transparenz in Dropbox packen, damit ichs einbauen kann ohne die Transparenz zu programmieren.

![image](https://cloud.githubusercontent.com/assets/5098472/12817581/056dd2c8-cb53-11e5-896c-d8425dc8c109.png)

**Comment by ghost** [comment]
liegt in drop > 02_intro...

**Comment by Waog** [comment]
habs in den richtigen dropbox ordner verschoben (main menu) und eingebaut
