### ISSUE TITLE
buildings in photoshop cropen

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#159]
Kannst du mir mal bitte die Transparenten Bereiche von den Buildings wegcroppen? Construct macht dabei Fehler (es macht die Bilder breiter als vorher ^^):

Dropbox > Gameplay > buildings_1.png
Dropbox > Gameplay > buildings_2.png

**Comment by ghost** [comment]
also so:?
![screen shot 2016-02-04 at 21 44 00](https://cloud.githubusercontent.com/assets/7753856/12829083/853d2b5e-cb88-11e5-978d-51f3860c33e9.png)
![screen shot 2016-02-04 at 21 44 05](https://cloud.githubusercontent.com/assets/7753856/12829082/853c853c-cb88-11e5-8297-18ce90314791.png)

**Comment by Waog** [comment]
jap

**Comment by ghost** [comment]
ist in drop > 02_gameplay...

**Comment by Waog** [comment]
oki, habs eingebaut und es funktioniert jetzt
