### ISSUE TITLE
lightning on hydrant lifebar missing

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#163]

**Comment by Waog** [comment]
habs gefixed.

habe die hydrant lifebar bricks etwas anders gefärbt, die leichter zu zerstören sind. Was sagst du zur Farbe?
![image](https://cloud.githubusercontent.com/assets/5098472/12869221/459ed474-cd19-11e5-8d66-b3a55073fe3d.png)

**Comment by ghost** [comment]
es blinkt in die neue Farbe und verschwindet?

**Comment by Waog** [comment]
hä? die ersten 5 balken sind einfach konstant rosa anstatt rot. Das wars. Nix blinkt.

Und wenn man attacked dann kommt wieder der blitz.... ähnlich wie vorher, aber noch besser :)

**Comment by ghost** [comment]
ok, style.
"ähnlich wie vorher, aber noch besser :)"
wenn du das sagt...
