### ISSUE TITLE
Shadow/Spotlight Tutorial

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#169]

**Comment by Waog** [comment]
hab was eingebaut, warte auf grafiken.
Das _plötzliche_ einblenden des Spotlights sieht amateurhaft aus. Es sollte Reinfaden oder irgend ein anderer Effekt da sein. Oder die Szene sollte direkt mit Spotlight starten...

**Comment by ghost** [comment]
in drop: gamepaly > shadow monster

**Comment by Waog** [comment]
mach mal n screenshot wie es aussehen soll

**Comment by Waog** [comment]
ich glaub die zunge im mund sieht nicht gut aus. Musste 3 mal hingucken bis ich vertsanden habe was das sein soll... lieber nur zähne!?

**Comment by ghost** [comment]
nope... kauf dir eine Brille ahahah

**Comment by ghost** [comment]
![Uploading Screen Shot 2016-02-07 at 01.12.07.png…]()

**Comment by Waog** [comment]
die augen in dropbox sehen aber anders aus ... BÖSER. die in Dropbox gefallen mir besser

**Comment by ghost** [comment]
![screen shot 2016-02-07 at 01 12 07](https://cloud.githubusercontent.com/assets/7753856/12870155/f38c142a-cd37-11e5-86af-c898b126c9a3.png)
 falsche layer...

**Comment by Waog** [comment]
genau die augen mein ich :)

**Comment by Waog** [comment]
echt so tief den mund?

**Comment by ghost** [comment]
kann man auch hoher, wie du möchtest

**Comment by Waog** [comment]
jut, habs gleich eingebaut. Exportiere es gleich... müsste also so in ner Stunde verfügbar sein :P

**Comment by Waog** [comment]
okay eingebaut, aber müssen wir nochmal zusammen angucken und finetunen
