### ISSUE TITLE
Bloody Finger in Tutorial

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#170]
- [x] "Attack"-Schrift nach links schieben, so dass platz für blutigen Finger ist
- [x] Finger ist kürzer aber nciht breiter im dritten frame

**Comment by Waog** [comment]
Habs schonmal eingebaut, warte noch auf deine Grafiken

![image](https://cloud.githubusercontent.com/assets/5098472/12869520/516ab5ee-cd22-11e5-9375-964043baf458.png)

**Comment by ghost** [comment]
in drop >

**Comment by Waog** [comment]
okay, habs eingebaut

**Comment by Waog** [comment]
siehe Häckchen oben -.-

**Comment by ghost** [comment]
probier mal mit dite: gameplay > tutorial > tutorialattack-sheet.png

**Comment by Waog** [comment]
was ist das fürn format?? Damit kann ich nix anfangen... hab dir mal das wie ichs brauche in die dropbox gelegt.

**Comment by ghost** [comment]
das ist dein super EXPORT format...

**Comment by ghost** [comment]
habe es ausgetaucht...

**Comment by Waog** [comment]
weißt du warum es EXPORT heißt? weil ich es nicht importieren kann ;)

**Comment by Waog** [comment]
okay, done
