### ISSUE TITLE
RETRY Button win Menu

### ISSUE THREAD

**Issue by ghost** [Waog/towelGuy#172]
sollte man nach denken ob ein RETRY button nicht besser wäre im WIN menu (wie im LOSE menu zB.
sonst muss man erstmal auf MENU und dan auf PLAY.

ist nicht gut, wenn ich mein score verbessern will (mehrmals spielen und gewinne nach ein ander) der Gamer muss immer wieder die zwei steps machen... > langweilig, und man verlier lust aufs Spiel/sich verbessern.

**Comment by Waog** [comment]
Dagegen, keine neuen Features!

**Comment by ghost** [comment]
?! es geht nicht um "neuen Features"...

Geht um Game Architektur: 
der player ist nach zwei/drei mal gelangweiligt vom prozess: WIN screen > click:  Intro screen > Play button: und nur dann kann man wieder spielen... 
ergebnis: spielt weniger weil es meeeega langweilig ist.

0110010101101001011011100110011001100001011000110110100000100000011101010110111001100100001000000110110001101111011001110110100101110011011000110110100000100001

**Comment by Waog** [comment]
@nostoner Wo soll der button platziert werden? Wir haben nicht wirklich platz dafür...
![image](https://cloud.githubusercontent.com/assets/5098472/13554941/d66baeb2-e3b4-11e5-81d7-a859c0a8b092.png)

**Comment by Waog** [comment]
added a retry button like this now:
![image](https://cloud.githubusercontent.com/assets/5098472/13555038/08fdf400-e3b7-11e5-8a74-6c3d16b0da83.png)

**Comment by Waog** [comment]
position it like this:
![image](https://cloud.githubusercontent.com/assets/5098472/13883807/75f9bca6-ed2b-11e5-9f71-16fc8387217b.png)

**Comment by Waog** [comment]
fixed
