### ISSUE TITLE
Required Sounds/Music List

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#174]
- [ ] Global
  - [ ] Button-Sounds
- [ ] Main Menu
  - [ ] Logo-Blitze
  - [ ] .(Play-Button)
- [ ] Credits
  - [ ] Tropfen
- [ ] Comic
  - [ ] Touch
  - [ ] v4: Glitzer/Splash
  - [ ] v5: Glitzer + Zoomin
  - [ ] v6: Shock
  - [ ] v7: Wind-Stoß
  - [ ] v8: Aieee!
  - [ ] v9-12: Flatter-Hose
  - [ ] v13: renn-sound (flintstones?)
  - [ ] v14: fliegen
  - [ ] v15: Glitzer von oben
  - [ ] v16-17: Ray
  - [ ] v18: runterfallende hose
  - [ ] v19: wackel/beben
  - [ ] v20: explosion + pffrrscchh
  - [ ] Play-Button (?)
- [ ] Gameplay
  - [ ] Pause Menu
    - [ ] 1-2 simple Blib-Töne für Animation
  - [ ] Tutorial
    - [ ] Segelnde Hose
  - [ ] Demon Intro
    - [ ] Spotlight-Start
    - [ ] Evil Laughing
    - [ ] countdown
  - [ ] Core Gameplay
    - [ ] verschiedene musiken für verschiedene Spielfortschritte (player life oder hydrant life)
    - [ ] haupt-tropfen
    - [ ] guy steps
    - [ ] gulli-hand
    - [ ] fliegen
    - [ ] attack
    - [ ] hurt
      - [ ] verwundbar werden (flashing)
    - [ ] Powerups
      - [ ] 1up
        - [ ] auf den boden fallen
        - [ ] collect
        - [ ] disappear
      - [ ] nian cat
        - [ ] nian-music
        - [ ] appear
        - [ ] disappear
        - [ ] collected
        - [ ] flying up
        - [ ] Rainbowshield
          - [ ] tropfen auf shield
          - [ ] disappear
        - [ ] Tetris
          - [ ] musik (rechte?)
          - [ ] bewegen
          - [ ] drehen
          - [ ] fallen
          - [ ] flashing
          - [ ] accelerating
          - [ ] boden crash
          - [ ] player crash
  - [ ] Win/lose Animation
    - [ ] foto flashes
    - [ ] win/lose musik/sound
    - [ ] bildschirmwechsel
    - [ ] powerup explosion
- [ ] Newspaper
  - [ ] sound/music
  - [ ] bildschirmwechsel
- [ ] Lose Menu
  - [ ] blitz
  - [ ] jogger steps
  - [ ] gebüsch-rascheln
  - [ ] guy-steps
  - [ ] wind + handtuch
- [ ] Win Menu
  - [ ] too slow
  - [ ] touch sound
  - [ ] eingabe registriert/gespeichert
  - [ ] sehr simple sounds für:
    - [ ] foto
    - [ ] reden (2-3 verschiedene?)
    - [ ] bellen
    - [ ] hero-blitzi
- [ ] High Score Menu
  - [ ] taube + kacke
  - [ ] körner/futter sound
  - [ ] picken
  - [ ] möven

**Comment by ghost** [comment]
i wrote a mail to this guy... (waiting for an answer)

rolemusic (spain)
http://rolemusic.sawsquarenoise.com/
http://freemusicarchive.org/music/Rolemusic/

**Comment by Waog** [comment]
coppied from #91:

> NES - Turtle Ninja
> https://www.youtube.com/watch?v=5kK8mFYbl1s

**Comment by ghost** [comment]
got an answer from:
rolemusic (spain)
http://rolemusic.sawsquarenoise.com/
http://freemusicarchive.org/music/Rolemusic/

–––––––––––––––––––

Hi Chris

The game looks awesome, and is a funny idea, yes I am interested in doing music. About the prices I usually take 60€ per loop of at least 1:15 minutes. I can give cheapest rates (25€) if the music is distributed with a CC-BY license, so everybody can use it and credit it as Towel Defence OST, Just I did with Spacejacked http://freemusicarchive.org/music/sawsquarenoise/RottenMage_SpaceJacked/ , so both benefit from mutual promotion. But I'm open to hear another posible ways.

I usually work before and if you like the music then you can use it and pay after you listen.

Also my availability depend on the deadlines.

Best regards
José

**Comment by Waog** [comment]
sehr nice! das wo ich jetzt so reingehört hab, war mir zu langsam fürs core gameplay. aber darüber kann man ja mit ihm (und dir :stuck_out_tongue:) reden. 25€ find ich total okay

**Comment by Waog** [comment]
achso, ist damit jetzt unsere quest erledigt nach musik zu suchen? würde lieber an anderen baustellen arbeiten.

**Comment by ghost** [comment]
_"achso, ist damit jetzt unsere quest erledigt nach musik zu suchen? würde lieber an anderen baustellen arbeiten."_
finde auch,  passt ganz gut..

haste Zeit Morgen Abend (18h30 - 19h) nach der Arbeit für nen short treffen?
oder skype?

wäre wichtig, damit wir ihm richtig briefen können.

**Comment by Waog** [comment]
jo, 18:30 - 19:00 geht klar. Skype oder bei mir?

**Comment by ghost** [comment]
komme dann vorbei, ist auf dem Weg nach Hause...

**Comment by Waog** [comment]
:+1:

**Comment by ghost** [comment]
mail + jpg overview ist in Drop. you can check it. If stuffs sounds odd for you, let me know.
will send it early tomorrow...

**Comment by Waog** [comment]
Okay, I reviewed both documents and corrected a bunch of grammar and wording.

I also did a slight change to text above "tutorial" in the chart. Maybe you can beautify this with photoshop ;)

For the rest I'm fine with the revised version. :)

**Comment by ghost** [comment]
## José wrote:

Hi Chris

About the price I consider 90 to 100€ the cheapest I can go with the free CC-BY licences and sound efects. (about 10-15€ per loop double discount 50% for being short, and 50% for free license, sound effects)

Yes the schema of the songs make full sense, and about two or three weeks seems a nice deadline. 

About the sound yes it will help an small idea of how you want the overall sound, or if you have a game that you like the music, my main genre is 8bit chiptune, so blip blops effects make it easy, or you can also search my rolemusic or sawsquarenoise profiles to see what tunes you feel you like.

---

you understand it also as: "100 bucks for everything" or i just don't get it?

![150216_td_charts_for_music](https://cloud.githubusercontent.com/assets/7753856/13111698/78c9d88c-d587-11e5-80ea-4844826f5a10.jpeg)

**Comment by Waog** [comment]
Yep, "100 bucks for everything".
We can also offer him further 100€, if we earn money with the game, even if he didn't ask for it. Just so he feels a little more motivated :)

Can we compose the answer the same way we did it for the last email?

**Comment by ghost** [comment]
OK, we offer him 200€ for everything (i pay 20 bucks and you 180 right? ho ho ho). We explain, that we don't want to push the price to much down, blah blah... i think it's fair.
as you said, is good for motivation!

on top of that, i think it will be also cool (for him AND for us) to propose him a place in the "credits" screen with avatar and Co (as we already have)
the idea is: it gives more weight to the Game. 3 people, 3 fields of competence > gives the game more professionalism. 
To that, he already have some fans... > and that's good for us :)

what do you think?

_Can we compose the answer the same way we did it for the last email?_
yep...

gonna probably write it yet tonight. you can check it in drop' later and i'll send it tomorrow...

**Comment by Waog** [comment]
I agree with all of you points (except the 180:20 joke). Maybe I'll only review you text tomorrow afternoon.

**Comment by ghost** [comment]
i have already sent the email... and got the answer back.
u can check it in drop.

sounds like a go! :)

**Comment by ghost** [comment]
"Hi Chris

Everything sound perfect
I understood the guidelines, I'll be working on it the following days

Cheers"

just have to wait...

**Comment by ghost** [comment]
Hellöööö Öli,

habe von José wat bekommen :) (Protokoll liegt im Drop falls du willst)

---

Hi Chris

Here is a draft preview on what I had been working, the loop ones are recorded twice then fade out, still have to polish some stuff and adjust the volumes

https://dl.dropboxusercontent.com/u/12498165/towel.zip

Let me know what you think

Cheers

---

habe parallel gespielt und music an gemacht, macht schon was :)
lass uns einfach am Samstag darüber kwatchen oder? dann können wir him zusammen Feedback schicken.

**Comment by Waog** [comment]
jo, samstag 14h dann :)

**Comment by Waog** [comment]
not needed any longer
