### ISSUE TITLE
FB like (constant) reward

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#188]
- [x] Graphics: like button für Main Menu
- [ ] Graphics/Animation: loading/connecting graphics
- [x] Graphics/Animation: like button transforms into recognizable bonus-icon (ufo+laser)
- [x] Gameplay-Bonus: Ufo which destroys drops occasionally for the first 30 game seconds with a laser

**Comment by ghost** [comment]
facebook like button in drop > main menu > like.png
![screen shot 2016-03-28 at 18 35 40](https://cloud.githubusercontent.com/assets/7753856/14083175/9267b0aa-f514-11e5-82f4-0350854413c4.png)

**Comment by ghost** [comment]
Hi Splinter ( immer so lustig... XD
habe die letzte Version gerade gespielt, magste meine süße Buttons "like" und "Tweet" nicht?
(übrigens ist es "Tweet" oder "Follow"?)

Habe nochaml die CI von FACEBOOK durch geschaut... wie oben gemacht ist nicht ganz richtig, und wie du es gebaut hast muss auch nicht unbedingt sein. Also solage es noch nicht ganz geklärt ist wäre ganz gut das du es austauscht (wegen Publisher suche) damit es einfach grafischer aussieht. Muss aber in alle fälle nochmal dran...

**Comment by Waog** [comment]
Hi April,

nein, ich mag die nicht. Aus zwei Gründen:
1. Keine Icons... Du kannst gerne Icons mit Text kombinieren, aber icons total weglassen ist in dem Fall total daneben.

![image](https://cloud.githubusercontent.com/assets/5098472/14140558/0053d466-f67a-11e5-9800-ea8a42903f19.png)
1. Ich glaube wir sollten alles was externe links sind nicht wie unsere anderen Buttons modellieren, weil sie keine Spiel-Funktionalität verkörpern. Das ist mehr wie weggehen vom Spiel, als wie irgendwas im Spiel zu tun.

D.h. Twitter (#189 #191) , FB (#190 #153) und auch RedRittles Links (#197) sollten keine normalen Buttons sein, das ist irreführend.

**Comment by ghost** [comment]
Liebe April,

gerne möchte ich auf deine Punkte eingehen und sie auch gerne noch weiter mit dir am Freitag diskutieren :)

> erstmal, es muss dir klar sein, dass diese beide Buttons nicht eine Top Prio für die (User)Interface ist.
> Wir haben eine Hierarchie für die Buttons (wie alle UI verlangert), und diese beide Element sind ziemlich (wenn nicht gaaaanz) unten davon.

FB und Twitter integration ist in meinem Portfolio nicht ganz unten in der Prioritätenliste. Ganz im Gegenteil es ist für mich relevanter als 90% unserer restlichen (eher grafischen) features.

> Ob icons drin sein mussen oder nicht, spielt keine Rolle für den button, da die "Farben und Wörter" einfach gelernt sind. 
> Also "aber icons total weglassen ist in dem Fall total daneben." ist kein Argument sondern eine Emotion.

Auf die icons lege ich deswegen so viel wert, weil wir [localization](http://de.slideshare.net/flashgamm/softgames-dev-gammkiev/16) verkackt haben, was für publisher relevant ist. Es gibt einige die unser Spiel deswegen nicht kaufen werden.
![image](https://cloud.githubusercontent.com/assets/5098472/14144597/a1c3601c-f690-11e5-8770-d4b51184b445.png)
Icons sind für mich ein Versuch die verkackte Lokalisierung wenigstens noch ein wenig zu retten.

> Sowie dein zweiter Punkt "...weil sie keine Spiel-Funktionalität verkörpern. Das ist mehr wie weggehen vom Spiel, als wie irgendwas im Spiel zu tun.", nochmal geschmack Sache mit dünne Argumentation ohne wichtiger Kernbotschaft.

Auch das sehe ich nicht so. Man lässt buttons ja nicht nur zum Spaß wie dreidimensionale Knöpfe an irgend einem Gerät aussehen, sondern um eine Analogie zur echten Welt herzustellen. Und diese Analogie trifft auf Links nicht so gut zu.

> Von meiner Sicht, hätte ich lieber dass du es einbaut (wie du mal gesagt hattest irgendwann am Anfang des Projekts und by the way, wie mann es tatzächlich in ein Unternehmen macht), und wir schauen und reden nochmal drüber, statt allein anschauen/entscheiden (und was selber basteln)
> Ich verlange es aber nicht von dir, weil du nicht für mich arbeitet (sodern mit mir).
> Jeder hat seine Kompetenz und man sollte damit weiter (mit Spaß) machen.

Meine zwei hässlichen Buttons waren sicher nicht als finale Version gedacht, sondern als Platzhalter für deine pr0-Grafiken. Also kein Grund beleidigt zu sein ;)

Ich kanns erstmal einbauen. Es macht nur doppelte Arbeit für mich, wenn wir es sowieso wieder austauschen. Und man sieht bereits in deinem Screenshot wie es aussehen wird auch ohne dass ich es eingebaut habe.

> Also, solage ich kein Hakenkreuz male, würde ich mich freuen wenn du mich ein bisschen Freiraum für meinen Teil lässt. Ich werde langsam müde alle Irrelevante klein Fürtz zu debatieren.

Ich empfinde es bereits als sehr viel Freiraum was ich dir einräume. Musste mich bereits sehr viel zurückhalten. Aber das ist tatsächlich nur eine meiner irrelevanten Emotionen.

Aber da mir das Social-Thema sehr wichtig ist und dir eher egal, wäre es nett, wenn du hier mehr auf meine Wünsche eingehen würdest ;)

> Ich freue mich auf Diskussion und Konzept die wir zusammen entwicklen können, aber irgendwann muss auch klar sein dass ich auch nicht für dich arbeite (sondern mit dir). 

Es tut mir Leid wenn dieses Gefühl entstanden ist. Verstehe jedoch nicht genau wodurch ich es verursacht habe.

> Hoffe es macht Sinn für dich, am besten kwatchen wir nochmal am Freitag oder Samstag darüber

Ich bitte darum. Deine Mail kam doch sehr angespannt rüber... wäre cool wenn wir solche Probleme aus der Welt räumen können bevor sie eskalieren. Vllt kuscheln wir einfach mal ein bisschen.

:kissing_heart: 
dein Splinter :rat:

**Comment by Waog** [comment]
liegt in drop

**Comment by Waog** [comment]
übrigens fehlt die loading graphic...

**Comment by Waog** [comment]
implemented
