### ISSUE TITLE
twitter follow (constant) reward

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#189]
- [x] Graphics: follow button für Main Menu
- [ ] Graphics/Animation: loading/connecting graphics
- [x] Graphics/Animation: follow button transforms into recognizable bonus-icon (ufo + heart)
- [x] Gameplay-Bonus: Ufo which drops hearts if player got hit

**Comment by ghost** [comment]
Twitter "follow" button in drop > main menu > like.png
#188

**Comment by Waog** [comment]
finde ihn kacke, siehe kommentar in #188

**Comment by ghost** [comment]
das Wort "kacke" ist ziemlich hart (besonders wenn es "mein Job" direkt angriff).  
Ich vermute aber, dass es nicht böse gemeint ist. Diplomatie beschädig nicht besonders wenn du irgendwann in ein Unternehmen (mit oder für Leute) arbeiten willst... follow up #188 :)

**Comment by Waog** [comment]
liegt in dropbox

**Comment by Waog** [comment]
übrigens fehlt die loading graphic...

**Comment by Waog** [comment]
implemented
