### ISSUE TITLE
Gameplay Concept

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#19]
Vorschläge und Ideen:
- User muss verschiedene Buttons richtig drücken (nicht nur Space), die er vorgegeben bekommt bekommt. Vllt auch in bestimmtem Rythmus.
  - Umsetzung
    - z.B. indem Hydrant die Farbe wechselt und somit Tasten symbolisiert.
    - Einführung in mehreren Levels/Schwierigkeitsgraden.
  - Nachteile:
    - Spieler für ein banales minispiel viel zu viele funktionen erlernen.
    - Schwer auf touch Displays umzusetzen. Lieber wenig Mechaniken/Möglichkeiten, mit viel Tiefe.
- Hydrantenreparatur (Hydrant regeneriert, wenn man zu lange nicht angreift).
  - Vorteile: Mehr Action, keine Verzögerung nach Attacks nötig.
  - Nachteil: Weniger Entscheidungsfreiheit für den Spieler (klare Präferenz zum Schießen wird erzwungen)
- Kombi-Bonus: Spieler verursacht mehr Schaden, wenn er oft hintereinander space drückt, ohne sich zu bewegen.

**Comment by Waog** [comment]
Diskussion teilweise in die anderen Issues verlagert.

**Comment by Waog** [comment]
- Ich bin gegen den ersten Punkt (verschiedene buttons/rythmus). Meiner Meinung nach sollten wir das Spiel-Prinzip so simpel lassen wie es jetzt ist und lieber Zeit in finetuning investieren, damit das was schon da ist sich noch besser anfühlt.
- Hydrantenregeneration ist spannend. Sie würde dem Spieler aufzwingen noch mehr und schneller auf Space rumzuhämmern und weniger Zeit mit unnötigem Ausweichen zu verbringen. Also mehr Action, Dadurch könnte man vielleicht den Delay nach den Angriffen komplett weglassen. Nachteil ist, dass der Spieler sich nicht mehr so frei entscheiden kann, ob er lieber ausweicht und gelegentlich schießt oder umgekehrt. Die taktische Entscheidung wäre stets eindeutig.

Was meint ihr?

**Comment by ghost** [comment]
#25 
sonst findest du gut ein art "Verteidigung hit combo"? muss naturlich irgendwann kommunizieren werden (im spiel? tutorial?) aber wäre wat wie:"Pfeil left, Pfeil left, Pfeil right, space par, space bar, Pfeil right" (super NES style) und dann produziert er ein "Mega Strahlung Shild keine Ahnung wat"  die entfernt die Tropfen (vom Himmel kommen) im Bildschirm...
?  ist es cool? ist es machbar? haben wir genug Events?

**Comment by Waog** [comment]
Ich glaube das würde ich nicht in dieses Spiel einbauen... das ist ein vollkommen anderes Spiel-Konzept pattern nachzuahmen (wie bei tekken oder guitar hero). Es bringt dem Spiel glaube ich wenig mehrwert und verursacht sehr viel aufwand für uns (ja, auch viele events). Ich würde vorschlagen wir machen erstmal das Core-Gameplay fertig, und adden dann vielleicht derartige zusatz-features, später, wenn wir noch lust haben.

Du hast mich auf eine weitere Idee gebracht. Memo: Der Spieler muss powerups einsammeln/auffangen... dadurch muss er nicht NUR ausweichen und schießen, sondern auch an bestimmte positionen laufen.
