### ISSUE TITLE
facebook highscore share (one time bonus)

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#190]
- [x] Graphics: share FB button für win screen
- [x] Graphics/Animation: loading (sanduhr oder wheel of doom)
- [x] Graphics/Animation: Bonus (frog rain)
- [x] Gameplay-Bonus: frogs instead of drops

**Comment by ghost** [comment]
in drop > win screen

**Comment by Waog** [comment]
war bereits eingebaut... die grafiken für den reward fehlen noch alle

**Comment by ghost** [comment]
> > > Disable "Frogs"after one attempt

**Comment by Waog** [comment]
done
