### ISSUE TITLE
twitter highscore share (one time bonus)

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#191]
- [x] Graphics: share FB button für win screen
- [x] Graphics/Animation: loading (sanduhr oder wheel of doom)
- [x] Graphics/Animation: Bonus (sace invader shaped drops)
- [x] Gameplay-Bonus: space invaders instead of drops (maybe they an stop short before impact)

**Comment by ghost** [comment]
in drop > win screen

**Comment by Waog** [comment]
hab das neue icon eingebaut. Ich weiß du bist ein fan von _keine icons_ und _walls of text_, aber könntest du den _**twitter-vogel**_ anstatt dem _**t**_ auf den button malen?

**Comment by ghost** [comment]
> > > Disable "Space Invaders"after one attempt

**Comment by Waog** [comment]
done
