### ISSUE TITLE
export to android app store

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#193]
For Beta Testers only:
1. https://play.google.com/apps/testing/net.waog.toweldefence
2. https://play.google.com/store/apps/details?id=net.waog.toweldefence

**Comment by Waog** [comment]
Es ist jetzt online, wirf mal nen blick drauf

**Comment by ghost** [comment]
yey cool, 
ist aber nur zu sehen  fun eingeladene Tester wenn ich es kappiere oda?
![screen shot 2016-04-02 at 10 12 41](https://cloud.githubusercontent.com/assets/7753856/14225239/a08f9b5c-f8bb-11e5-911f-e260211f8c5d.png)

zweite URL funktionniert leider nicht...
![screen shot 2016-04-02 at 10 12 54](https://cloud.githubusercontent.com/assets/7753856/14225240/cabee6c6-f8bb-11e5-9028-33ac3e11c3c0.png)

grundzätzlich muss ich jetzt schnell noch ein Smartfone mit Android kaufen um das Spiel zu Testen :)

**Comment by Waog** [comment]
ja, das ist nur für tester sichbar, also für uns beide.

Das mit der URL hatte ich gestern auch... das hat aber nach einer Weile von alleine funktioniert. Ich glaube es dauert einfach eine Weile bis das Spiel auf allen Google-Servern verbreitet ist... probiers mal in nem halben Tag nochmal.

![image](https://cloud.githubusercontent.com/assets/5098472/14225462/e087a350-f8c3-11e5-89f2-207e44a2c3e7.png)

**Comment by Waog** [comment]
ich musste nochmal alles neu machen im play store. habe die links oben ausgetauscht. du musst dich nochmal neu anmelden.

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

Hab dich lieb :heart:

**Comment by ghost** [comment]
okay, habe mich wieder angemeldet und warte das den "detail link" läuft...

hmmm, Lorem Ipsum... ist aber lateinisch oder? hu hu hu (joke)

:heart::heart::heart:

**Comment by nostoner** [comment]
okay, habe mich wieder angemeldet und warte das den "detail link" läuft...

hmmm, Lorem Ipsum... ist aber lateinisch oder? hu hu hu (joke)

:heart::heart::heart:

**Comment by Waog** [comment]
Habe die aktuellste version im Appstore. kannst du die sehen?
