### ISSUE TITLE
add red rittles links into the game

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#197]
- [ ] graphics for credits menu
- [ ] link it to redrittles.com

**Comment by ghost** [comment]
button in drop box > Credits

would be cool to put it beside the music button (right corner on the far left)

**Comment by Waog** [comment]
Fänds cool, wenn die grafik nochmal überarbeitet wird und kein Button ist... siehe kommentar in #188

**Comment by Waog** [comment]
button bleibt so. derzeit verlinkt auf twitter oder FB, da redrittles.com nichts enthält
