### ISSUE TITLE
HS sharing on Tweeter

### ISSUE THREAD

**Issue by ghost** [Waog/towelGuy#204]
habe jetzt das statt das logo...
es liegt im Drop > HS

![screen shot 2016-03-29 at 21 17 08](https://cloud.githubusercontent.com/assets/7753856/14120696/41ab7bf2-f5f4-11e5-9a72-926cf7ad6469.png)
statt

![screen shot 2016-03-29 at 21 25 06](https://cloud.githubusercontent.com/assets/7753856/14120802/cdf50a1a-f5f4-11e5-925a-8f5ba2e1df8a.png)

**Comment by Waog** [comment]
hab das neue icon eingebaut. Ich weiß du bist ein fan von _keine icons_ und _walls of text_, aber könntest du den _**twitter-vogel**_ anstatt dem _**t**_ auf den button malen?

**Comment by Waog** [comment]
duplicate of #191
