### ISSUE TITLE
Cheat Activation Graphics

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#205]
Habe mal grafiken eingebaut welche Cheats grade aktiv sind... willst du nochmal schönere dafür machen, oder wollen wir meine geile paint-grafik als easter-egg drinlassen?

![image](https://cloud.githubusercontent.com/assets/5098472/14142550/b5bb55de-f686-11e5-8de2-87ce004a0814.png)

**Comment by ghost** [comment]
ahahah, geil! finde so fast besser :)

**Comment by Waog** [comment]
bleibt so
