### ISSUE TITLE
Export to Different Platforms

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#21]
- Android
- iOS
- Win8
- Chrome Web App
- Different Browsers
- any more?

**Comment by Waog** [comment]
Can't properly export the game from Construct 2 without a non-free edition of Construct 2. The required licence costs £79.99.

Since the browser-version seems to work well, it would be great if we can spend the first 80£ earned with the browser-version for this licence. So we could also publish it in the different mobile stores.

**Comment by Waog** [comment]
A new version of Cocoon JS was released, which promises to fix some issues with construct 2. Maybe exporting is possible now.
From the news letter:

**COCOONJS 2.0.1**
_Improvements to Canvas+_
Canvas+ now correctly handles HTML5 exportations from Construct 2 Get more info here.

**COCOONJS AND CONSTRUCT2 PERFORMANCE TEST**
Scirra, the company behind Construct2, a great HTML5 game authoring framework, released “The Great HTML5 Gaming Performance Test: 2014 edition” weeks ago. In this test, they used a Construct2 based game demo and executed it in numerous environments. Want to know the results? Read [here](http://ludei.us6.list-manage2.com/track/click?u=035d35c1b796455b04906c40e&id=e562ba272c&e=3f6f6ad12a)

**Comment by ghost** [comment]
Wir haben zwei schwarze Balken (links und rechts) kann man ein art "autosize" im Browser einfügen?

**Comment by Waog** [comment]
Muss ich recherchieren, ob das mit Construct2 geht. Ich vermute eher nicht.

**Comment by Waog** [comment]
Autosize sollte für mobile platformen genauso funktionierten wie für brower (see #54)

**Comment by Waog** [comment]
Export scheint jezt ordentlich zu klappen... werden also auch eine mobile version machen können :)

**Comment by Waog** [comment]
das spiel läuft auf meinem tablet... Sounds kommen beim ersten abspielen immer verzögert. Vielleicht brauchen wir einen ladebildschirm, um alle assets einmal zu laden :\

**Comment by ghost** [comment]
ist nicht schlimm oder? Kann das Ladebildschirm eine Animation sein? (wie beim Flash Seiten oder so)

**Comment by Waog** [comment]
- ist nicht schlimm, aber ziehmlich schwach von construct2. Man sieht am anfang immer diesen ladebildschirm von construct2... was zur hölle lädt construct da so lange, wenn nicht die sounds und grafiken?
- erstmal abwarten, ob ein ladebildschirm nötig ist... ich hoffe es geht ohne
- verstehe nicht ganz was du mit animation meinst... ich glaube wir könnten ihn genauso bauen wie das hauptmenü usw... aber je weniger grafiken/sounds da drin sind, um so besser... weil die ja ohne ladebildschirm geladen werden müssen :)

**Comment by ghost** [comment]
dachte nur wie vor 5 jahre war trend auf "flash Seiten" einden Ladebalken (oder Prozent ladezahl) und eine kleine einfache anim... 
aber ok, erstmal warten.

**Comment by Waog** [comment]
The People of CocoonJS forgot to include the construct-options in their cloud compiler. We need to wait for the next version of CocoonJS to export it. [see comments here](http://support.ludei.com/hc/en-us/articles/202372276).

It can be tested on mobile platforms anyway, just not be released.

**Comment by Waog** [comment]
erster Erfolg... Das Game läuft im korrekten Format auf meinem Nexus7. Es stürzt allerdings ab, sobald das Gameplay beginnt :boom:

**Comment by Waog** [comment]
So, habe mein Nexus7 formatiert und mir ein neues Adroid installiert. Unsere App gebaut und sie läuft mit einigen Macken und laggy game-play :)

**Comment by Waog** [comment]
to big
