### ISSUE TITLE
Discussion Packaging & Marketing

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#218]
Hi @nostoner,

Ich mache hier mal eine neue Topic für den aktuellen milestone auf und räume auch grade die restlichen Issues auf. Implementation ist jetzt fertig für Sounds fehlt nur noch die Mail und das Geld an José.

Hast du die Woche nochmal Zeit um weiteres Vorgehen zu besprechen? Als nächstes bräuchten wir denke ich Wall-Images für sharing auf Twitter und Facebook und fertige FB und Twitter Seiten. Dannach können wir releasen schätze ich.

**Comment by Waog** [comment]
wie siehts aus bei dir? hast 2 wochen nix von dir hören lassen...

**Comment by ghost** [comment]
Jep sorry, arbeit...
hätte Zeit nächste Woche am Freitag oder Samstag, passt für dich?

**Comment by Waog** [comment]
nee sorry, kann dieses wochenende nicht....
wie ist es nächste woche bei dir?

**Comment by ghost** [comment]
ok, no prob!
kann sich für mich ziemlich schnell ändern uf Arbeit, aber soweit wäre nächste Freitag ok für mich und für dich?

**Comment by Waog** [comment]
Jop, Freitag würde passen. Welche Uhrzeit?

**Comment by ghost** [comment]
15h? (für 3 Stunden oder so)

**Comment by ghost** [comment]
keine meldung, ich bin traurig ;)

ok, dann lass uns dann nächste Woche Freitag um 15h treffen, jep?

**Comment by ghost** [comment]
Hello!
Wie sieht es aus bei dir für Morgen 15h?

**Comment by Waog** [comment]
So, bin wieder verfügbar... wie siehts diese woche bei dir aus?

**Comment by ghost** [comment]
yey! Freitag, 14h bei dir?

**Comment by Waog** [comment]
jap, passt. wie lange dann?

**Comment by ghost** [comment]
bis 18h finde ich gut oder?

**Comment by Waog** [comment]
okay, klingt gut, bis Freitag :)

**Comment by ghost** [comment]
Hi Splinter,
wie läuft es bei dir? bin gerade zurück aus dem Uralub. Werde leider auch den kommende Wochen weniger Zeit haben, aber irgendwann müssen ir das Paket Rund bekommen, oder?
Wie sieht's aus bei dir?

Habe schnell meine Mails überflogen und José hat sich gemeldet wenn ich richtig bin...

cheers,
C.

**Comment by ghost** [comment]
Hey Oli, wie sieht's aus bei dir?

**Comment by Waog** [comment]
Hiho, lebst du noch @nostoner ? :)

**Comment by ghost** [comment]
ich schon :) ich dachte du bist schon in Hong Kong!

wäre cool wenn wir uns nächste Woche treffen könnte um die Sache mit José zu klären. haste Zeit nächste Freitag, 14h bei dir? wir brauchen nicht lange...

best
C.

**Comment by Waog** [comment]
Jo gerne, würde das Ding auch gerne noch fertigstellen, also nicht schlimm wenn du etwas mehr Zeit mitbringst ;)

**Comment by ghost** [comment]
habe das Geld geschickt...

LG,
C.
