### ISSUE TITLE
Logos, Banner, etc.

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#22]
We need tons of logos for all different devices, platforms and websites.
Should be one of the last tasks we work on.
Which logos are needed, hardly depends on Issue #21 .

**Required Images:**
- [ ] Facebook (for dimensions take a look [here](https://www.facebook.com/PagesSizesDimensions/)):
  - [x] Red Rittles Page:
    - [x] Profile photo
    - [x] Cover photo
  - [x] Towel Defence Page:
    - [x] Profile photo
    - [x] cover photo
  - [ ] FB-App
    - [ ] App Icon (1024x1024)
    - [ ] Small App Icon (16x16, transparent BG)
    - [ ] Cover Image (800x150)
    - [ ] Banner (1200x627)
    - [ ] Hero Banner (1848x682)
    - [ ] Web Banner (155x100)
  - [ ] Share Hiscore #153
- [ ] android
  - [ ] these 8 images:
    ![image](https://cloud.githubusercontent.com/assets/5098472/12595751/5b60c69a-c47d-11e5-9a4e-7d6a20a61efc.png)

**Comment by ghost** [comment]
tons of logos? mean 1 logo of the game title fit for different media?

**Comment by Waog** [comment]
maybe... but they need many different resolutions and maybe also different ratios (most of them are 1:1)

**Comment by ghost** [comment]
sollte eigentlich das Finale Logo sein
![logo](https://cloud.githubusercontent.com/assets/7753856/3422075/c0cb1762-ff15-11e3-9b57-b22951e9375e.jpg)
... wie findest du es?

**Comment by Waog** [comment]
Overall ganz gut, nur zwei kleinigkeiten:
- Die Hintergrundfarbe sieht etwas langweilig aus.
- Es ist nicht quadratisch (das meinte ich oben mit 1:1)

**Comment by ghost** [comment]
Hinterground farbe hab ich nicht als teil des Logo wahrgenommen.

1:1 fur ein App Icon meinste? 
das ist eigentlich am Ende nicht wichtig, da Logos (brands,etc.) immer angepasst sind.
aber wir kriegen wat geil ihn, wenn wir das brauchen sollten :)

**Comment by Waog** [comment]
verstehe nicht was du meinst mit _sind immer angepasst_!?

**Comment by ghost** [comment]
ein Logo (für AUDI zum Beispiel, 4 Kreise) ist als Logo gedacht, aber: 
- Wenn Sie das Digital benutzen wollen, für ein App button Style z.B ( ein "rudes Viereck" ), ist das Logo nicht verändert, aber angepasst. In ein Viereck eingefügt, mit golw drauf, usw.
- andere Beispiel, wenn das Logo auf ein T-Shirt fürs Mitarbeiter beduck werden soll (Siebdruck z.B) würde man das einfarbig drücken (Audi will das so, sagen wir) dan ist das Logo (ursprunglich mit highlights und shadows) einfach Einfarbig in "weiss" bedruckt... ist auch ein art Anpassung

Logos sind immer an Medium (Digital oder Reallife) angepasst... das meine ich damit :)

**Comment by Waog** [comment]
- achso, verstehe, dann gefällt mir das logo oben gut :)
  die form der blitze würde ich dann vielleicht nichtmal als teil des logos sehen und je nach medium anders platzieren (also z.B. blitze von oben und unten, um quadratisch zu sein).
- 1:1 meine ich vor allem für mobile apps, ja. Da braucht man die in ca. 20-30 verschiedenen auflösungen (für verschiedene geräte, stores, menüs, launcher, usw)

**Comment by ghost** [comment]
- blitze: "also z.B. blitze von oben und unten, um quadratisch zu sein" ja das ist eine gute Lösung...
- Auflösung und größe ist kein Dings, geht janz schnell :)

**Comment by Waog** [comment]
gut :+1:

**Comment by ghost** [comment]
war neugierig (ich habe kein smartphone, nur ein ipod touch von 2009 und hab noch nie ein jame gedownload...) und eigentlich die app icons sind am meisten ohne title drauf (hätte das gegenteil gedacht...)
![480x352xicons_games png pagespeed ic bupn05oocf](https://cloud.githubusercontent.com/assets/7753856/3553730/ab1536e6-0906-11e4-8b4e-e0dfa53a5698.png)
![screen shot 2014-07-10 at 16 40 36](https://cloud.githubusercontent.com/assets/7753856/3553736/bee7ab68-0906-11e4-8512-3b4e32700285.png)

ist mehr ein kvisual...
![screen shot 2014-07-10 at 16 41 42 2](https://cloud.githubusercontent.com/assets/7753856/3553764/e767c334-0906-11e4-9b0f-a0968e95c900.png)
![screen shot 2014-07-10 at 16 43 03 2](https://cloud.githubusercontent.com/assets/7753856/3553771/f8bc4254-0906-11e4-923b-239cb965d671.png)

**Comment by Waog** [comment]
stimmt, gute beispiele... habe ich nie drüber nachgedacht. aber man hat das app-icon am ende gitterförmig angeordnet zwischen 20 anderen app-icons. und darin will man die richtige app finden, ohne lange nachzudenken, zu suchen, oder gar lesen zu müssen.

Meine negativ-erfahrungen mit app-icons sind folgende:
- das logo ist so "normal" dass es zwischen den ganzen anderen "normalen" untergeht und man sich doch zeit nehmen muss jedes einzelne anzugucken. (das ist vor allem so bei schrift im logo)
- das logo ist so penetrant, dass es die Aufmerksamkeit ständig auf sich sieht, selbst wenn man die app gerade gar nicht sucht. (vor allem bei signal-farben)
- das logo verkörpert die app so schlecht, dass man es nicht mit der app assoziiert, obwohl man schon drei mal drüber geguckt hat (logo zeigt nicht die kernfunktionalität, bzw. das womit der nutzer die ganze zeit konfrontiert wird)

Meine positiv-erfahrungen sind schwer zu benennen. Denn am positivsten ist es, wenn man als nutzer gar nicht darüber nachdenkt und nur unterbewußt das richtige icon anklickt.

**Comment by ghost** [comment]
Diese Issue ist für mich nicht mehr Relevant, das es sich nicht ums Spiel handelt, sondern Marketing (also wenn das Spiel fertig ist.)

**Comment by Waog** [comment]
Für mich ist der Issue sehr relevant, da ich die Logos brauche, um das Spiel bereitzustellen. Man benötigt Logos zum Erzeugen eines Installers usw.
Zudem ist es für mich 100% Mandatory, dass das spiel am Ende in den Stores liegt. Marketing und Verkaufszahlen sind mir dabei egal, aber für mein Portfolio macht es einen enormen unterschied, ob man mein spiel einfach wie alle Spiele über einen playstore installiert, oder ob man umständlich irgendwie anders ein Game ohne Logos installiert.

**Comment by Waog** [comment]
okay, i start a checklist in the first post of this issue now.

**Comment by ghost** [comment]
cool, ich versuche am Donnerstag anzufangen...

**Comment by ghost** [comment]
http://havecamerawilltravel.com/photographer/images-photos-facebook-sizes-dimensions-types

**Comment by Waog** [comment]
Die FB Profil-Fotos sind zu klein. FB sagt sie müssen mindestens 180px groß sein.
Das Towel Defence Cover sieht auch nicht gut aus, wie es einfach nur gestaucht ist. Dann lieber im Original-Seitenverhältnis lassen...

**Comment by Waog** [comment]
beim RedRittles Cover Photo gafallen mir 2 sachen nicht:
- Über dem Schriftzug sind die horizontalen Steifen zu dominant. Habe erst "Red Rittles Cames" gelesen, weil die Kontur so stark verdeckt ist. Vllt hinter die Schrift legen?
  ![image](https://cloud.githubusercontent.com/assets/5098472/12864944/0f92c118-cc9e-11e5-9ac4-8e5060d3bf9b.png)
- Auf FB steht sowieso wie die Seite heißt, bis man das Cover-Foto angeklickt hat. Es ist doof, dass "Red Rittles Games" jetzt noch ein zweites mal da steht. Vllt das Bild noch nach unten erweitern, so dass man es nur sieht, wenn man das Cover einzeln anzeigen lässt?
  ![image](https://cloud.githubusercontent.com/assets/5098472/12864942/faeb8e0c-cc9d-11e5-8b50-dc8167219681.png)

**Comment by Waog** [comment]
Habe dir grad per Email eine Einladung zur Google Play Store Console geschickt. Dort kannst du Bilder und Screenshots hochladen, die dann hoffentlich im Play Store zu sehen sind.
