### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#23]
- Graphics new (BG, style)

**Comment by Waog** [comment]
- start countdown (3-2-1...)
- Einen Countdown oder ähnliches ganz am Anfang hinzufügen (3, 2, 1 > Start).

**Comment by ghost** [comment]
![tutorial](https://cloud.githubusercontent.com/assets/7753856/3244456/4489eb2a-f168-11e3-808e-606871c24462.jpg)
WIP... 
was hälst du davon?
Tastatur in Motion (Pfeile drück down und gleichzeitig interagiert unser Hero: mal, links, mal rechst, mal attack...) und dazu läuft der Countdown bis 0....

**Comment by Waog** [comment]
Ich verstehe nicht genau was du mir mit dem Text sagen willst.

Also meine Freunde, die es mal gespielt haben, die haben alle nicht kapiert, dass sie space schnell und oft drücken müssen. die haben es immer nur gelegentlich gedrückt, oder gedrückt gehalten.

Daher folgender Vorschlag:
- wir machen das tutorial in Stufen:
  - 1. zuerst kommen die tasten links und rechts. Text ist unter den Tasten und es kommt eine animierte Hand/Finger, die da langsam draufdrückt und gedrückt hällt. Sobald der Spieler einmal nach rechts _oder_ links gelaufen ist, kommt der nächste Schritt
  - 2. dannach kommt nur die Space-Taste und eine animierte Hand/Finger, die wie behämmert da drauf klickt. Nachdem der Spieler (mehrmals?) space gedrückt hat kommt der countdown.
  - 3. der countdown. Dannach die ersten Tropfen/Spiel-Start.

**Comment by Waog** [comment]
Achso, das waren jetzt nur argumente zum Konzept.
Die Grafiken gefallen mir, daran würde ich nix ändern, außer die Hände/Finger.

**Comment by ghost** [comment]
ok cool. 
das heisst, jede Phase des Tutorials ist interaktiv (nächste "Tutorial Schritt" ist duch druck auf die richtige Taste aktiviert... richtig?)

D.h., jedes mal wenn ich spielen will muss ich den tutorial mit machen, ist es nicht redundant?

**Comment by Waog** [comment]
Ja, richtig, so meinte ich es.

Ok, ich korrigiere mich (habe auch oben editiert): im ersten Schritt muss der Spieler rechts **oder** links drücken. Also insgesamt zwei Tasten, um das Spiel zu starten: Links oder Rechts, dann Space.

Und ich glaube die Redundanz ist akzeptabel, da man insgesamt nur zwei Tasten drücken muss und zwar genau die Tasten die man sowieso zum Spielen drücken würde.

**Comment by Waog** [comment]
Achso und die Pause-Taste würde ich dauerhaft in einer Bildschirm-Ecke einblenden, vgl. Pflanzen gegen Zombies 2 (oben rechts):
![plants-vs-zombies-2-china-gameplay-640x384](https://cloud.githubusercontent.com/assets/5098472/3244981/2ee3b264-f16e-11e3-86cf-fb108f4f928e.jpg)

**Comment by Waog** [comment]
Was meinste?

**Comment by ghost** [comment]
finde ich jut.
Sollte die "Pause Taste/Icon" eigentlich auch eine richtige Taste oder? (finde nicht so gut wenn man es per Maus kontrollieren muss)

**Comment by Waog** [comment]
Es kann ja Maus UND "P" möglich sein. Wenn das Spiel auf Touch-Screens spielbar werden soll, dann brauchen wir Buttons zum antippen.

Wenn wir es für Touch kompatibel machen, dann brauchen wir später auch komplett andere Tutorial-Animationen. Aber das würde ich nicht in diesem Issue hier klären.

**Comment by ghost** [comment]
hab das jetzt so gemacht:
![tutorial](https://cloud.githubusercontent.com/assets/7753856/3281029/ab1be55e-f48e-11e3-8751-0c73e6267912.png)

wie du meintest; erstmal anim move left (plus player interaction) > anim move right (plus player interaction)...> kommt dann attack anim ( plus player interaction) > count down to play
- pause #28  wenn man will...

die Buttons and grafics liegen by Brop Box: "png stripes">"tutorial Cycles"

**Comment by Waog** [comment]
Tutorial und Pause sind eingebaut.
