### ISSUE TITLE
Hydranten-Reperatur

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#25]
Deutlichere kommunikation, dass Space den hydranten repariert und wie weit der Hydrant schon repariert ist.

---

TODOs:
- [x] Hydranten-Fontaine und Wasser-Tropfen nicht gleichmäßig verteilen, sondern immer in einzelnen Schüben…. vllt auch kurze Schübe/Unterbrechungen als Feedback, wenn der User gerade den Hydranten repariert.
- [x] Energiebalken
  - [x] Hydrantenreparatur über einen vertikalen Energiebalken rechts im Bild darstellen, der mit jedem Mal “Space”-drücken sinkt (Referenz: z.B. MegaMan) ,deutlich lesbar!
  - [x] animation des balkens bei änderung
- [x] Reperatur-Animationen reparieren.
- [ ] Fontaine: Verstärkerung Visuals (Sprites) für jede Stufe.

**Comment by Waog** [comment]
3 Dinge sind zu diskutieren:
- Was haltet ihr von einem Energie-Balken der erst leer ist und den man aufladen muss? Immerhin reparieren wir und zerstören nicht. Und es wäre mal innovativ :)
- Ist überhaupt ein Sprite nötig, wie bisher? Oder reicht es aus, wenn wir die Fontaine nur als Partikel darstellen? Vergleich Fontaine in der aktuellen Version.
- Wozu haben wir 3 Stufen? Es gibt keinen qulitativen Unterschied zwischen den 3 Stufen... Man könnte es auch Stufenlos machen.

**Comment by Waog** [comment]
Habe die Lifebar für den Hyranten eingebaut, brauche aber noch ordentliche Grafiken...

**Comment by Waog** [comment]
Reperatur animation wurde repariert.

**Comment by ghost** [comment]
wieviel energie punkte hat die Hydrant?

**Comment by Waog** [comment]
derzeit 150... aber wir können am ende auch problemlos noch balancing machen...

**Comment by ghost** [comment]
ok cool, ist bestimmt Möglich nur zu Beispiel:
50 Streifen zu Zeigen und jeder 3 click geht ein Streifen weg....

oder?

**Comment by Waog** [comment]
ja, sowas in der art habe ich auch schon überlegt... im moment ist jeder einzelne Schuss _zu bedeutungslos_ ... aber bevor wir uns über diese Visualisierung gedanken machen, sollte die Spiel-Mechanik genau festgelegt sein (Vergleich Issue #19)... offene Ideen sind ja noch:
- spieler macht mehr schaden, wenn er öfter hintereinander space drückt, ohne sich zu bewegen (so eine art "Kombo")
- Hydrant regeneriert wieder

**Comment by ghost** [comment]
- "spieler macht mehr schaden" finde eine sher gute idee (aber macht es noch sinn da es jetzt eine tropfe automatisch auf ihm fällt nach ein paar Sekunden?)
- "Hydrant regeneriert wieder" #19 das ist auch cool wenn es nicht ganz so schnell sich repariert...

![screen shot 2014-06-24 at 12 28 52](https://cloud.githubusercontent.com/assets/7753856/3370079/71e40a16-fb8a-11e3-944e-e32bfb516154.png)

was häslte davon? 50 punkte (wie oben jesagt...)

**Comment by Waog** [comment]
Für diskussion zum Gameplay Concept siehe #19

**Comment by Waog** [comment]
Wenn der hydrant regeneriert, dann ist glaube ich ein kontinuierlicher balken besser... weil sonst der sprung bei jedem regeneration-schritt zu groß ist. Mit den Lifebar visuals kannst du glaube ich noch warten, bis das balancing feststeht (ob der hydrant 100, 1000 oder 1.000.000 Lebenspunkte hat, ob es kombos gibt usw.)

**Comment by Waog** [comment]
habe hydranten regeneration eingebaut.

**Comment by ghost** [comment]
super, ist cooler so :)

**Comment by Waog** [comment]
alle punkte fertig außer fontain-visuals. diese haben eigenen issue: #76
