### ISSUE TITLE
Sprites of Guy

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#26]
- [x] sprites protagonist (walk, stand, down)
- [x] sprites protagonist (hit)
- [x] Animationen Mensch + Handtuch in einer Animation (nicht mehr durch Spiellogik realisiert)
- [x] ~~Charakter sollte sich agiler bewegen und wann getroffen temporär langsamer.~~
- [x] Skalierung Protagonist (+all)
- [x] Kleinerer Charakter (vllt. halb oder ein drittel so groß)
- [x] Sprite: Handtuch mit Walk circle
- [x] Mensch muss deutlich mehr emotionen zeigen, nicht lässig laufen... vermutlich ist der Krebs-Mensch-Gang ganz gut
- [X] ~~vllt “unverwundarkeits”-grafiken~~
- [X] ~~slide funktion für movement+space um schnell auszuweichen~~
- [x] Er bewegt die Beine auch wann er stehen bleibt.
- [ ] vllt "ausweich"-animationen, wenn ein tropfen knapp an ihm vorbei geht, oder er vor der kratzenden Katze steht.

**Comment by Waog** [comment]
Diskussion nötig:
- was heißt "charakter sollte sich agiler bewegen"?
- wirklich langsamer nach treffer? wozu? ich denke das fühlt sich nicht gut an. bringt es einen Mehrwert?
- unverwundbarkeits grafiken nötig?
- wollt ihr zusätzliche ausweich-animationen und richtungs-wechsel-animationen haben?
- slide: bisher ist das spiel-konzept, dass man sich entscheiden muss zwischen pfeiltasten und space-taste, d.h. die tasten konkurrieren miteinander bzw. schließen sich gegenseitig aus. welchen sinn hätte es, wenn man sie jetzt plötzlich kombinieren kann? Wann bedeutet space schießen und wann sliden? Welchen mehrwert bringt sliden? Macht es das Spiel nicht zu kompliziert?

**Comment by ghost** [comment]
da sind Punkte nach der Version 1.0.

"unverwundbarkeits grafiken nötig?"  vielleicht,... oder auch nicht hahah! bin mir nicht janz sicher.

meine Meinung nach,  kann man die Restliche Punkte Ignorieren...

**Comment by Waog** [comment]
Ich glaube nicht, dass ich das Spiel nach v1.0 noch weiterentwickeln will. Ich will jetzt schon bestmöglich definieren, was die finale Version können soll. Aber du hast recht, dass es einer der späteren Punkte ist.

Ausweich und Richtungs-Wechsel-Animationen fände ich noch geil in der finalen Version. Ich glaube die lassen das Spiel 3-mal professioneller aussehen.

**Comment by ghost** [comment]
ich finde den rythmus von der Atem und Attack ziemlich schnell, kann man das runter holen?

**Comment by ghost** [comment]
"vllt "ausweich"-animationen, wenn ein tropfen knapp an ihm vorbei geht, oder er vor der kratzenden Katze steht."

ist es nicht überflüssig? (ich kaufe ein "ja"...) die Grenze Gulimonster-Trashbags(Katze) animation funktionnieren genug gut so (die sind nur Grenze Marker) fürs gameplay bringt es nich viel mehr und für uns nur "viel mehr" arbeit.

wat sag ste?

**Comment by Waog** [comment]
- atem: das finetuning müssen wir mal machen, wenn wir zusammensitzen. technisch aber kein problem.
- naja, ich finde es nicht ganz überflüssig. wir müssen uns irgend eine lösung einfallen lassen, was passiert, wenn der spieler in die Hand/Müllsäcke reinrennt. einfach die renn-animation weiter abspielen, obwohl der charakter nicht weiter kann, finde ich nicht schön. Einfach stehen bleiben und nach oben gucken, obwohl die hand/säcke unten sind, finde ich auch nicht so schön und der spieler bekäme kein feedback auf seine eingaben. Wie würdest du das umsetzen wollen?

**Comment by ghost** [comment]
haste recht, wäre optimal mit eine kleine animation. aber d.h. 3 x 2 (3 unterschiedliche Zustand mit Towel x 2 Seite links und recht) mehr Animationen.

lass uns dann das machen.
Betrifft es die "Event"?

**Comment by Waog** [comment]
ja, auch das betrifft die events... also mach dir erstmal wenig arbeit und gib mir irgendwelche test-grafiken... vielleicht kann ich sie am ende gar nicht einbauen.

**Comment by ghost** [comment]
-"wenn der spieler in die Hand/Müllsäcke reinrennt."
- "Ausweich und Richtungs-Wechsel-Animationen fände ich noch geil in der finalen Version. Ich glaube die lassen das Spiel 3-mal professioneller aussehen."

wat denkste für diese 2 Punkte? (wegen Event und so..) villeicht kann ich erstmal der erste Punkt anfangen? mahct es Sinn?

**Comment by Waog** [comment]
achso... für mich war das der gleiche punkt... mein ursprünglicher plan sah so aus, dass der character regentropfen ausweicht, aber auch ganz genauso ausweicht, wenn er zu nah an müllsäcke oder gulli kommt. aber wegen mir kannst du beides erstmal lassen... erstmal den rest fertig machen (alle menüs, win und lose screen). dann gucken wir mal wieviele events noch übrig sind.

**Comment by Waog** [comment]
aber wir haben oben noch offene punkte die wir mal diskutieren können:
- Charakter sollte sich agiler bewegen und wann getroffen temporär langsamer.
  - temporär langsamer -> bin dagegen
  - agiler bewegen -> ideen wie wir das umsetzen? ich nicht, deswegen erstmal dagegen.
- vllt “unverwundarkeits”-grafiken
  - das blinken nach einem treffer reicht mir, willst du mehr?
- slide funktion für movement+space um schnell auszuweichen
  - nicht auf touchscreen umsetzbar -> dagegen
- vllt "ausweich"-animationen, wenn ein tropfen knapp an ihm vorbei geht, oder er vor der kratzenden Katze steht.
  - siehe mein vorheriger post. dafür wenn am ende noch events und lust übrig ist, sonst gehts auch ohne.

**Comment by ghost** [comment]
bin einverstanden mit deine Punkte...

**Comment by Waog** [comment]
Du hast den Issue geschlossen. Wie siehts aus mit der Ausweich-Animation?
