### ISSUE TITLE
Pause Screen

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#28]

**Comment by Waog** [comment]
Zu Diskutieren:
Ist bei einem Spiel was ca. 30 Sekunden dauert wirklich eine Pause-Funktion nötig? Da es zusätzliche Arbeit verursacht würde es lieber weglassen. Was spricht für die Pause-Funktionalität?

**Comment by ghost** [comment]
Obwohl du recht hast (für so ein Spiel) finde ich trotzdem gut wenn es eine Pause Tase geben würde. Macht das Spiel mehr Profi (Pause is ein basic für games wie "music on/off" und so wat...) für die Mappe :)

**Comment by Waog** [comment]
Allrighty, bin einverstanden, sobald die Mandatory-Issues fertig sind.

Hier die TODOs:
- [ ] Grafik Pause Menu Fenster/Hintergrund
- [ ] 14 Button-Grafiken
  - [x] Pause, PausePressed
  - [ ] BackToGame, BackToGamePressed, BackToMenu, BackToMenuPressed
  - [ ] MusicOn, MusicOnPressed, MusicOff, MusicOffPressed
  - [ ] SoundOn, SoundOnPressed, SoundOff, SoundOffPressed
- [ ] Wenn fertig: Label `Task:Programming` hinzufügen und `Task:Graphics` entfernen.

**Comment by ghost** [comment]
"Back to Game & Back to Menu" sind fürs das Pause screen gedacht?

ein Music button & ein Sound button... könnte man dan nicht ein art kleiner Menu (der kommt wenn man Pause drückt) wo man einstellen kan mit mehere stuffe und so?

![screen shot 2014-07-11 at 16 31 01](https://cloud.githubusercontent.com/assets/7753856/3553876/15ededa4-0908-11e4-9508-392fdb3bdb50.png)
biespiel aber nur mit sound un music...

**Comment by Waog** [comment]
_"Back to Game & Back to Menu" sind fürs das Pause screen gedacht?_
- ja. "Back to game" kann auch "resume" oder so heißen. aber ein button, um das spiel abzubrechen und einen um es fortzusetzen, fände ich gut.

sehr viele mobile-games haben diese volume-control interessanter-weise nicht. Wir können sie reinbauen, müssen aber nicht. Mir würden auch on/off buttons reichen. Oder einen stufenweisen volume-controler (mit 0%, 25%, 50%, 75%, 100%). Viel präziser bekommt man es auf so einem touchscreen sowieso nicht eingestellt. Und es könnte Construct-Probleme geben die Einstellungen zu speichern. Und niemand will jedes mal wenn er das game startet, erst immer 3 minuten mit konfigurieren verbringen. Während on/off switches ok sind. Diese on/off switches würde ich sogar gerne in jeden bildschirm bauen, nicht nur ins pause-menü. das ist auch in allen mobile games so.

**Comment by ghost** [comment]
ok, d.H. (wenn ich richtig verstanden hab):
im Pause menu haben wir (wie du es oben geschrieben hast) buttons fur:
- "Back to game"
- " resume"
-  Music On/Off 
- Sound On/Off 

und aufs Bildschirm im "Gameplay" #19  haben wir buttons dür: 
- Music On/Off
- Sound On/Off
- Pause (mit alle Buttons wie über geschrieben )

bin richtig?

**Comment by Waog** [comment]
ja, aber:
Ich würde die music und sound on/off buttons auch im MainMenü anbieten. Für gewöhnlich sind das so kleine quadratische buttons in der oberen ecke (links oder rechts variiert).

**Comment by ghost** [comment]
okay, wie ein switch also...

**Comment by Waog** [comment]
so wie hier: 
![image](https://cloud.githubusercontent.com/assets/5098472/3582440/5036febe-0bfc-11e4-969c-b115b0fee4fc.png)

aber ich finde diese symbolik für _off_ immer schön, weil man die deutlich erkennt:
![image](https://cloud.githubusercontent.com/assets/5098472/3582448/79180418-0bfc-11e4-8373-3c9be87f6b92.png)

**Comment by Waog** [comment]
continued in #64
