### ISSUE TITLE
Find Publisher

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#3]
Find websites we can sell licences to, so they can publish it.

| Publisher | First Email/Submit | Answer | Dev-Link |
| --- | :-: | :-: | --- |
| spilgames.com | :white_check_mark: |  |  |
| coolgames.com | :white_check_mark: |  |  |
| Miniplay.com | :large_blue_circle: can't register login to dev area. contacted them for support |  | http://www.minijuegos.com/dev |
| softgames.de | :white_check_mark: |  | http://www.softgames.de/developers/ |
| Famobi GmbH | :white_check_mark: |  | http://de.html5games.com/Statisch/Entwickler |

**Comment by ghost** [comment]
finde das ziemlich interessant...
- https://www.scirra.com/tutorials/345/how-to-sell-your-game-to-large-publishers
- http://www.marketjs.com/
- http://de.slideshare.net/flashgamm/softgames-dev-gammkiev

**Comment by Waog** [comment]
ja, gucke ich mir bei Gelegenheit mal an.

Falls wir am ende Ladezeiten haben, könnten wir statt einem Ladebildschirm übrigens auch Werbung einblenden (ich hoffe Construct gibt das her). Was meinst du? Lieber hässliche Werbung und Geld oder lieber schönen Ladebildschirm und kein Werbe-Geld? Aus Portfolio-gründen wäre für mich sogar die Werbung interessanter, weil sie technisch anspruchsvoller ist. Vielleicht brauchen wir aber auch bei Werbung trotzdem einen eigenen ladebildschirm, keine Ahnung bisher.

**Comment by Waog** [comment]
ok, hab die links jetzt gelesen, die sind gut.

uns fehlen noch 2 punkte für ein "qualitäts"-spiel:
- Einfach zu lokalisieren -> wird wahrscheinlich nix.
- integration in soziale medien -> weiß noch nicht, ob es ohne highscores (vgl. #51) sinn macht.

Ich habe vor ein paar tagen auch mal alexander krug (der CEO von deinem dritten link) in linkedin angeschrieben. Der deren Publishing-Studio ist hier nur ein paar Meter von mir entfernt. Da können wir auch mal vorbei gehen und uns kostenloses professionelles feedback abholen.

**Comment by ghost** [comment]
cool, sehr gut! :+1:

**Comment by Waog** [comment]
a medium effort is a bad estimate, if we want to do it properly. It's not about finding a single publisher, willing to host our game, but about checking out the full financial potential of this game...

**Comment by Waog** [comment]
habe unser game mal auf market JS angelegt, aber noch nicht veröffentlicht.
