### ISSUE TITLE
Test if bitmap fonts work

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#30]

**Comment by Waog** [comment]
Create Bitmap fonts with http://kvazars.com/littera/

**Comment by Waog** [comment]
Bitmapfont Integration of Construct2 sucks...but the default bitmap font (see below), could be ok.... else we have to use normal system fonts:
![image](https://cloud.githubusercontent.com/assets/5098472/3276237/676d85cc-f346-11e3-9289-770da61828b8.png)

**Comment by ghost** [comment]
and if we use graphics (png) for all buttons & texts is not better? we can pimp them as we want and are not restricted from a standard font.
?

**Comment by Waog** [comment]
we can do so, but the maintenance of those texts sucks. If we find a typo or something, the complete workflow has to be repeated.

**Comment by ghost** [comment]
![screen shot 2014-06-18 at 00 28 19](https://cloud.githubusercontent.com/assets/7753856/3307606/e5747f04-f66e-11e3-8874-b8d6a5b635fe.png)
you are right, maintenance could be a problem. I think more for the future, if we want to developp the game for moblie or so. but on the other side, a generated font in HTML5 is really not flexible for the Design of the game.. (dependig what we have on the BG, etc.)

what do you think about this font?

**Comment by Waog** [comment]
i believe you underestimate bitmap fonts. One can create very cool and matching stuff with it (check out http://kvazars.com/littera/ to get an impression). But the fonts from the link are not compatible with construct2.

I think your font is good and fits into the rest of the artwork. Do you have the rights/licenses to use it commercially?

**Comment by ghost** [comment]
probably... :)

licence? sure... i worked for Advertising, this is a basic to check ;)

**Comment by Waog** [comment]
There is a Construct Plugin which makes Bitmap Fonts look much better: https://spritefontplus.codeplex.com/

Unfortunately it is under the GPLv3 license. With a little bit of luck they'll republish it under the MIT license: https://spritefontplus.codeplex.com/workitem/1

**Comment by ghost** [comment]
oh yep!

**Comment by Waog** [comment]
Ich habe jetzt die Standard bitmap fonts eingebaut und finde es sieht auch ohne Plugin ganz gut aus.

![image](https://cloud.githubusercontent.com/assets/5098472/4683404/52751cf0-5626-11e4-9ee8-ca354264ae46.png)

![image](https://cloud.githubusercontent.com/assets/5098472/4683421/6f70e00a-5626-11e4-860b-62336d052c69.png)

Was meinste? Reicht das so?

**Comment by ghost** [comment]
yep, ist eigentlich nicht so schlecht...
nur beim minuskeln "L" und Kapital "i" haben wir immer dieses Abstand... (wie: Gl  ut)... ist nicht so gelio finde ich.

**Comment by Waog** [comment]
Das könntest du in der Bitmap Font wegkorrigieren... zentriere das `l` und `i` etwas mehr und gib ihnen 2-3 Pixel breite Serifen. Reicht vllt schon.

**Comment by Waog** [comment]
Aber eine mono space font passt gut mit den strichen die wir in den leeren zeilen haben.

**Comment by ghost** [comment]
yep! ist janz gut! :)

**Comment by Waog** [comment]
dann würde ich den task erstmal zu machen und es bei den non-plugin bitmap font belassen, ok?

**Comment by ghost** [comment]
ok!
