### ISSUE TITLE
Sounds Gameplay

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#31]
- Sound (city, man voice?, attak sound, etc.)
- Sound change nach jeder schwiedigkeit step
  (schneller oder so)
- Sounds... ich fänds cool, wenn der Mann spricht und schreit.
- Rythm/Änderung Sounds:   Sounds die Rythm geben (z.B. schnelle/langsame Tropfen) 
  oder  Änderungen am Spiel signalisieren
  (z.B. 1. Charakter hat nur noch eine chance zu überleben, 2.das          Wasser wird schneller und schneller gespritzt und die Tropfen fallen schneller).

**Comment by ghost** [comment]
ask Sa.Syn for great beats and loops?
(https://soundcloud.com/saint-savant)

**Comment by Waog** [comment]
ein bestimmtes? finde die songs zu langsam fürs gameplay... aber vllt fürs menü.

**Comment by ghost** [comment]
should sound be 8/16 bit or more realistic?
(risk gap between gameplay and sound)

realistic:
https://www.freesound.org/people/lazymonk/sounds/214319/

8/16 bit:
http://www.youtube.com/watch?v=0iPurc4T-bU

**Comment by ghost** [comment]
Er kann für uns wat extra für das Spiel basteln...
jep, wäre gut fürs Menü und warum nicht Win and Lose sound...

**Comment by Waog** [comment]
Habe nochmal weiter reingehört. Ich finde nicht, dass der Stil von Sa.Syn zu unserem Game passt. Weder in die Menüs, noch ins Gameplay. Ich weiß nicht, ob ich zufrieden wäre, mit dem was er so bastelt...

Ich finde die bit-variante besser als die realistische.

Ich benutze bisher
- für musik: http://tones.wolfram.com/generate/
- für sounds: http://www.bfxr.net/

**Comment by ghost** [comment]
coole Spielzeuge :)

Er kann sich trotzdem gut anpassen, aber vielleicht haste recht...
sowieso muss man erstmal "mood board" fürs Sound sammeln (von andere Games die wir gut finden, oder werbung, filme...) um raus zu finden wat wir eigentlich wollen...

**Comment by ghost** [comment]
kennste "8 bit cinema"? könnte in der richtung gehen... (gibt mehrere Beispiele)

http://www.youtube.com/watch?v=k7X17t1PSZU&index=23&list=PLXwCEu8zfclXjnBTfYOZlQ269kjCgwl4J

oder villeicht auch nicht... :)

**Comment by Waog** [comment]
Gefällt mir erstmal gut beim ersten reinhören. :+1:

**Comment by ghost** [comment]
hab wat jefunden bei "Garageband" (sound editor von apple...) kann man music in 8 bit umwandeln, ist eigentlich ganz cool... nuss ein paar teste machen.

**Comment by Waog** [comment]
see #91
