### ISSUE TITLE
Begrenzungs Grafiken

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#34]
- BG: Begrenzungen (Müllsäcke, Gulli)
- Begrenzungen (Müllsäcke, Gulli) noch deutlicher kommunizieren
- Vllt Effekte, wenn spieler an die Grenzen tritt? MutantenHand die auf dem Gulli versucht ihm sein Handtuch runterzuziehen, oder eine kratzende Katze auf den Müllsäcken?

**Comment by ghost** [comment]
wenn mann an der Grenze (Links und rechts) stoss, unser Hero vibriert.

**Comment by ghost** [comment]
Gully:
wo ist die Zombie Hand :) 
Trashbags:
Schatten hat defekt wenn Hero dran stoß.

**Comment by Waog** [comment]
- fixed gully and trashbags.
- zittern bei kollision mit grenze: problem wird gefixt, wenn klar ist, ob es extra animationen gibt, um der hand und den müllsäcken auszuweichen.

**Comment by ghost** [comment]
gully: hatte so gedacht das random sieht man nur die rote Augen blinken (wenn "You" ist unterwegs) ab und zu... und nur wenn "You" stoß, kommt nur das Hand raus.

zittern: was meinst te mit: "ob es extra animationen gibt,um der hand und den müllsäcken auszuweichen"

**Comment by Waog** [comment]
- die roten augen habe ich nichtmal wahrgenommen... ich baue sie mal ein.
- extra animationen: siehe Issue #26

**Comment by ghost** [comment]
verstehe ich jetzt... :)

**Comment by Waog** [comment]
rote augen sind jetzt drin.
