### ISSUE TITLE
Decorations

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#35]
- BG: Cars-airplane-what else... animation

**Comment by ghost** [comment]
![bg_placeholder_pixel](https://cloud.githubusercontent.com/assets/7753856/3244173/d0006354-f164-11e3-8ee9-1acfd5804ae5.jpg)

WIP

**Comment by Waog** [comment]
Overall very nice :+1: 

My two cents:
- **character:** proportions between main character and the rest of the scene doesn't convince me. Either Character is to big, or rest to small. Oooor, he needs to stand closer to the camera/viewer than the rest.
- **car:** looks nice, we need a horn-sound for it. May we have two or three different cars (maybe only different color)?
- **flash+youth:** can you arrange them more three-dimensional? I.e. a few could stand closer to the camera than the others.
- **monster or steam:** Steam is easy, monster is cool. I'd prefer the monster... Maybe some Zombie-/Mutant-Hand which comes out of the gully and tries to grap the character, if he walks too close.
- **people in the background:** good idea. Some could also look out of the windows.
- **trashback + flys:** what about a cat on the bags, which starts scratching if the character walks too close?
- **airplaine:** as always... png, not gif! Looks nice. Maybe additional clouds?

**Comment by Waog** [comment]
Siehe auch Issue #34 für die Begrenzungen (wenn sie auf den Spieler reagieren müssen, sind es aus technischer Sicht nicht einfach nur Decorations).

**Comment by ghost** [comment]
character:
hab die Perspektive bisschen verändert (Strasse BG dünner jemacht.) Finde jut so, stimmt das Proportionen haben wat, pixel lasst sich schwer arbeiten :)

cars:
yep, mehere und abwechslung ist juti, vielleicht auch ein Krankenwagen oder so...

flash+youth:
have to make some more in the front...

monster or steam:
als long as the player don't hit the border, we see some red eyes blinking and if he touch the gully the hands try to chatch him.

Peps in BG:
yes that's cool

Trashbags & flies: cat is hot to animated with so low pixels, maybe flies + a green (stinky) skull steam... 

airplane: clouds to do...

**Comment by ghost** [comment]
![bg_placeholder_pixel](https://cloud.githubusercontent.com/assets/7753856/3269305/dced0766-f2ea-11e3-8ea3-4cb9b6328166.gif)
WIP

**Comment by Waog** [comment]
nice work so far :+1: 

_animation speed:_
some animations as you planed them for the character (attack) where to slow, to keep up with the fast gameplay. I had to increase the attack-animation-speed by factor 5 or 10. I didn't tell you yet.

I guess, the same will apply to your gully-hand. Your have to consider how fast the caracter walks/runs on the screen. If he would just continue running, he would pass the gully, before the hand even came out of it.

_umbrella:_
can you also add one or more umbrellas above the photographing people + gully? i want to make the rain also drop and splash there.

**Comment by ghost** [comment]
![bg_people](https://cloud.githubusercontent.com/assets/7753856/3307553/403f546e-f66e-11e3-853b-3ae4ccdd97d6.gif)
more live in the game...

**Comment by Waog** [comment]
:+1:

**Comment by Waog** [comment]
the airplane in dropbox is a tif-file, no png.

**Comment by ghost** [comment]
i changed it.

**Comment by Waog** [comment]
im moment fliegt das flugzeug immer vor den gebäuden entlang, das sieht doof aus. Ich bräuchte die Gebäude und den Himmel als zwei getrennte grafiken.

**Comment by Waog** [comment]
das gleiche problem gilt fürs auto... ich brauche die leute links unterm regenschirm seperat vom hintergrund, sonst fährt das auto immer vor den leuten entlang.

**Comment by ghost** [comment]
Liegt jetzt in Dropbox...

**Comment by ghost** [comment]
hab noch zwei "flash" sprites gebaut... ein fürs BG (kleine Leute) und ein fürs FG (Kinder & Leute Links)

![screen shot 2014-06-28 at 00 14 43](https://cloud.githubusercontent.com/assets/7753856/3418497/7befb6d4-fe48-11e3-98be-865ec9ff2229.png)

wäre eigentlich ganz cool wenn jedes mal "YOU" erwischt ist (gleichzeitig mit "HIT") dass die leute ihm Fotografieren...

**Comment by Waog** [comment]
ah, habe mir bisher vorgestellt, dass die die ganze zeit fotografieren... also unregelmäßig immer wieder ein blitzlicht... ich baue es erstmal so ein, wie ichs mir vorgestellt habe, dann sagst du mal ne meinung :)

**Comment by Waog** [comment]
die sind noch nicht in dropbox...

kannst du die zusätzlich auch noch alle als einzelne sprites speichern? also ungruppiert, mit genau einem blitzlicht je sprite sheet? Sonst sieht es doof aus, wenn ich sie immer mal wieder fotografieren lasse. Dann würden sonst immer alle gleichzeitig fotografieren.

**Comment by ghost** [comment]
liegt zwei unterschiedliche Sprites im Bropbox..
(flash_BG.png fürs kleine Menschen im Background und flash_FG.png fürs Leute links im Frontground)

fande eigentlich lustiger das es ein art reaction aufs "HIT" ist...
da ich ein flash hin und her ein bisschen langweilig fande... Hatte im Kopf wie im Stadion oder so, wenn wat besonders passiert, haste eine Menge Flash die den Moment aufnemen...

![flash_test](https://cloud.githubusercontent.com/assets/7753856/3420426/ea7ed26e-fea8-11e3-9b6a-ad0dad0b876e.gif)
(sollte eigentlich ein loop sein...)

ich hab auch 2 unterschiedliche flashs gelegt (flash1.png, flash2.png), dan kann man wie du meinst  ab und zu einfügen.

**Comment by Waog** [comment]
jap, wäre vielleicht zu langweilig. Man kann es ja kombinieren... gelegentlich zufällige einzelne flashs... und bei nem treffer n flashstorm :)

**Comment by Waog** [comment]
du müsstest mir bei den flashs mal sagen, wieviele reihen und spalten die haben.
Und kannst du die einzelnen blitze auch als sprite strip machen?

**Comment by Waog** [comment]
Kannst du die menschen im Vordergrund auch noch animieren? Die Menschen im Hintergrund sehen schön lebendig aus, die im Vordergrund stehen nur da wie statuen.

**Comment by ghost** [comment]
beim "flash_BG" und "flash FG" gibt ein "Anker Punkt" (schwarze pixel) um das richtig ein zurichten... haste villeicht schon gemerkt.
-"flash_BG" geht der Pixel aufs Fuß von dem Typ ganz rechts...

Menschen im FG, haste recht, muss ich eine animation machen... wäre viel besser. Dann muss ich die Flashs noch anpassen (nochmal machen)

**Comment by Waog** [comment]
habe die getrennten grafiken (sky, buildings, foreground) eingrbaut.
Auch flashes habe ich _irgendwie_ eingebaut... die sitzen noch nicht genau an den richtigen positionen, aber das lässt sich später leicht fixen.

**Comment by ghost** [comment]
![people-copy](https://cloud.githubusercontent.com/assets/7753856/3448632/8bee5480-015b-11e4-9e12-2d5325256de3.gif)
mehr Leute? (ist ein bisschen Leehr ganz links, für grössere Bildschirm auflösung...)
![screen shot 2014-07-01 at 22 10 17](https://cloud.githubusercontent.com/assets/7753856/3448645/c1a10078-015b-11e4-894d-30f8cca1ff5f.png)

**Comment by Waog** [comment]
sieht schon viel lebendiger aus :)

Zum Versändnis: die Ecke ganz links sieht man nicht weil die Bildschirm-Auflösung größer ist, sondern nur wenn die ratio bereiter wird (also auf 16:9 mehr als auf 4:3).

Hast recht, sieht irgendwie leer aus. Musst aber nicht unbedingt mehr Leute machen, kannst auch ein Haus, Imbissbude, Baustelle oder sonstwas dahin stellen, Musst aber bedenken, dass man vielleicht nur die Hälfte davon sehen wird.

**Comment by ghost** [comment]
Liegt im Drop Box... (datum: 140707)

**Comment by ghost** [comment]
hatte noch ein UPS wagen gebastelt...
light och im Drop Box.

![ups](https://cloud.githubusercontent.com/assets/7753856/3493794/fa38e7c0-05bb-11e4-8ee5-0bd3025ae0bd.png)

**Comment by Waog** [comment]
- hmm... den öfter als 2 mal durchs bild fahren zu lassen sähe doof aus, weil der zu auffällig/besonders ist. halt kein "normales" auto. Aber ich baue ihn erstmal ein.
- du musst mir mal zeigen wo du dir vorgestellt hast wo die autos langfahren sollen. Die straße ist nur irgendwie 3 pixel breit. wir schwierig da autos in 2 richtungen drauf fahren zu lassen.

**Comment by ghost** [comment]
- ok. Ich könnte sonst noch 2 oder 3 andere Autos (unterschiedlische farbe oder so) machen... würde auch ein bisschen abwechslung bringen.
- ja, eigentlich sind nur 2 pixels (yellow und gelb)
  ![screen shot 2014-07-07 at 16 38 47](https://cloud.githubusercontent.com/assets/7753856/3496661/d42735e0-05e4-11e4-913e-24a49d2d3dd4.png)

**Comment by Waog** [comment]
ah ok... dann weiß ich schonmal wie die autos fahren sollen.

2-3 weitere autos wären cool. möglichst _normale/unauffällige_ am besten.

**Comment by ghost** [comment]
jep...

wollte eigentlich wissen, der Flugzeug im BG, finde eingentlich nicht so geil das er schrek fliegt (linie in piexel sehen nicht so cool aus) kann man den Horizontal fliegen lassen?

**Comment by Waog** [comment]
Kann ich auch horizontal fliegen lassen, aber ich fand es sah nicht so geil aus. Zu _statisch/mechanisch_, dass das flugzeug "zufällig" genau horizontal auf kamera-ebene fliegt.

Aber das lässt sich ganz schnell ändern. Wir müssen uns eh nochmal irgendwann treffen, für Partikel. Da können wir dann sowas gleich mit machen... also alles was ich an grafik-effekten selbst programmieren muss, würde ich dann nochmal mit dir abstimmen wollen. Ich mache mal nen neuen Issue auf, wo wir sammeln können was dann besprochen werden muss, damit wir nix vergessen.

**Comment by Waog** [comment]
neuer issue #56

**Comment by ghost** [comment]
hab noch die drei im Drop Box...

![car_blue](https://cloud.githubusercontent.com/assets/7753856/3523065/486b7d74-0754-11e4-8015-cceeb520acd2.png)
![car_brown](https://cloud.githubusercontent.com/assets/7753856/3523072/553c297c-0754-11e4-9daf-7aebd3a40a39.png)
![car_gray](https://cloud.githubusercontent.com/assets/7753856/3523074/59471eaa-0754-11e4-95a4-8c16c246a399.png)

**Comment by Waog** [comment]
super :+1: 
wird auch eingebaut...

**Comment by Waog** [comment]
ok, hab die autos und die animierten menschen eingebaut.
ich brauche noch die grafiken von den dingern neben dem hydrant. die hattest du bisher mit in der grafik der unanimierten-menschen. jetzt wo die menschen animiert sind, wären die als alleinstehende grafik besser.

**Comment by ghost** [comment]
"dingern neben dem hydrant" meinste: News Paper box, pole one way und pole cross walk?

**Comment by Waog** [comment]
spiel einfach ne runde und gucke was fehlt :) habe alle grafiken eingebaut die ich habe.
