### ISSUE TITLE
Scalable Lightning

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#36]
- wenn charakter vorne am hydranten steht, dann geht der blitz durch hydranten durch.

**Comment by ghost** [comment]
jetzt ist ok.

**Comment by Waog** [comment]
Eigentlich wollte ich das problem teils mit programmieren lösen... dass ich den blitz immer so platziere, dass er vom character bis zum hydranten reicht. Aber das könnte jetzt n problem werden aufgrund der event-grenze.
