### ISSUE TITLE
Tropfenspawn über Spieler

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#39]
- Jeder X-te Tropfen sollte genau über dem Spieler spawnen, damit langes stehenbleiben nicht möglich ist.

**Comment by Waog** [comment]
Meinungen?

**Comment by ghost** [comment]
d.h. wenn es keine bewegung gibt, nach 5 sec. z.B geht automatisch ein Tropfen uf ihm?

**Comment by Waog** [comment]
ich meinte es so ähnlich, aber so ginge es auch.

Entweder alle paar sekunden, oder alle paar tropfen:
- wenn mans mit sekunden macht, dann bleibt es gleich schwer, man kann potentiell (je nach Glück) immer bis zu 10 Sekunden stehen bleiben
- wenn man es z.B. alle 10 Tropfen macht, dann hat man im early-game länger Zeit zum stehenbleiben als im late-game.

Ich finde die zweite variante etwas besser.

**Comment by Waog** [comment]
Jeder 20ste Tropfen spawnt jetzt über dem Spieler.
