### ISSUE TITLE
Graphics WinScreen

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#43]
TODOs:
- [ ] filled WinScreen-Graphic, with "Win!" as Text and space for a Button.
- [x] optional: character animations (happy? arranging his towel?)
- [ ] "main menu" button
- [ ] "one more time" button
- [ ] after graphics are finished: add `Task: Programming` label.

**Comment by ghost** [comment]
![win_right_test](https://cloud.githubusercontent.com/assets/7753856/3468205/07905c92-029b-11e4-8619-7b9fac723424.gif)
![win_test_left](https://cloud.githubusercontent.com/assets/7753856/3468206/0d4f08b8-029b-11e4-98a6-ef3195e976eb.gif)
hab das erstmal als test so gemacht.
Am angang sollte noch ein art electrische explosion (oder so) sein und am ende noch wat kurzes... (miroslav klose style :)

 finde eigentlich auch nicht schlimm wenn es die Grenze überschneidet... 

how do you see it?

**Comment by Waog** [comment]
- ich gucke kein fußball... keine ahnung was _miroslav klose style_ ist
- den siegertanz finde ich sehr cool, auch wie er grinst :)
- der schock am anfang sieht eher aus als ob er schaden nimmt...
- theoretisch kann das handtuch unterschiedlich hoch hängen, wenn der spieler gewonnen hat... das müssen wir irgendwie beim siegertanz einarbeiten... entweder "regeneriert" der handtuchzustand bei deinem blitzeffekt am anfang, oder wir brauchen 3 verschiedene siegertänze.
- **grenze**: finds nicht so schön, wie er über den gulli schwebt.
  - was hällst du davon: beim win und lose macht der chracter 1-2 schritte auf den spieler zu (3D nach vorne, so dass er größer wird). Dann würde er nicht mehr mit den Grenzen kollidieren, wir haben noch nen geilen effekt drin und es ist nochmal extra absurd, weil er die ganze zeit hätte drum rum laufen können... vielleicht lassen wir ihn von dort sogar einfach zum hydranten laufen und den hydranten tätscheln oder so. Das hieße allerdings, vermutlich, dass du win und lose grafiken nochmal neu machen müsstest!? Was meinste?

**Comment by ghost** [comment]
– Fußball? wer hat von Fußball gesprochen? ich meinte "Miiroslav Klose" der Russische Quantenphysiker... (joke, egal...)
– "der shock" war ein art "Dragon Ball Z" super power der nicht fertig ist... ich vollte eigentlich vermeinden, dass ich drei variante machen muss (deshalb ein art "grzzzzz shok " Blitz) sonst ist immer ziemlich viel arbeit.
Aber, ich könnte eigentlich nur den start sequenz (1 sekunde oder so) in drei variante machen ("Tuch wir hoch gezogen" wie du das ganz ober geschrieben hast) und dann geht die "win sequenz" weiter  mit der Tanz (gleich für die drei) Es könnte eigentlich gut so sein...
– Grenze: jep haste recht... und wenn wir ein neues "sprite" einfügen, wo die Hand den Gully deckel zu macht, könnte eigentlich lustig sein und Löst das Problem.

Dein Vorschlag
: finde eigentlich ganz gut, aber:
-"1-2 schritte auf den spieler zu" nicht so gut bei der machbarkheit, mit sprites und gif bin ich beschränkt mit Animationen. Könnte in Flash wat Anfangen, aber  es würde leider ewig dauern zu Produziren (um ein geiles Ergebins ihn zu bekommen)
-"einfach zum hydranten laufen " wie kombiniert man  "distanz" (wenn er gewinnt ganz links oder ganz rechts ist ein unterschied richtig?) und aktion zum Hydranten? ist es technik einfach? nicht zu viel events?

Meine Meinung: 
Gully deckel macht sich zu, dann (drei) Anim win (tuch wird wieder hoch gezogen...) plus tanz zu ende...

und du wat willste?

**Comment by ghost** [comment]
hab da jetzt so gemacht...
![goully_cover](https://cloud.githubusercontent.com/assets/7753856/3493425/16cb40ee-05b8-11e4-9f7a-f993c3fced55.gif)
![final_win_3](https://cloud.githubusercontent.com/assets/7753856/3493428/1ae5cd98-05b8-11e4-9ef9-c9467adc5ac4.gif)

**Comment by Waog** [comment]
jut, gefällt mir :)
- das handtuch-hochziehen stellst du dann in 3 versionen bereit?
- das die body-builder-pose am ende erkennt man nicht so gut, die würde ich vielleicht weglassen. da stimmen genau die konturen nicht, die du mir mal erklärt hast (bild in schwarz/weiß). Vermutlich wird es vor einem bunten/animierten hintergrund noch schwerer zu erkennen.

**Comment by Waog** [comment]
- habe übrigens echt nochmal gegooglet wegen miroslav klose, das hat mich gewurmt, dass ich nen quanten-physiker nicht kenne, aber nen fußballer... dannach habe ich dne scherz verstanden :)
- und ich finde wir können die jetzt so nehmen. das mit dem in den vordergrund laufen und hydranten streicheln und so, macht viel arbeit für uns beide und könnte auch probleme mit der event-anzahl geben. lassen wirs einfach, ist nicht so wichtig.

**Comment by ghost** [comment]
-  3 versionen bereit?
  jep, es gibt jet 3 ending. (jedes mal die erste sekunden sind unterschiedlich wegen die drei Zustand, und dann alle gleich ending)
- Haste recht fürs "Bodybuilder denker"... am besten nur am ende  winkt er hände hoch oder so...

**Comment by Waog** [comment]
stell mir mal die 3 versionen in 2 teilen bereit bitte... also 3 kleine dateien + eine große für den rest der animation. Dann kann ich evtl. Ladezeiten besser optimieren.

**Comment by ghost** [comment]
ok, juti...

**Comment by ghost** [comment]
hab das so gemacht...
ist im drop box

![win](https://cloud.githubusercontent.com/assets/7753856/3517597/6d427d4a-06f1-11e4-8bf0-1242cbec0d57.gif)

**Comment by ghost** [comment]
Ladezeiten besser optimieren... #49 sind die Bilder eigentlich nochmal via Constructor 2 comprimiren?
bis jetzt habe ich eigentlich die bilder in ein art "high resolution" PNG gespeichert...
hab immer noch die Möglichkheit die niedrieger zu speicern wenn es hilf...

**Comment by Waog** [comment]
sehr gut baue ich so ein.

musste selbst erstmal gucken ob da was optimiert wird. Es wird ganz extrem optimiert. Z.B. hat dein bg-sky 6.502 KB, die optimierte version hat 38 KB.

**Comment by Waog** [comment]
hab die win-animation eingebaut.

**Comment by Waog** [comment]
habe auch die gulli-schließen-animation eingebaut. sowohl wenn der spieler gewinnt, als auch wenn er verliert.

**Comment by ghost** [comment]
:+1: coolio

**Comment by ghost** [comment]
wie #45... mit andre Headlines...

![outro_win](https://cloud.githubusercontent.com/assets/7753856/3771808/b4a7c564-18f8-11e4-89da-e96e38cf77ba.jpg)

**Comment by Waog** [comment]
Ich fänds schon besser, wenn der Spieler irgendwie "belohnt" oder "gelobt" wird, wenn er gewinnt.
Also entweder n geiles Art-Work / Film-Sequenz am Ende. Oder wenn du keine Lust auf zu viel Arbeit hast, dann ein Zeitungsartikel in dem der Held gefeiert wird:
"Man saves city from drowning" oder so....

**Comment by Waog** [comment]
Ich glaub, wenn man nicht unsere ganzen Hintergrund Diskussionen mitbekommen hat, versteht man sonst nicht, dass man gerade gewonnen hat, sondern fragt sich nur, was dieser Zeitungsartikel überhaupt bedeuten soll.

**Comment by ghost** [comment]
jep, mein Gedank war das wir "0815" News geben, da es eine komplette "blöde" situation ist, es gibt irgendwie nichts zu gewinnen oder stolz darüber zu sein... deshalb ein visual style: " alles geht weiter, wie jeden tag" (wie ob es nie was passiert würde...)

aber villeicht haste recht, man versteht es nicht ganz...
lass uns noch ein bisschen nachdenken :)

**Comment by ghost** [comment]
also... ich würde das so machen:

wie du gesagt hast: "Zeitungsartikel in dem der Held gefeiert wird:
"Man saves city from drowning""... (dynamik wie beim lose), screen bleibt paar sekunden so... und dann kommt eine kleine Animation mit so was:
![screen shot 2014-08-05 at 11 39 00](https://cloud.githubusercontent.com/assets/7753856/3809618/41c2ef7e-1c86-11e4-9cb4-e2826922da57.png)
(grob gemacht) und man sieht villeicht jemand joggen, ein Schiff oder Vögel oder so...

wat meinste?

**Comment by Waog** [comment]
Sehr coole idee. :+1: 
Hier würde ich wieder (wie im main menü), kein pixel art verwenden, außer die statue so lassen. Was meinste?

**Comment by ghost** [comment]
Würde Sinn machen wie du es meinst (wie im main menü).
auf eine andere Seite, fande ich cool wenn es auch denn jogger annimiert ist, Vögel bewegen sich och etc. und das kann mann nur (schnell und einfach) im Pixel machen... 

muss nachdenken wegen machbarkheit und so wat...

**Comment by Waog** [comment]
Kannst dir ja mal [Spriter](http://www.brashmonkey.com/spriter_features.htm) angucken, wenn du magst...

**Comment by ghost** [comment]
kenn ich... (hab sogar vor ein Paar Wochen probiert :)  ein supper tool for rigging! aber wenn wir ein dynamische perspective haben wollen, ist so was nicht so optimal... 

 (eigentlich hätten wir alle sprites damit machen können, hahah)

**Comment by Waog** [comment]
Naja, nächstes mal :)
Wenn du Interesse hast, können wir gerne noch ein weiteres Spiel zusammen machen, nachdem TowelDefence fertig ist.

Die Perspektive auf die Jogger darf sich nicht ändern, sonst hättest du richtig viel arbeit!
Ich könnte die Animationen programmatisch fließend skalieren... um die Entfernung von der Kamera zu simulieren, wenn er hilft.

**Comment by Waog** [comment]
Wie wärs, wenn wir diesen Screen gleichzeitig für die High-Scores benutzen? Dann wäre eine Tabelle im Vordergrund...

**Comment by ghost** [comment]
"Spiel zusammen machen" bin dabei... :)

eigentlich hätte ich gerne das wir auch auf eine Zeitschrift enden (wie beim Lose) mit beide Buttons links und rechts. Das gibt unser Spiel eine UI Logik. (villeicht kann man die High Score in der Zeitschirft einfügen?)

da hätte ich zwei Variante wie man dadrauf kommt (einmal pixel oder einmal mit illustration), aber muss den "mini-stoyboard" erstmal zeichnen...
und zeige dir das gleich.

**Comment by Waog** [comment]
Die High-Scores in der Zeitung gehen vermutlich aus zwei Gründen nicht:
- technisch: ich glaube nicht, dass ich das mit Construct2 hinbekomme
- optisch: guck dir mal an, wie die Zeitung in klein (mobile größe) aussieht. Man kann gerade so die Überschrift lesen.
- (UI Logik: da du sie gerade ansprichst. Wenn beim Lose gibt es nichts äquivaltentes in der Zeitung)

**Comment by Waog** [comment]
Also es macht vom Storytelling her keinen Sinn, wenn wir die Win-Zeitung erst nach dem Park+Statue zeigen. Das wäre nicht mehr in chronologischer Reihenfolge.

Ich verstehe zwar dein Argument mit der UI-Logik, aber weiß keine bessere Lösung. Da unsere Grafiken für Win und Lose zur Zeit asymmetrisch sind.

**Comment by ghost** [comment]
High score Zeitung: yep haste recht, bin zu Browser fokusiert... :s

ich dachte mir, es ist eine Möglichtkheit (ending mit Zeitchrift) ein art "to be continued" zu inzienieren.

Erklärung:
1. win screen ... >
2. spin news paper (wie beim lose) ... > 
3. Newspaper Headline, wat wie "Hero is born!!!" ... > 
4. Landscape visual: ein Text pop up "3 month later..." (pixel art style, es lässt uns die möglichkheit was lebendig mit viele action zu machen: jogger, Krokodil, CIA agent mit Kippe, kene Ahnung....) ...>
5. Landscape visual: Irgendwann sieht man ein Vögel der lässig auf dem Memorial eine Kacke schiesst (absurd wie das Spiel :) ... >
6. spining Zeitung again ...>
7. Newspaper Headline, wat wie "Pigeon vandalised the memorial!!!" (in der art, to be continued! ) mit Bild der Statue (könnte auch ein zweites Bild von eine Taube die wie ein Pirat oder was lustiges aus sieht...

--- die Phase 4 und 5 könnte anstatt Pixel auch wie im main menu aussehen aber viel weniger action... (villeicht nur dem Vögel)

und wenn du das sagt mit High-Score:  könnte nach dem Punkte 7. ein fade in auf "High-Scores" plus buttons einfügen (und scheiss die UI Logik :)

![untitled-1](https://cloud.githubusercontent.com/assets/7753856/3818009/8a3f40de-1cdd-11e4-8dd0-d99cc9ab483a.jpg)

Brauchste Erklärungen? ist es nicht lustig?
finde persönlich dass es mehr Konsistenz am Spiel gibt...

––––––

(nur als Gedank, denke ich jetzt nach... könnte man fast eine Art fake "Towel Defence II" als finting Game (street fighter II) 
"Heroe" vs "Pigeon"

![untitled-8](https://cloud.githubusercontent.com/assets/7753856/3818266/ad486b9e-1cdf-11e4-9c6d-0a8512f837e3.jpg)

OK, villeicht geht es zu weit! ahahahah

**Comment by Waog** [comment]
Brauche keine extra Erklärungen, alles verstanden.

Also an scheißende Tauben habe ich auch schon gedacht und finde auch den zweiten Zeitungsartikel gut, aber:
- die Win-Sequenz ist zu lang. Wir machen nur ein Casual-Game. Wenn unser Spiel halbwegs Spaß macht, dann wird ein (not-first-time-)Spieler nach seinem 30 Sekunden Spiel möglichst schnell die nächste Runde starten wollen. Da ist es nicht gut, wenn er immer wieder die gleiche 30 Sekunden Sequenz angucken muss.
- Wir sollten möglichst wenig mit Texten arbeiten (wegen Übersetzungen). Den "Three Month Later" Bildschirm können wir meinetwegen weglassen. Ich glaube man versteht es auch so. Falls nicht -> z.B. eine Animation wie Kalenderblätter vom Kalender abgehen.

Anderer Vorschlag:
**Win:**
- Punkte 1 - 3 bleiben
- Punkt 4 bleibt, aber ohne Vogelscheiße, dafür mit Highscore
  - Spieler soll sich freuen
  - High-Scores können animiert sein und nach ein paar Sekunden verschwinden, wenn du willst, dass man deine Grafiken besser sieht
  - Buttons erscheinen im Park (Retry, Main Menu)
  - Passanten winken dem Guy zu

**Lose:**
- wie bisher, aber nach der Zeitung gehts weiter
- Nach der Zeitung ist auch der Park (for Consistency) zu sehen, aber ohne Statue und irgendwie negativ:
  - taube scheißt dem Guy auf den kopf oder
  - fahrrad-fahrer fährt durch pfütze und spritzt guy mit dreck nass oder
  - kinder lachen den guy aus
  - Buttons erscheinen im Park (Retry, Main Menu)
  - kein High-Score im Loser-Park

**High-Scores (mit Button im MainMenu):**
- Spinning News Paper "Pigeon Vandal" oder alternativ, ein Schwarzer Ladebildschim mit nur der pixel-Statue und einer tauben animation, wie die Taube draufkackt (zweite Variante finde ich besser, weil sie ohne Text ist)
- Dann der Park, mit vollgeschissener Statue und Highscore-Liste (vielleicht kleine Animation wie wie Kacke immer runtertropft)
- Park mit Back-Button

So hätten wir alles drin glaube ich:
- "Kurze GUI Wege" (Casual menu flows),
- Konsistente GUI Logik (Die Buttons sind in allen drei Fällen im Park)
- Alle deine Vorschläge (aber in anderer Reihenfolge)

PS: Hero vs. Pigeon ist cool, aber geht nicht gut auf mobile :laughing:

**Comment by ghost** [comment]
ok, klingt jut...

-würde dann beim LOSE and WIN eine "Illustration" (Key visual) fürs Park machen (d.h. erstmal keine "frame" animation drin. Oder kleine anim duch Programmierung wenn wir tatsächlich ein bisschen bewegung wollen)
-und beim "High score" im MAIN MENU, lieber wat in pixel art machen (wie CREDITS) und da kann man mehrere kleine anim einfügen...

**Comment by Waog** [comment]
Hmm... ich dachte, dass wir für win/lose/credits jeweils einen Park in Pixel-Art nehmen. Nur jeweils leicht verändert.
Das hätte den Vorteil, dass in unserem UI-Flow immer genau abwechselnd pixel-grafik und non-pixel-grafik hätten.

Warum willst du den Park teils so, teils so machen?

**Comment by ghost** [comment]
als "Baam" aber ich bin auch ok so...allet nur im Pixel Art ist super (geht schneller :) und macht mehr spass...

**Comment by ghost** [comment]
muss noch buttons und paar anim machen... aber den BG sieht so aus:

![bg_win_test](https://cloud.githubusercontent.com/assets/7753856/3848003/4e505c2c-1e6b-11e4-9750-4594e5487860.jpg)

**Comment by Waog** [comment]
nice. Vor allem der unscharfe Effekt bei den Bäumen im Vordergrund :)

**Comment by ghost** [comment]
ich habe das in zwei geteilt: HERO und ZERO #45 

![screen shot 2014-08-09 at 00 05 01](https://cloud.githubusercontent.com/assets/7753856/3863527/409e5aea-1f4a-11e4-9f85-cf3bb17056c6.png)

hab schon den Fahrradfahrer
![biker](https://cloud.githubusercontent.com/assets/7753856/3863473/7ef13a5c-1f49-11e4-94f6-14df1aeeeb2b.gif)

zwei menschen im BG
![people_dog](https://cloud.githubusercontent.com/assets/7753856/3863475/8c936a90-1f49-11e4-8730-54c44d1398eb.gif)

und Tauben
![pigeon_shit](https://cloud.githubusercontent.com/assets/7753856/3863477/9db5ad42-1f49-11e4-9410-0b1c585f08b1.gif)
![pigeons-ground](https://cloud.githubusercontent.com/assets/7753856/3863480/a2d34be0-1f49-11e4-9014-f3d09f901901.gif)

**Comment by Waog** [comment]
Gut :+1: 
- Die scheißenden Tauben würde ich erst im Highscore screen (aus dem Menü) einbauen.
  Wie wäre es im Win-Screen stattdessen mit solchen _Bling Bling Animationen_? du hast es schon statisch an der Ecke vom _Hero_-Schild gemacht. Sowas könnten wir an 2-3 stellen aufblinken lassen.
- Kannst du auch hier die Schrift _Hero_ wegnehmen? Das goldene Schild ist cool. Aber der lesbare text nicht so. stattdessen lieber gekrakel oder irgend eine symbolik.

**Comment by ghost** [comment]
Bling Bling Animationen habe ich auch jemacht (high lights Kanten) yep villeicht ab un zu ein part Sterne auf die Polierte Statue oder so...

Für die Schrift finde ich eigentlicht das wort "HERO" ganz gut. Es ist klar und einfach. Wegen die Lesbarkheit finde ich nicht sooo schlecht (auch für Mobil), aber stimmt, es fehlt Kontrast drinn...

ich probiere trotzdem eine Alternative...

**Comment by Waog** [comment]
integrated the non-animated stuff

**Comment by ghost** [comment]
in case of... the bling bling animation is in "park sprites": park_win_gold_plate.png...

**Comment by Waog** [comment]
hab alles eingebaut
