### ISSUE TITLE
Graphics LoseScreen

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#45]
- Animation “Flash Fotography”
- Animation Lose? (Zeitung?) << Discuss this with Programming... it may not work.

**Comment by Waog** [comment]
Forget about the flash fotography. Technically it's impossible to achive this effect in all browsers.

TODOs:
- [x] Lose Animations
  - Guy with towel on the ground and red face?
- [x] Lose Screen
  - one complete screen with the text "Game Over" and some nice artwork and space for one Button.
- [ ] "Main Menu" Button (up/down)
- [ ] "retry" button (up/down)
- [ ] After graphics are finished: add label `Task: Programming`

**Comment by ghost** [comment]
![lose_animation](https://cloud.githubusercontent.com/assets/7753856/3286521/7cfe9196-f54a-11e3-8e30-d46d02004404.gif)

WIP

**Comment by Waog** [comment]
:+1: 
Den Sinn vom Umdrehen nach hinten und die Blase mit dem "?" verstehe ich nicht genau.
Dannach ist es ganz cool finde ich... es wäre gut, wenn er nicht "vorwärts" rennt, sondern auf der Stelle. Wenn er genau vor dem Müllsäcken steht während er verliert kriegen wir sonst probleme... außerdem verbauche ich weniger Events, wenn ich nur eine neue Animation starten muss, ohne ihn zu bewegen :)

**Comment by ghost** [comment]
da wir noch ein gif für Zuschauer im BG haben (Hände Hoch und runter, zum Beispiel), man könnte im Finale "Lose sound" (zusätzlich von flash und photo apparat) leute die Lachen einfügen, Pfeife usw.

finde cool wenn er die erste Sekunden nicht versteht wat los ist, eins bisschen wie "euh, waten los? warum lacht Ihr??? was hab ich gemacht?" er schaut sich herum...

villeicht am ende läuft er im Kreis, oder hin und her :)

**Comment by Waog** [comment]
Ok, können wir probieren...

**Comment by ghost** [comment]
![lose](https://cloud.githubusercontent.com/assets/7753856/3307547/0f72189e-f66e-11e3-93bc-2bf015984520.gif)
 so wat in der art...

**Comment by Waog** [comment]
es gibt 2 probleme mit der grafik:
- man kann sie nicht spiegeln, wegen dem _?_. Aber spiegeln ist vielleicht auch nicht nötig.
- sie ist deutlich breiter als ein normales sprite vom guy. D.h. es kann passieren, dass das Handtuch auf dem Gully landet, oder der guy über die müllsäcke rennt.
  - vorschlag wie es trotzdem klappt: was hälst du davon, wenn während der lose sequenz der hintergrund schwarz wird und nur noch der guy (und vielleicht der regen) zu sehen ist? dann würde der guy nirgendwo dagegen rennen. Außerdem wäre sehr sehr deutlich, dass man verloren hat. Das wäre allerdings keine so geile Lösung für die win sequenz... da müssen wir uns was anderes einfallen lassen.

**Comment by ghost** [comment]
-"...dem Gully landet, oder der guy über die müllsäcke rennt."
hatte ich auch im Kopf, ich dachte wir können den sprite "hit" (electro) ab den moment wo er erwicht ist, den animiert (verschieben, "Street Fighter 2" style) bis zu mitte des  Screen... dann ist die Rest Anim keen Problem... kannste dich das vorstellen?

-Schwarz "fade on" oder so wat könnte eine Alternativ, aber haste recht, ist nicht so schick...

-Beim Gewinn kann man einfach was machen wo er auf der gleiche Platz steht, wie z.B. bewegung von ein Budybuilder, "Queen" Grüß wie eine Star, oder so hänliches...

**Comment by Waog** [comment]
- ich weiß nicht wie gut das mit dem verschieben aussieht. er bekommt einen treffer von oben ab und fliegt zur seite... irgendwie komisch. Ich weiß auch nicht, ob ich das so animiert bekomme, dass es flüßig aussieht und nicht mechanisch...
- Das mit dem schwarz finde ich gar nicht so hässlich... so ist es auch in pflanzen gegen zombies 2, wenn man verliert (finde die sequenz leider nicht auf youtube). Es muss auch kein fadeout sein, wir könnten z.B. auch den ganzen Bildschirm blinken lassen und/oder überall blitze blinken lassen und am ende schwarz machen.

**Comment by ghost** [comment]
http://www.youtube.com/watch?v=m0_tHQSoO-M
(0:26)

– da er electrocutiert wird find ich nicht so schlimm, und die amiation könnte ich auch selber machen,
aber du hast am ende recht, ist alles sher mühsam...
– "schwarz" (ich liebe jazz, hip hop, usw. "black is beautiful"!!! ho ho ho janz lustig oda? ok geht so :) könnte doch klappen, muss man einfach grafisch wat einbringen (muss ich bisschen rumfumeln...)

**Comment by Waog** [comment]
naja, ich fänds komisch, wenn er so fliegt wie in streetfighter... passt nicht so gut, wenn er von oben getroffen wird.

Aber vllt könnte er im elektrisierten zustand tanzen!? glaube ich hab sowas schon öfter in cartoons gesehen.

**Comment by ghost** [comment]
also, er fällt runter (immer elektrisiert) und tanzt/erschrekt uf die gleiche stelle? 
verstehe ich nicht janz genauuuuu... :)

**Comment by Waog** [comment]
nee, nix mit runterfallen. wenn er das letzte mal elektrisiert ist, dann springt er nicht nur hoch, sondern fängt dannach noch an zu tanzen und zwar richtung mitte des bildschirms... vllt ein moonwalk, tanz wie ein ägypter, oder was elektrisierte sonst so für nen tanzstil haben.

**Comment by ghost** [comment]
hab nochmal duch geprüft wie es aussieht mit der aktuelle Sequenz, und finde eigentlich ganz gut :)

![screen shot 2014-06-20 at 20 13 59](https://cloud.githubusercontent.com/assets/7753856/3344090/271d1a44-f8a7-11e3-9e57-46a6a8936d01.png)
falls Hit Auf der Rechte seite:
 mit dem Müll, finde ich gar nicht schlim das er ein bisschen überschneidet in dem run in circle, ist immer noch realistich.

falls Hit linke Seite:
Animiren wir den Sprite so das den Tuch runter fällt, wo die Füsse sind... 

Wir behanlten den BG mit animation (people, flash (zu machen übrigens) auto, Flugzeug, etc.) und dann ist allet tuti pallety oder? was meinste?

**Comment by Waog** [comment]
also ich weiß nicht was der BG, auto flugzeug usw mit der lose animation zu tun hat. was meinst du damit?

In deinem Bild sieht es jetzt ok aus wie er rennt, finde ich auch... also meinetwegen kann er so über die müllsäcke rennen wie in deinem bild.

**Comment by ghost** [comment]
zwischen eine lebendige final animation (BG, autos, flugzeug, usw) mit animation und ein Ending der mit ein schwarzer BG sich spielt, finde ich uterhaltsammer und dynamischer die erste Losüng...

**Comment by Waog** [comment]
also sollen BG, autos und flugzeuge beim lose andere animationen abspielen als die restliche zeit?

**Comment by ghost** [comment]
ne, genau die Gleiche Animationen im Background (Auto, flugzeug, etc.) wie dem rest des Spieles.
es ging mir nur darum das es zwichen bunte Ending or schwarze Ending, finde ich viel besser mit Bunt (Bunt bedeutet mit Farben, animationen mit die Menschen im Background, etc.)

der "Lose final" ist nur eine Kontinuität vom playgame...

![untitled-1](https://cloud.githubusercontent.com/assets/7753856/3351288/4e92f266-f9ff-11e3-832e-e46efcad8d6d.jpg)

**Comment by Waog** [comment]
bunt fände ich auch besser, aber wir müssen halt mal ausprobieren, wie das dann aussieht mit der lose animation und den borders. Diese woche habe ich wieder zeit zu entwickeln.

**Comment by ghost** [comment]
ok goody...

**Comment by ghost** [comment]
ist es nicht zu viel ein sprite mit ungf. 70 sequenz? ist es möglich als finale anim in zu bauen?
anstatt ein horizontal balken, kann ich es auch10x 7 einbauen, funktionniert es auch für dich?

**Comment by Waog** [comment]
ja 10x7 geht auch. Ob es zu viel ist müssen wir mal probieren...

**Comment by ghost** [comment]
Sprite liegt in DropBox "lose.png"

**Comment by Waog** [comment]
habe `lose.png` eingebaut

**Comment by Waog** [comment]
Der Issue ist noch nicht wirklich fertig. Dieser punkt fehlt noch komplett:
- Lose Screen
  - one complete screen with the text "Game Over" and some nice artwork and space for one Button.

**Comment by ghost** [comment]
-Fürs Lose screen, sollten wir nicht zwei buttons haben? (was wie "retry" und "menu"? und villeicht ein count down, und wenn nichts reagiert auf "...2,1,0" gehts automatich aufs Menu)
- wollen wir ein screen Unabhängig von "lose Animation and gameplay graphic" d.h. --->Lose animation (street) --> black screen 0.1 sec. ---> Lose screen (irgendwas wie text, mit Bild oder so).
  Beispiel: http://youtu.be/Hrtj6Qy0SYE?t=2m37s
- oder mehr eine kontinuität? (ende animation rennt er hin un zurück...) villeicht stopt er, steht dan da und fängt an zu weinnen wie ein Wale (count down ist da + buttons)

-sonst gab es noch die Idee vom Zeitschrift?... cover von "the Sun" tabloid oder so?
sowas aber in geiler: http://www.youtube.com/watch?v=anJiAYz9PKE

was denkste? bin mir nicht ganz sicher wat cooler ist...

**Comment by Waog** [comment]
- 2 buttons (retry + menü) finde ich gut.
- countdown + automatisch ins menü ... sehe ich erstmal keinen vorteil drin und es macht zusätzliche arbeit. wozu macht man sowas?
- finde die erste variante am besten. also nochmal ne eigene fullscreen-art mit platz für 2 buttons.
  - die kontinuität finde ich eher nicht so schön
  - die zeitschrift wäre erstmal auch nichts weite als eine fullscreen-art. also was das für eine ist, überlasse ich mal dir.

**Comment by ghost** [comment]
- "countdown + automatisch" in unser fall ( da es keine speicherung im laufen des spieles gibt, wie ein "platform game" (wo du schon im 3 Level bist) oder "kombat tournament" (schon 5 Feinde ausgeschaltest hast) die idee ein "countdown" wäre mehre eine Reaktion des Spielers hervorzurufen.
  Du hast recht, es ist nicht notwendig aber ich finde nicht so Geil das den "Lose screen" steht da  mit "retry + menu" für 2 minuten und nichts passiert...
- villeicht kann man die transition sie so was machen:
  http://www.youtube.com/watch?v=z72bJXrVko4&feature=youtu.be&t=4s
  (Kreis fade on transition oder so...)
- oder so was wäre eigentlich auch super lustig ( musik zu definieren...)
  http://www.youtube.com/watch?v=UEkvtNXGj9g
  (kannste auch bestimmt ganz einfach drehen oder?

**Comment by Waog** [comment]
- ok, dann würde ich vorschlagen wir machen erstmal ohne countdown, und merken uns countdown als nice-to-have issue. Den mache ich dann wenn noch events und lust am ende übrig ist... vom reinen arbeitsaufwand ist das kein so großes problem.
- kreisfade weiß ich gerade nicht, muss ich mal probieren. aber ein einfacher (alles auf einmal) fade geht auf jeden fall.
- die rotierende zeitung macht nur sinn, wenn der loseScreen auf jeden fall eine zeitung ist. Damit wärst du thematisch festgelegt. Ich kann sie rotieren lassen, aber diesen verschwommenen effekt bekomme ich vermutlich nicht hin. D.h. du müsstest vermutlich 1-2 extra grafiken für diesen rotations-effekt machen. Aber ich kann es erstmal mit einer grafik probieren, vielleicht siehts ja gut aus.

**Comment by ghost** [comment]
ok, juti  :+1:

**Comment by ghost** [comment]
hab die Zeitung  grafik erstmal so gemacht (Platzhalter) und dazu ein andere mit spinning effect... (und wie du meintest, wenn wir sehen das es nicht so geil aussieht, villeicht noch ein Paar "spinning" unschärfe Stufen, d.h. 2 oder 3 zusätzliche Grafik oder so...)

wäre ganz gut wenn du probieren könntest auf ein schwarzer hinterground wie beim Youtube Beispiel.

![newspaper](https://cloud.githubusercontent.com/assets/7753856/3611426/bca2c570-0d9a-11e4-991e-36983e4f25c1.png)
![newspaper_spin copy](https://cloud.githubusercontent.com/assets/7753856/3611433/c43d3e78-0d9a-11e4-9ddb-731989e26f57.png)

ich finde diese "UFO - Twilight Zone" musik style ganz cool, wat meiste?

(liegt im DropBox)

**Comment by Waog** [comment]
sehr gut, zeitung ist genau so wie ich es meinte :+1: 

was meinst du mit _"UFO - Twilight Zone" musik_? die aus dem rotierende-zeitung-youtube-video? die fände ich unpassend, weil sie zu ernst/seriös ist. Das ganze game ist jetzt extrem auf _retro-style_ und _lustig_ getrimmt. Wir sollten auch eine musik in dem style wählen.

**Comment by ghost** [comment]
Ja diese video http://www.youtube.com/watch?v=UEkvtNXGj9g .
 "ernst/seriös" finde ins gegenteil die musik sehr gut weil es so absurde ist (absurde wie  "Mars Attack" von Tim Burton oder "Batman and Robin" aus der '60...). In der Tat ist die Zeitschrif mit spinning auch komplet absurde (eigentlich unser ganzes game, hahahah :)

aber ok, sowieso, am ende müssen wir Musik Teste machen, wat am bessten ein mit ein ander geht usw. (musik intro+ game play+ win,etc.)

**Comment by Waog** [comment]
hmm... also vielleicht ginge diese twilight-musik, wenn sie im 8-bit-style ist. Aber ich bin noch nicht überzeugt.

**Comment by Waog** [comment]
kannst du das foto in der zeitung noch so machen, dass da der held mit verdecktem penis zu sehen ist? also den frame, wo er sich die hände davor hält, oder die beine gekreuzt hat? Ist besser für die öffentlichkeit geeignet :laughing:

**Comment by ghost** [comment]
ja klaro, wollte sowieso fine tuning machen... :)
(wir sind trotzdem pegi 18 oder, ahah http://www.pegi.info/de/ )

**Comment by Waog** [comment]
habe die zeitung eingebaut. sag mal deine meinung.
soll das so vor dem schwarzen hintergrund bleiben, oder lieber direkt im gameplay bildschirm angeflogen kommen? wenns im gameplay bildschirm ankommen soll, dann ist nicht klar wann (dann würde der spätere teil der lose-animation von der zeitung verdeckt werden). Oder willst du noch einen anderen hintergrund als schwarz machen, oder mir einfach nur nen RGB-Code sagen, welche farbe besser aussieht?

**Comment by Waog** [comment]
Buttons für den lose-screen fehlen noch.

**Comment by ghost** [comment]
erstmal sieht ganz cool so :) 
- wegen hintergrund Farbe finde es auch jetzt gut so (ich probiere trotzdem noch auf unterschiedlische Farben)
- die "spinning" animation: villeicht brauchen wir doch trotzdem ein oder zwei Grafik (mit Unschärfe) für eine Flüssige Animation...

**Comment by ghost** [comment]
was häslte davon, wir machen es auch so für win #43  after win screen mit andere Headlines auf die Zeitschrift... (wie in ein normales Tag, ohne rambazamba unber den hero).

Zeitschrift dreht sich > Zeitschrift fix und buttons tauchen (smooth) links und rechts auf.
![outro lose](https://cloud.githubusercontent.com/assets/7753856/3771716/d8fc5b06-18f7-11e4-95f6-ead58016e55d.jpg)

**Comment by Waog** [comment]
Die Buttons find ich gut :+1: 
Diskussion zum WinScreen siehe WinScreen-Issue #43

**Comment by ghost** [comment]
buttons liegen in Drop box...
hab noch dazu:
newspaper bg + newspaper shadow + newspaper small

Ziel wäre kurz nach der drehung, das Background (newspaper_bg.png) und die schatten taucht langsam auf (Übergang dauert villeicht 1 oder 2 Sekunden?)... kannste das machen?

**Comment by Waog** [comment]
verstehe nicht genau, wann was auftauchen soll... kannste das noch genauer schreiben?

**Comment by ghost** [comment]
"Opacity" langsam von 0% auf 100% (in ein paar Sekunden...) wie ein fade in.

**Comment by Waog** [comment]
ja, aber was soll wann faden?

**Comment by ghost** [comment]
ok...
Zeitschrift dreht sich (klein und wir immer grösser wie es schon jetzt ist) --> Zeitschrift freeze schräg (wie es schon jetzt ist) --> buttons+ shadow + bg: fade in langsam (1 oder 2 Sek.)

ich glaube es könnte gut aussehen (bin mir nicht ganz sicher, deshalb wäre jut wenn wir das probieren könnten...)

**Comment by Waog** [comment]
ok verstanden.
ich glaube es sähe besser aus, wenn der hintergrund sofort gezeigt wird, aber ich probiere es erstmal so wie du sagst.

**Comment by ghost** [comment]
![screen shot 2014-08-09 at 00 04 50](https://cloud.githubusercontent.com/assets/7753856/3863534/4f62a18a-1f4a-11e4-9bf8-c2d3a69fb881.png)

findest du besser wenn  beim "ZERO" die Stimmung anderes ist als beim "HERO" #43 ? wie regen oder am Abend sogar nachts mit feuer? oder so was. 
Ich bin mir nicht ganz sicher...

**Comment by ghost** [comment]
![screen shot 2014-08-11 at 00 57 31](https://cloud.githubusercontent.com/assets/7753856/3870843/16a15e9c-20e2-11e4-8a11-875d26bcc9ed.png)
hab das so.. .wäre lustig mit Blitze/Storm im BG und ein Godzilla in der Stadt... :)

**Comment by Waog** [comment]
Insgesamt cool.
- Aber ich mag das Schild mit _Zero_ nicht, aus diversen Gründen:
  - lesbarkeit auf mobile
  - unmögliche Übersetzung
  - dem spieler eine idee via text zu vermitteln finde ich grundsätzlich schlechter als sprechende bilder zu benutzen.
- Über godzilla bin ich auch noch unschlüssig. Vorher ist in der Zeitung die Top-News, dass der Guy peinlich ist. Und jetzte trampelt Godzilla durch die Stadt? :D

**Comment by ghost** [comment]
bin OK mit deine Argumente... 

haste villeicht eine Storytelling Alternative?

Wegen Godzilla, finde ins gegenteil lustig das wir ein Super hero haben (obwohl er verloren hat) und im BG läuft Godzilla, UFOS im Himmel und so was...

**Comment by Waog** [comment]
Story-Telling hatte ich schon im WinScreen Issue #43 vorgeschlagen:

---

**Lose:**
- wie bisher, aber nach der Zeitung gehts weiter
- Nach der Zeitung ist auch der Park (for Consistency) zu sehen, aber ohne Statue und irgendwie negativ:
  - taube scheißt dem Guy auf den kopf oder
  - fahrrad-fahrer fährt durch pfütze und spritzt guy mit dreck nass oder
  - kinder lachen den guy aus
  - Buttons erscheinen im Park (Retry, Main Menu)
  - kein High-Score im Loser-Park

---

ich glaube jetzt verstehe ich godzilla erst. Ist der Witz, dass die Stadt jetzt in Chaos versinkt, wo der Held sie nicht mehr beschützt? Wenn das der Witz ist, dann ist er noch etwas zu umständlich. Wir sollten den Witz näher an das koppeln was der Spieler wirklich erlebt hat und nicht vorraussetzen, dass dem Spieler klar ist, dass der Held sonst die Stadt rettet. Immerhin wird im geplanten Intro #47 vermittelt, dass er einfach nur zuhause sitzt und Zeitung liest.

Wie wäre folgendes (komplette sequenz innerhalb von 5 maximal sekunden):
- wir zeigen mehrere Tage oder Jahreszeiten im Zeitraffer
- anfangs sieht man weit im Hintergrund die hydranten-fontaine und der held ist im park und wird ausgelacht
- dann (tage/wochen später) steigt der wasserspiegel und überflutet die stadt, der held ist alleine im park säuft bier und hat nen penner-bart
- noch später, tauchen riesen-tentakeln aus dem wasser auf und reißen ein hochhaus ins wasser. Der penner-guy schläft neben seinem Einkaufskorb und Bierflaschen.

zu kompliziert? zu schwer zu verstehen in 5 sekunden?

meinetwegen sollten wir godzilla und ufos, lieber in den highscores #60 machen. Im Lose-Screen einfach nur ein ausgelachten Held + Regen.

**Comment by ghost** [comment]
Mussen zwichen "lustige ideen" und "easy machbarkheit"(animation und so) eine Balance finden :)
- Taube scheisst uf dem Kopf, ja aber wir haben schon Tauben die kacken beim "Park - High score menu" ist für mich lanweilig, zwei mal zu sehen...
- Fahrrad pfütze, yep! (muss nachdenken für eine anim...)
- Kinder lachen aus: da die Stimmung grau ist... Kinder im Bild finde ich nicht so passend...  und Kombination "homeless" style (hero mit guitarre im Dreck...usw.) + ausgelacht, nicht so der knaller... (man lacht nicht über Leute im Not. hab von meine mama gelernt hahaha)

wegen Godzilla " Chaos versinkt, wo der Held sie nicht mehr beschützt?" ist zu weit gedacht...
brauch man nicht zu viel nach zu denken als player... 
geht mir nur darum:
wir haben ein hero/superpower der eine pause/depression im park macht/ist... es passiert was im Frontground und lustigeweise ein Monster (oder what else) taucht auf im BG... 

aber villeicht lassen wir godzilla einfach in Japan :) ahahaha

Vorschlag Sequenz finde ich gut, aber ja, meine Meinung nach zu komplitziert :s

**Comment by Waog** [comment]
Hmm... meinst du es ist vielleicht zu kontrovers den Held als Penner darzustellen und ihm noch weiteres ungück wiederfahren zu lassen?

Wie wärs mit: einfach langweilig lassen den Hintergrund? also nur eine graue Stadt und gut.
Dafür animieren wir Held und High Score Liste, um so besser. So müssen wir uns keine zusätzliche Story ausdenken. Und es lenkt auch nichts von dem ab was eigentlich relevant ist:
- ein niedergeschlagener Held und
- die high scores

für den Held finde ich einiges noch unpassend:
- ZERO-Schild (siehe oben)
- Gitarre -> Damit assoziiere ich positive Gedanken
- Die Kopfbedeckung -> Was soll das sein? Sieht für mich aus wie Federn.

Gegenvorschlag:
- Held hat so ein Papp-Schild zum betteln in der Hand und eine Dose
- Keine Mütze/Federn sondern zottelige Haare + Bart
- und irgendwas mit seiner Strom-Fähigkeit. Vielleicht kommt wieder so eine Schadens-Animation, nachdem er mit Schlamm vollgespritzt wurde?

Je mehr ich drüber nachdenke, desto weniger mag ich die Idee des unglücklichen Helden.
Kennst du das halbe Ende von Super Wario Land oder Kirbys Dream Land 2 (Game Boy)?
- **Super Wario Land:** Wario gewinnt, aber hat noch nicht alle Münzen. Er kriegt nicht sein erhofftes Schloss sondern weniger (z.B. Vogelhaus). Und guckt dann komisch mit nem fragezeichen überm Kopf oder so.
- **Kirbys dream Land 2:** man besiegt den Endboss, aber hat den letzten Endboss noch nicht freigeschaltet. Es kommt irgend eine Anspielung darauf, dass noch mehr möglich wäre (Schatten und Fragezeichen).

Wie wäre sowas bei uns? es herscht eine neutrale Situation (dem Helden gehts nicht schlecht, aber auch nicht gut). An der Stelle wo beim Win die Statue steht, bleibt der Held kurz stehen und guckt verdutzt... das wars.

Im vergleich zu den GB spielen, hat bei uns der spieler allerdings nicht (unvollständig) gewonnen, sondern verloren. Daher weiß ich nciht wie gut die referenzen sind.

**Comment by ghost** [comment]
yep! " also nur eine graue Stadt und gut." finde ich gut so... villeicht nur eine Flasche die sich umkippt, ein Blitz im BG oder so? für ein wenig bewegung..
und ich würde unser Hero gar nicht Zeigen...

ich finde das wichtige im ending WIN  #43 und LOSE; ein unterschied zu zeigen auf die STATUE Fläche...
- WIN eine super Statue
- LOSE abgefackte Fläche

Zero Schild, Gitarre, usw kann einfach weg... oda?

Übrigens, uf dem Kopf ist "deuuuuutlich" ein COWBOY Hut zu erkennen... hahahahh  es ist eine Ode an "Robert John Buck", mehr bekant Weltweit als "the naked Cowboy"... google ihm mal :) Ist eigentlich eine Touri Attraktion in Timesquare seit ewig... (aber egal, ist nicht wichtig für uns :)

Die idee aus dem GB Spielen finde ich ganz gut, aber passt meine Meinung (wie du es auch sagt) nicht;
Spieler verliert, ist dann nackt ---> lose screen Zeitung pi pa po.. ---> Park: er steht da (nackt? finde ich nicht jut... mit Tuch? macht nicht so Zinn, er hat es verloren...)

**Comment by Waog** [comment]
Finde die Iee eigentlich gut, aber:
Wir müssen davon ausgehen, dass der Spieler noch nie gewonnen hat, wenn er den LoseScreen sieht. Also ist für ihn völlig unverständilich: warum ist da jetzt ein Park zu sehen? Was hat das mit der Story vorher zu tun?

Wenn nichtmal der Held zu sehen ist, dann ist gar kein Zusammenhang zu vorher. Wie wärs, wenn das Handtuch angeflogen kommt, und in einem Baum/Strauch hängen bleibt?

**Comment by ghost** [comment]
Finde das dieses "düster" Ending mit Muhl und so erregt den Spieler noch mehr um zu sehen was los ist wenn man gewinnt... dazu ist im BG ist die gleiche Stadt zu erkennen... (das ist die Brücke mit dem Spiel)

wat meiste mit "Baum/Strauch hängen bleibt?"? 
komme auf diese Idee, lustig wäre dann:

Man sieht beim Rainweiden ein der ein bisschen grösser ist (erstmal passiert nichts)... dann sieht man ein Gesicht drinn, kommen 2 beine... (ist drin versteckt) und versucht undercover von links nach rchts zu laufen... wenn ein fahrrad fahrer vorbei kommt, der Busch geht wieder runter... usw.

![screen shot 2014-08-14 at 12 19 42](https://cloud.githubusercontent.com/assets/7753856/3918678/05b2f6d2-239d-11e4-89c0-f4ba19251989.png)
![screen shot 2014-08-14 at 12 20 16](https://cloud.githubusercontent.com/assets/7753856/3918679/0a471eb2-239d-11e4-86c8-170e16f420e7.png)

**Comment by Waog** [comment]
**hängenbleiben:** damit meine ich, dass das Handtuch erst mit dem Wind angeflogen kommt. Dann bleibt es an irgend einem Ast hängen und weht da einfach vor sich hin, wie eine Flagge nur unordentlich befestigt.

**Das Busch-Kostüm** ist auch gut. Aber die beiden Dinge sollten nicht gleichzeigit passieren. entweder Kostüm oder fliegendes Handtuch. ... Oder erst schleicht er komplett aus dem Bildschirm, und wenn der Spieler dann immer noch keinen Button gedrückt hat, dann kommt auch noch das Handtuch angeflogen.

Ich würde aber in beiden Fällen nicht hinschreiben _3 Monate später_. Könnte auch ne stunde später sein und würde genauso viel Sinn ergeben.

Was meinste?

**Comment by ghost** [comment]
Okay... finde auch beide gut (3 Monate später ist auch nicht so wichtig...)
preferenz für Busch Kostüm (mit "kein Button gedrückt" Variante)

**Comment by Waog** [comment]
Also beides nacheinander... halte ich auch für die beste variante. Cool, dann machen wir das so :)

**Comment by ghost** [comment]
![guy_bush](https://cloud.githubusercontent.com/assets/7753856/4171205/8e1b0b46-353a-11e4-8f63-9f7745b0515b.gif)

hab jetzt das LOSE ending so mit dem Typ gemacht. Ideal wäre (es ist nur ein loop erstmal) ein zweites loop (durch programmierung) damit er weg aus dem Bildschirm geht. 

cool wäre, nach das erste loop, das fahrrad fahrer fehrt durch den park... und dann loop 2...

Wenn YOU weg from Bildschirm ist, nach ein Paar Sekunden kommt das fligende Tuch (beim Beispiel ist es falsch...)

es liegt im Drop Box... (tuch muss ich noch machen...)

**Comment by Waog** [comment]
:+1: geilo!
freue mich schon drauf das einzubauen :)

**Comment by ghost** [comment]
cool! :)

hab noch das flying towel und ein sprite wind dazu (separat)...
liegt in Drop Box, und sieht so aus...

![towel_wind](https://cloud.githubusercontent.com/assets/7753856/4175944/11a326d0-35ed-11e4-8904-aa82ce1721e6.gif)

(das tuch sollte mit dem letzte frame aufs Müll eingerichtet wenn es geht...)

**Comment by ghost** [comment]
hab noch ein jogger eingebaut fürs PARK_LOSE venn er verstech sich :) (liegt im drop...)

![jogger](https://cloud.githubusercontent.com/assets/7753856/4176139/4a6a2114-35f5-11e4-89aa-d475748eebb2.gif)

**Comment by Waog** [comment]
der jogger sieht dem guy sehr ähnlich. kannst du dem ein paar deutlichere unterscheidungsmerkmale geben? blonde haare? andere hautfarbe? andere frisur? breitere brust?

**Comment by ghost** [comment]
yep haste recht, mache ich... :)

**Comment by ghost** [comment]
ok, hab den nur ein "bisschen" den verändert... (ist in drop)
![jogger_new](https://cloud.githubusercontent.com/assets/7753856/4178716/8065b3d8-36a3-11e4-9efe-5e6275153d45.gif)

**Comment by Waog** [comment]
die grafiken sind jetzt in den losescreen eingebaut.... der guy bewegt sich nur einmal
