### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#47]
Mit Programmierung abstimmen, was für Formate funktionieren, und ob es überhaupt geht.
- [ ] "replay intro button" (pressed and released) im hauptmenü.

**Comment by Waog** [comment]
- “Grafische Präsentation mit Sympathische Beschreibung des Spiels ganz am Anfang hinzufügen.”
- was haltet ihr von kleinen Intro-, Win- und Lose-Filmchen? Kannst du sowas erstellen Stefano?
- Ste: Ja ich könnte etwas grafisches machen. Animationen? Mal überlegen!
- Oli: hat sich vermutlich erledigt. ich kann keine Animationen einbinden. Nur welche die ich selbst zusammenstelle. Keine AVI, MPG oder FlashFilme oder ähnliches.
- Ste: Ja, Animationen kann auch mit Jpeg oder ähnliches machen. Besser wenn alles einfacher für uns wird.
- Animationen ist vllt das falsche Wort… ich meinte damit Film-Sequenzen.

**Comment by steplus** [comment]
Animationen oder Film-Sequenzen? Ist das vielleicht nicht dasselbe? ich meine für Animationen natürlich was wir schon am meeting zusammen gemacht haben. Kurze Sequenzen in denen sich der Towelguy sich bewegt.

**Comment by Waog** [comment]
Animationen macht christophe. und die sind auch schon fast fertig. Ich meine Film-Sequenzen.

**Comment by Waog** [comment]
Sowas in der Art ginge technisch vermutlich: http://www.tubechop.com/watch/2979873

**Comment by Waog** [comment]
Meinungen?

**Comment by ghost** [comment]
Wäre eigentlich ein "Animatic"... finde ich jut.
aber du würdest die Bilder (PNG-high-res-coole Visuals...) per HTML5 animieren richtig? (wie beim play für Flugzeug, Autos, etc.)

**Comment by Waog** [comment]
Ich bin nicht sicher, ob ich die Frage richtig verstehe.
Also ihr würdet mir statische unanimierte Grafiken liefern. Ich würde sie nacheinander einblenden und fading einbauen.Und das würde ich in Constructor2 machen (was am ende zu HTML5 kompiliert, ja).
Frage beantwortet?

**Comment by ghost** [comment]
Genau. Ist es Blöd oder Schwierig für dich?

**Comment by Waog** [comment]
nö, das ist sehr einfach, solange es vor oder nach dem gameplay passiert.

**Comment by Waog** [comment]
Wenn wir ein intro einbauen, dann wäre ein "replay intro" button im hauptmenü gut.

**Comment by ghost** [comment]
"Ich dachte wir machen sonen kleinen "animatic"

yep, so war es geplannt (ursprunglich dachte ich mir was richtug "Parallaxe", da wir ein key visual erstellen wollten.) Das key visual ist jetzt für unser MENU benützt. Sieht gut aus, aber viel zu detailliert um eine vernunftige animation via Programmierung zu machen...
dazu haben wir zwichendurch viele Sachen klarer fürs Spiel gemacht und mehr kontent im Spiel eingefügt als gedacht (jeden falls für mich :) wie: ending animationen, gameplay animationen, high score, etc...

d.H wir sollten flexible bleiben und sich überlegen ob man es tatsächlich braucht...

ich sehe 3 unterschedliche Möglichkheiten:
1. Intro sequenz mit fat Logo und "Strom Blizte" Animationen (mit Geiler Sound effects und noch ein Paar electric animation... kan es knaller aussehen....)

Vorteil: nicht Schwer zu machen, ist ein "BANG! intro", sieht geilo aus.
Nachteil: erklärt nicht was man machen muss (> sollte im spiel schnell Erklärt werden oder worum es geht --->Punchline/Bubble) 

oder 
1. Ein art Comic sheet/storyboard (MARVEL, DC Comics,etc...) mit unsere Geschichte und via Programmierung (du), (small zoom in) Kamera fliegt durch die geschichte bis unten rechts (vom Sheet)

Vorteil: Die Geschichte ist sofort zu verstehen, könnte SUPA geilo aussehen.
Nachteil: ich muss die Zeichnung mit gleichem niveau fom MENU Key Visual machen, d.H wird ewig (eeeeeeeewig!) dauern um wat geil zu machen...

oder
1. Keine Intro und wir Lösen die "Background Story" durch 2 Satz in eine Bubble, wie es gelernt ist in alle kult Games...

Vorteil: Zeit gespart, Qualität/Zeit optimal
Nachteil: ist nicht super geilo...

Meinung:...

**Comment by Waog** [comment]
see #53
