### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#48]
For experimenting with github.
# Try whatever you want here.

**Comment by ghost** [comment]
![towel_defence_sprites2](https://cloud.githubusercontent.com/assets/7753856/3139154/0e1847fc-e8cc-11e3-851f-a4e98dd79b86.gif)

**Comment by Waog** [comment]
[ ] Checkbox 1
[x] checkbox 2.

**Comment by Waog** [comment]
- [ ] another test
- [x] and a checked one

**Comment by Waog** [comment]
- [ ] one task
  - [x] a nested task
  - [ ] another nested task
- [x] a second task
