### ISSUE TITLE
Particle Graphics

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#50]
We need (non-animated-) sprites for each of the particle effects. Currently i've just painted some quick-shot for each particle effect, which does not match the overall graphical syle.

TODOs:
- [x] multiple sprites for lightning
  - current version: ![lightningparticles](https://cloud.githubusercontent.com/assets/5098472/3199530/ecbd137e-ed69-11e3-880c-ecb355263867.png)
    ![lightningparticles2](https://cloud.githubusercontent.com/assets/5098472/3199528/ecbab1ba-ed69-11e3-849a-898f964eaa40.png)
    ![lightningparticles3](https://cloud.githubusercontent.com/assets/5098472/3199529/ecbca4f2-ed69-11e3-83d9-66a259f36e49.png)
- [x] sprite for the small rain drops
  - current version: ![rainparticles](https://cloud.githubusercontent.com/assets/5098472/3199531/ece61b16-ed69-11e3-8322-e2fa7ffb5fae.png)
- [x] sprite for the splash effect of the small rain drops
  - current version: ![splashparticles](https://cloud.githubusercontent.com/assets/5098472/3199527/ecb8fcda-ed69-11e3-88ea-d673f3f3e10f.png)
- [x] sprite for the splash effect of the large rain drops
  - current version: ![dropsplashparticles](https://cloud.githubusercontent.com/assets/5098472/3199501/7ff13b08-ed69-11e3-98e1-93caab53998e.png)
- [ ] sprite for the fontain spray effect
  - current version: ![dropsplashparticles](https://cloud.githubusercontent.com/assets/5098472/3199501/7ff13b08-ed69-11e3-98e1-93caab53998e.png)
- [ ] Label the task as `Task: Programming`

**Comment by ghost** [comment]
Die ersten in grün sind für die Intro?

**Comment by Waog** [comment]
ja, aber ich könnte sie auch für den Angriff benutzen. Oder alternativ andere für den Angriff. Ich machs am Ende wie du magst.

Die müssen auch keinesfalls grün bleiben, die sollten halt zum overall-style passen.

**Comment by ghost** [comment]
![drops_fg](https://cloud.githubusercontent.com/assets/7753856/3199939/7737e368-ed73-11e3-8f01-d8254cb6acf2.png)
(drop front)

![drops_bg](https://cloud.githubusercontent.com/assets/7753856/3199942/7fe093c0-ed73-11e3-9503-ebb1a0a862bd.png)
(drop background...)

kannste wat damit anfangen?

**Comment by Waog** [comment]
nein.
1. was ist soll drop front/background sein?
2. ich kann nur einzelbilder (keine animationen) benutzen.

**Comment by ghost** [comment]
zwei Art für (eine mehr Gründlich (drop front) und die zweite grober (drop background) eine bessere visuelle Tiefe ... aber egal, wenn du das nicht benutzer kannst...
wir können es trotzden nacher für die "Lose" final anim benutzen...

(hab nur jetzt gelesen "(non-animated-) sprites for each of the particle effects" hattest du geschrieben, my fault...)
können wir trotzdem mehr Instanz für Particles einfugen (nicht nur eine sondern zwei oder drei... )
für mehr random?

**Comment by Waog** [comment]
Ja mehrere Instanzen von Particel-Effekten sind möglich, aber technisch etwas umständlich in construktor.

Bei den blitzen im main menu, mache ich das ja bereits. Da kommt immer zufällig einer der drei Blitze.

**Comment by Waog** [comment]
Meinst du das mit front/back?
![problem with sprites toweldefence](https://cloud.githubusercontent.com/assets/5098472/3200293/5a8bf3d8-ed7a-11e3-853d-21f8c95a3c7a.png)

**Comment by ghost** [comment]
Oui :)

**Comment by Waog** [comment]
Das ist möglich, ja... dafür muss ich dann einfach 2 partikel-effekte anstatt einen machen und vllt ein neues layer hinzufügen (ich bin glaub ich auf 5 layer beschränkt in der free version von construct, also nicht übertreiben :smile: )

**Comment by ghost** [comment]
http://www.share-online.biz/dl/OA8LGR6NH0VP

schau dir mal das an... 
Hab erstmal  3 unterschiedliche "small drops" und 3 unterschiedliche "splash small drops".
Macht  es Zinn für dich so? 

dazu ist ein neuen Background... kannste das bitte im Spiel ersetzen? wäre gut für mich wegen visuals usw.

**Comment by Waog** [comment]
der background hat plötzlich eine andere auflösung, bisher hatten wir **1424 x 1168**. Das sollte auch so bleiben.

**Comment by ghost** [comment]
my bad...

**Comment by Waog** [comment]
- ich kann das bild so nehmen. Aber es könnte sein, dass github es beim hochladen komprimiert oder so. Bei mir ist es **20.169 Bytes** groß. Wie groß ist das original?
- ich werde die grafiken vermutlich erst sonntag einbauen.
- wie hast du dir die partikel gedacht? welche sollen nach vorne, welche nach hinten?
- der fußgängerweg im hintergrund ist vllt ein bisschen zu klein. Ich hatte mir überlegt, dass wir da zur dekoration vielleicht irgendwelche passanten langlaufen lassen. Ne alte oma, n fahrradfahrer und so. Musst du dir mal überlegen, ob du sowas machen willst und wie...

**Comment by ghost** [comment]
- ungf 78K, ich schicke es dir nochmal Morgen oder so via share online.
- da es keine GIF mehr ist, kann ich schwehr beurteilen. kann mann erstmal sehen wie es so aussieht?
  -BG, auf jeden fall: Passanten, autos, flugzeug oder so wat... wäre juti

**Comment by Waog** [comment]
übrigens noch besser als share online, wäre google drive oder dropBox... da muss man nicht immer captchas eingeben und 30 sekunden warten.

**Comment by ghost** [comment]
"multiple sprite for lightning" ist momenta nicht so wichtig, da den layout noch nicht gemacht ist...

sonst hab ich den rest (via drop box?) ich muss trotzdem das eingebaut sehen (Tropfen und Background)
villeicht sieht es richtig kacke... :s

**Comment by Waog** [comment]
Ich stimme zu. Ist nicht so wichtig (deswegen label "Prio:Optional" anstatt "Prio:Mandatory").

Und ich baue es vermutlich erst Donnerstag oder Freitag ein. Habe vorher wenig Zeit.

**Comment by ghost** [comment]
"multiple sprites for Lightning" für die Intro sind abhängig von der Visual Intro/Menu #47  (noch nicht fertig)

**Comment by ghost** [comment]
1.Die Fläche wo die Tropfen platzen ist noch nicht angepasst oder? (Platz bis höhe von Kopf zuschauer im Background)
2.Tropfen platzen haste nich ersätzt ich bin so trauriggggg :(... :)
3.Finde die "Passive" Tropfen zu groß
4.Finde die Tropfen "Aktiv" viel zu goß

finde viel äestetischer wenn die pixels Proportion behalten sind.

**Comment by Waog** [comment]
1. welche tropfen? wo die großen platzen ist bereits angepasst... die kleinen noch nicht, nein.
2. die großen tropfen schon, die kleinen fehlen nocht. Ich verstehe nicht, wie ich deine splash-pngs benutzen soll.
3. & 4. & proportionen: ich finde die originalgröße viel zu klein. die kleinen tropen nimmt man gar nicht wahr und für die großen muss man schon sehr genau hingucken und die wirken auch nicht wie eine bedrohung oder wie spiel-relevante objekte. ... ich lade aber gerade für die version mit den kleinen tropfen hoch, damit du es mal angucken kannst.

**Comment by ghost** [comment]
1.
![screen shot 2014-06-14 at 00 29 15](https://cloud.githubusercontent.com/assets/7753856/3276462/ad13ad8c-f34a-11e3-95ab-12bdc6bed8e9.jpg)
Pink sollte nicht die Platz Zone sein?
1. Splash PNG sind 3 unterschiedliche Bilder (nichts ein mit ein ander zu tun) kann man die 3 Art random verteilen?
2. haste recht, kommt nicht genug raus vom BG. villeicht zwei/dreifach grösser und heller (weiss) wäre besser?
3. stimmt auch, und wenn wir die zwei mal grösser machen, plus ein art "Faden" (wie eine Spur... wie regen eigentlich :) es könnte helfen oder?

**Comment by Waog** [comment]
**pink:** ja ist schon so, wie du gezeichnet hast. aber halt bisher nur für die großen tropfen.

**splash-png:** und dann ohne animation und partikel-effekte, oder wie? verstehe es immer noch nicht.

**tropfen-große/-kontrast:** du hast photoshop :) probier einfach aus, was gut aussieht... du musst es ja nur vor den hintergrund malen, dann hast du nen eindruck.

**faden:** vielleicht... probier es aus :) könnte sein, dass du mir den faden dann als seperate grafik geben musst, weil der spieler sonst damit kollidieren kann.

**Comment by ghost** [comment]
pinkos: verstanden

splash-png:  also "passiv": "drops fallen" ist mit particles (jemacht), und "splash" ist dein grafik (kannste mit: splash_small_drops_1.png, splash_small_drops_2.png oder splash_small_drops_3.png ersetzen)  ohne animation. finde ich eigentlich ok 
"aktiv": "drops fallen" mit big drops.png und "splash" mit particles effekt wie es jetzt ist finde ich auch gut.

tropfen-große/-kontrast+ Faden: P'shop, mach ich (werde auch :) gerne, trotzdem muss man das irgendwann einbauen um zu kiecke ob es mit animation, interaction, etc. funktioniert und gut aussieht...

**Comment by ghost** [comment]
new in Brop Box:
- "Big drop"
- "Big drop Alternative 1 und 2" (Drop und Spure separat)
- "smal drops 1,2,und 3"

**Comment by Waog** [comment]
Also habe beim einbauen ein problem festgestellt:
Ich brauche partikel-Grafiken immer mit quadratischem Scale. Construct2 verzerrt alle partikel-grafiken die AxB pixel groß sind. Sie müssen also immer AxA groß sein.

Habe die Grafiken trotzdem mal (teilweise) eingebaut, damit du einen eindruck hast. Mir gefällt nicht so gut wie es aussieht.

**Comment by ghost** [comment]
Ah ok, hädelt es sich nur ums Ratio vom PGN? (3pixel mal 3 pixel...egal ob es trenzparenz drin gibt?)
z.B. kleine splash tropfen sindd 12x21 sind Sie dan verzerrt? kann man 21x21 mit trenzparenz machen?

was magste nicht  so? drops visual? drops splash?
Persönlich finde ich 
- die große Tropfen: ziemlich cool... (vibriert ganz oben, ist bestimmt wegen scale?) 
- die große Splash Tropfen: ziemlich cool (ist leider ohne Schatten auf dem Boden, wäre noch geiler... aber gibt bestimmt keine Lösung mit particles?)
- Kleine Tropfen: villeicht noch zu klein? sieht man die kleinste vom "particle size random" nich richtig 
- Kleine Splash Tropfen: es hat auch ein art von random size richtig? manchmal finde ich es zu groß und unscharf wegen scale?

**Comment by Waog** [comment]
- also 21x21 mit transparenz geht ohne verzerrung, genau das brauche ich.
- große tropfen: vibration habe ich eingebaut, um animation zu testen. unanimierte tropfen sehen doof aus. Die großen Tropfen finde ich ok, aber wir sollten so 3 verschiedene tropfen mit jeweils eigener animation haben, damit es nicht zu langweilig wird.
- wegen den restlichen partikel effekten müssen wir uns glaub ich mal n paar stunden treffen und die zusammen fertig machen...

**Comment by ghost** [comment]
- hab das ersetzt
- ok cool. d.h 3 unterschidliche "große Tropfen" design und du baust ,wie bei deinem Test, die animation damit, ist es richtig?
- allet klar...

**Comment by Waog** [comment]
- na ich würde die größe der tropfen außerdem noch zufällig skallieren, also du kannst auch alle gleich groß machen. Das verwaschene kommt glaub ich dadurch das die nicht quadratisch waren...

**Comment by ghost** [comment]
hab 3 unterschidliche "große Tropfen" im Drop Box: "big drops_alternative1.png", "big drops_alternative2.png" und "big drops_alternative3.png"

**Comment by Waog** [comment]
FIXED: verzerrte splashes

**Comment by ghost** [comment]
Logo im Hauptmenu würde ich so machen für die kleine animation:
- Haupt blitz/electrics so (der jede 4 oder 5 sekunde kommt mit super sound) (muss den effekt noch ein bisschen besser hin kriegen...):
  ![title-test](https://cloud.githubusercontent.com/assets/7753856/3782296/10f67520-19a0-11e4-8afd-d6c9d3e9d5a1.gif)
  plus:
- 2 oder 3 (kleinere aber hänlich) die für particles gedacht sind...
  Meinung?

**Comment by Waog** [comment]
sehr geil :+1:

**Comment by Waog** [comment]
ich finde die tropen übrigens im moment zu unauffällig. die kleinen sieht man im grunde gar nicht.
und für die großen, muss man noch zu genau hingucken. Die großen Tropfen sind in der Spielmechanik  viel zu Bedeutsam, um sie so unauffällig zu gestalten. Die brauchen sowohl mehr kontrast, als auch mehr größe glaube ich...

**Comment by ghost** [comment]
"electrics" für den Title  liegen in Drop...
-logo simple
-electric prime (geht druch logo von links nach rechts)
-electric small 1,2,3 und 4 (für particles... sind viereckig)

![elec_big](https://cloud.githubusercontent.com/assets/7753856/3789358/85321bc6-1a9d-11e4-81d4-c10e3986b1d0.gif)
![elec_small1](https://cloud.githubusercontent.com/assets/7753856/3789363/ba2e3c7e-1a9d-11e4-8eeb-8cd77449aaad.gif)
![elec_small2](https://cloud.githubusercontent.com/assets/7753856/3789364/bd98381a-1a9d-11e4-9d3d-4846ca3ef724.gif)
![elec_small3](https://cloud.githubusercontent.com/assets/7753856/3789365/c0f1e33a-1a9d-11e4-9342-c49d4a436503.gif)
![elec_small4](https://cloud.githubusercontent.com/assets/7753856/3789366/c3b500d4-1a9d-11e4-9585-b3b928ec36cf.gif)

**Comment by ghost** [comment]
Tropfen: du hast recht, die kleine sieht man kaum... (wegen helleres BG) villeicht dunkel blau wäre besser?
für die "big drops", ja, villeicht mehr Kontrast, haste recht aber die Grösse finde ich sehr gut so. Wir hatten die schon mal am Anfang grösser gemacht und es sah nicht sooo gut aus...

**Comment by Waog** [comment]
Mach mal dein Browser-Fenster so klein wie ein Handy, wenn du spielst.
Damit kannst du dir mal angucken, wie es nachher auf einem Handy aussieht. Die kleinen Tropfen sind bei mir unsichtbar, die großen zu unauffällig.

**Comment by ghost** [comment]
stimmt... kleine Drops sieht man sowieso nicht, und Grosse pepsen nicht genug.

sollten Probieren mit eine Outline herum die  grosse Tropfen...

ist es möglich bei die kleine wat zu programieren wo: 
solage es auf die Fläche X ist, hat es die Farbe "A".Und wenn es auf die Fläche Y ist hat eine Farbe "B"?

Ich sehe die gaze Tropfen problematik nich wegen die Grösse (die gaz gut so ist) sondern als "Kontrast problem" mit dem BG... villeicht muss ich den BG (sky, buildings,etc.) auch ein bisschen dunlker machen...

**Comment by Waog** [comment]
Also die eleganteste Lösung wäre vielleicht einen anderen _blend mode_ einzustellen. Ich habe folgende zur Auswahl:
- ADDITIVE (a.k.a. add)
- XOR (a.k.a. exclusive or)
  musst du mal mit photoshop layern probieren, was da gut aussieht.

An _BG dunkler machen_ (oder heller, aber insgesamt weniger kontrastreich) habe ich auch schon gedacht. Aber mach uns erstmal nicht die arbeit, alle Bilder auszutauschen. Ich kann stattdessen einen halb-transparenten schwarzen layer darüber machen, um erstmal zu sehen wie es aussieht. Können wir beim Treffen diskutieren (see #56 ).

Der Farbwechsel ist für die kleinen Tropfen problematisch. Die sind im Moment als Partikel eingebaut, da habe ich nicht so viele Einstellungsmöglichkeiten. Ein einziges Bild (non-animated), und im dann lässt sich nur noch die Größe und Position ändern. :\

Ich könnte die Tropfen vielleicht auch komplett umbauen (nicht als partikel, sondern als dekorative game objects, wie die autos), aber ich weiß nicht wie performant das ist bei 500 tropfen gleichzeitig.

Ich würde eine grafische Lösung bevorzugen, anstatt das komplett neu zu programmieren.

**Comment by Waog** [comment]
There are also other blend modes, but I can't see how we could use them:
https://www.scirra.com/manual/146/effects

**Comment by Waog** [comment]
see #80

**Comment by Waog** [comment]
see #76
