### ISSUE TITLE
Intro Story Comicbook

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#53]
## storyboard
- The Guy is just called "You" (i.e. the player) if we use any texts at all. No texts would be even better.
- It is totally common that the Guy uses electric superpowers.
  (- He shuts down his alarm in the morning with it.)
  (- After that, he sits in the kitchen in his towel, reading a letter or newspaper, while eating breakfast.)
- Füttert Goldfisch, dabei spritzt Wasser an ihn. Er wird geschockt und leidet.
- Er lässt (dadruch?) seine unterhose los. Diese Fliegt durch Wind weg.
- He runs after it.
- Out there the shorts stop lying on the hydrant.
- Menschen fangen an interessiert zu gucken..
- Guy stops, because of trash stack.
- Guy uses telekinese/lightning to get shorts.

---- Tutorial Starts #73  ----
- Shorts are successfully removed from the hydrant, but fall behind the trash stack.
- The hydrant rumbles
- Menschenmassen sammeln sich.
- And the hydrant explodes, ending in the situation we know from the gameplay.
- Guy weicht ersten tropfen panisch aus. Sammelt mut für kampf.
## art
- [x] comicbook / story board
  - [x] sketches first -> oli zeigen -> sounds unten festlegen
  - [x] final version
- [ ] animationen fürs story board
## programming
- [x] arts einbauen
- [x] kamera von bild zu bild
- [x] fading comic -> tutorial -> comic -> gameplay (mit countdown)
- [x] 3x irgendow in comic clicken -> sofort zm nächsten screen
## sounds & music (8bit?)
- [ ] wait for sketeches above...
- [ ] 2-3 music tracks

**Comment by ghost** [comment]
Forget Programming, you should become a "Copywriter" :) good for what we need.

**Comment by ghost** [comment]
ich hab das Spiel an meine Frau gezeigt. Sie ist ziemlich begeistert :)

was eigentlich fehlt ist irgendwann eine erklärung "warum ist man da? oder was muss man eigentlich machen?"  (mehr tiefe in der Geschichte...)

wenn ich nachdenke, finde ich das ganz richtig... sollte man was vor dem "Buttons" tutorial (oder gerade nach...) was komunizieren: was oder warum ist man da...

Lösung wäre was, wie beim standard pixel gaming, mit eine Blase und 2 lines oder so... (und villeicht eine mini anim...)

in der richtung...
![screen shot 2014-09-09 at 20 54 21](https://cloud.githubusercontent.com/assets/7753856/4207086/c5150ee2-3852-11e4-8b8f-37966c41db24.png)

deine Meinung?

**Comment by Waog** [comment]
Ich dachte wir machen sonen kleinen "animatic" wie in #47 besprochen!? Ich bin ken Freund von texten. Ich würde sowas lieber über visuals ausdrücken (das gilt übrigens auch für die beschrifteten Buttons).

**Comment by ghost** [comment]
hmm...
ich glaube bis jetzt haben wir ohne viel Text es ziemlich gut hingekriegt... leider ist unser thema 
"Typ halb nackt mit Tuch", "Strasse", "Hydrant spritzt wasser",etc... nicht sehr deutlich (was man im spiel machen muss... oder verstehen muss) 
z.B. RAMBO vs. USSR soldaten, weiss man sofort das man die alle killen muss weil Sie sehr sehr sehr Böse sind, und jeder weiss das die USA das Land des frieden und happyness ist.

bin auch kein fan von 50 Texte Seilen bevor man spielen muss (auch nicht im Spiel :), aber eine kleine "Punchline" wäre nicht luxus am anfang des gameplay... (ist sogar wichtig)

wegen animatic, finde ich beide (animatic und "Punchline") nicht unbedingt inkompatible... folge #47

**Comment by ghost** [comment]
![comic_towel](https://cloud.githubusercontent.com/assets/7753856/5036155/a5772df0-6b7d-11e4-941b-d20b7b64d74d.jpg)

YO!
hab den ruff sccribble für das comic so gemacht (wird eine mischung zwischen "DC comics" und funny "manga")
die vignetten werden wahrscheinlich nicht100% so aber ungf.
werde versuchen mich am Wochenende das zu Umsetzen... alos, falls du was was dich irritiert, behalt es für dich! (joke...) sag bescheid... (muss aber wirklich kratzen, hahah)

**Comment by Waog** [comment]
ok, habe einige kritikpunkte und anmerkungen:

**erste seite:**
- im zweiten bild sollte deutlich gezeigt werden, dass er seine unterhose grade in der hand hat. Der spieler hat sonst kaum eine chance das zu kapieren, bevor der guy sie verliert.
- unten links, wäre es cool, wenn der guy nicht _komplett_ unter strom steht, sondern nur sein arm. Später kommen nämlich hunderte von diesen kleinen dekorativen tropfen, die ständig de guy treffen, aber nichts ausrichten (coolen funken-partikel-effekt einbauen?). Deswegen wäre komisch, wenn mini-tropfen plötzlich so krasse auswirkungen haben
- das heulende gesicht passt nicht zum rest (davor geschockt, dahinter tot-ernst). in dem kreis wäre glaube ich cooler, wenn eine nahaufnahme zu sehen wäre, wie die unterhose aus der hand fällt. Er könnte sie dann im schock-bild sogar noch in der hand haben.

**zweite seite:**
- warum sprintet er im ersten bild? Das würde sinn machen, nachdem die hose aus dem fenster geflogen ist, vorher nicht so richtig.
- die manga-artige renn-animation in der mitte ist zwar cool, aber passt überhaupt nicht zum restlichen artstyle. dort würde stattdessen das frontale sprint-bild passen.
- die erstes gameplay-bild unten links. warum schleicht er plötzlich, während er vorher ständig rennt?

**insgesamt:**
- ich finde den manga-style nicht gut, weil wir eh schon zwei art-styles gemischt haben. Noch einen dritten stil reinzumischen finde ich nicht gut. das ist "stillos".
- Du hast den zweiten stichpunkt vom storyboard ignoriert. Der Spieler weiß und versteht am ende also nicht, dass er telekinetische kräfte hat.

**Comment by ghost** [comment]
![comic_towel2](https://cloud.githubusercontent.com/assets/7753856/5053696/4520849e-6c4d-11e4-99dd-4b87588233cb.jpg)

1.
 bild 2, ja haste recht, deshalb meinte ich das die Vignetten nicht 100pro. finale sind. Fnal render muss deutlicher gezeigt werden.
2.
ich finde nicht richt nur den Arm oder ein Teil zu machen, grafisch ist viel besser das ganze zu Zeigen, da versteht man sofort: "WASSER ist nicht jut für ihm", und dazu ist es im Spiel schon gelernt (Übertreiben ist für comics wichtig, und am Ende unser Spiel hat nicht sehr viel mit realismus zu tun.... :)
3.
ich finde die ordnung gut so: 3.1 die Unterhose fliegt richtung Fenster > 3.2 er sihet es aus mit schmerzen und leid > 3.3 aber wie ein echter Superhero versucht hinter zu rennen > 3.4 leider es ist zu spät, es ist schon fast durch > 3.5 (close up mongo face! es kann nicht gerettet werden) > 3.6 versucht trotzdem die Unterhose zu catchen....
4. Eine Treppe wäre ganz gut hier...
5.1 er ist jetzt draussen, ich kenne nicht so viel Leute die Stolz mit nem Handtuch und halb nackt auf der Strasse stehen :) deshalb langsam...
5.2 Er benutzt telekinetisch und die Hose heb sich hoch aber die Hydrante ist erwischt... (gleichzeitig kommen mehr Leute....)
5.3 die Hose fält hinter die Müllsäcke und er merkt das wat nicht stimmt (immer mehr Leute...)
6 VIVA la BAAAAM! 

insgesamt:
Wir haben sehr viel zu erzählen in wenige Vignette, deshalb finde ich alles ziemlich gut gelöst (storytelling alle Punkte sind da)... und ist sehr lustig.

Kennste "Teen titan" (Cartoon network) oder älter "Dr Slump"(80's)? obwohl den stlye nicht ganz manga ist, manchmal gibt es unterbrächung in manga style, und ist der Hammer lustig. Ich stehe auf sowas weil es einfach GEILO funny ist (und unser Spiel ih nicht wirklich der nächste "Last of Us" von naughty dog.... :)
"Stillos" nicht ganz, obwohl unser scenario ziemlich gut in der Richtung geht ("Towel defence", ein Typ fight against eine Hydrant... etc... )also für mich is es nicht richtig ein guter argument gegen drei "manga style" vignette...

Ich hab leider nicht so viel Zeit für Privat sachen, arbeit macht stress... ahahaah 
Muss am Wochenende auch arbeiten...

**Comment by Waog** [comment]
mach dir kein stress, arbeit geht vor. das hier ist freizeit und soll spaß machen.

also punkte 3.1. bis 3.x finde ich zu viel hin-und-her. erst 3.1, dann 3.6 und dann 3.7 wäre ausreichend. alles dazwischen finde ich mehr verwirrend als erklärend.

stattdessen wäre es gut, noch irgendwie den zweiten story-telling punkt unterzubringen: die telekinese.

also das mit dem dritten art-style ist am ende deine entscheidung, du bist artist. aber ich finde es wirkt oft unprofessionell und konzeptlos, wenn zu viele styles gemischt werden. Und im moment sehe ich keinen Grund für den Manga-style, außer deine persönliche Vorliebe dafür. Lustig kanns auch ohne Manga-style sein.

wenn du das ganze in HQ machst, dann denk dran, dass wir einige bilder später animieren wollen. Trenn also die ebenen entsprechend.

**Comment by ghost** [comment]
![comic2](https://cloud.githubusercontent.com/assets/7753856/5062327/e21c677a-6dbc-11e4-9a66-abd0bff32f08.jpg)
hab den Storyboard nochmal short bearbeitet. Will nicht mehr so viel Zeit dafür bringen, also falls du noch kkkkkkkkkleine Anmerkungen hast... :)

sonst wegen animationen, stimmt, wir hatten darüber besprochen. Ich glaube leider, dass es nicht sehr gut aussehen wird durch Programmierung.
Wenn es um kleinichkheiten geht wie ; Farben wechseln in eine Vignette (Beispiel auf 6: unter Strom, den BG hat unterschiedliche Farben), oder reduzierte "Paralaxe" (Vignette 13) oder noch vibrationen (Vign. 18) aber vielmehr wird es nicht gut aussehen...
also, (Grundsätzlich finde ich) sollten wir Spannung erzogen durch eine coole Musik (mit villeicht sounds...) aber Animation via Programmierung, bin nicht sehr begeistert... 
(leider muss ich an die Zeitung die sich dreht denken, und sieht nicht sehr gut aus...)

Optimal wäre dieses Teil via FLASH, oder Aftereffects...(dann könnte man unschärfe vignette einfügen, camera "steady cam" style, etc. im traveling einfügen...) und das in mpg4? SWF? exportieren... (welche art animation suport Construct2?)

**Comment by Waog** [comment]
ok, dann halt keine Telekinese. Den Rest finde ich jetzt gut so :)
Besonders gut finde ich, wie die hose jetzt hervorgehoben ist, dadurch dass sie als einziges Farbe hat. Wenn du Farbe hinzufügst, wäre geil, wenn die Hose weiterhin guten Kontrast hast.

Für **Bild-Animationen** habe ich noch ein paar Ideen. Wir müssen nicht alle davon einbauen, weil es nicht so cool ist, wenn jedes bild animiert ist, aber potentiell könnten wir auch noch folgende Animationen einbauen:
- Die sternförmigen Streifen in 5 bewegen (wie in animes)
- den hintergrund in 15 bewegen (wie in animes, z.B. wenn pokemon angreifen)
- In 11 die Unterhose animieren. Vermultlich sieht es besser aus, wenn sie nicht flüssig fliegt, wie im Lose-Screen, sondern einfach gefaded wird. Also an Position 1 ausblenden und an Position 2 einblenden. Finde ich stelbst nicht so gut, weil auch animierte Comics so funktionieren sollten, dass man jedes Bild ewig angucken kann. Wenn die unterhose sich bewegt, sieht man die animation aber nur am anfang.
- In 12 die Hände und Füße abwechselnd ein- und ausblenden.
- In 19 die Streifen vom Wasserstrahl animieren (2 wechselnde Bilder sollten reichen)
- Ich verstehe nicht wie du dir die paralaxe in 13 vorstellst.

**Sounds und Musik**
Stimme nur halb zu. Sounds und Musik werden bei ca. 50% unserer Spieler ausgeschaltet sein. Daher muss das Spiel auch ohne Sounds und Musik gut wirken und verständlich sein. Sounds und Musik sind für mich nur ein schönes Extra, aber keine Kernfunktionalität.

**Animations-Formate**
Ich habe mich damit noch nicht beschäftigt, aber ich vermute, dass in HTML5 gar kein Animations-Typ ordentlich funktioniert. Das einzige was sicher funktioniert sind selbst animierte Bilder und Spritesheets, wie wir sie schon benutzen. Effekte wie Unschärfe sind zu inkompatibel. Die gehen  z.B. nur auf Android, aber nicht auf iOS.

Die Zeitungs-Animation wollten wir auch nochmal zusammen anpassen. Ich sehe Animation via Programmierung nicht so problematisch wie du. Ich weiß nicht genau was du mit "steady cam" meinst. Aber ich denke ich bekomme da was brauchbares programmiert, sowohl für die Kamera als auch für die Bild-Animationen.

**Comment by ghost** [comment]
![storyboard 2](https://cloud.githubusercontent.com/assets/7753856/5221965/bbb89b38-7688-11e4-9e53-9ecd83c765e4.jpg)
soweit sieht es so aus... (14, 16 und 17 sind nicht fertig...) ich überlege noch ob wir das einfach so dastellen oder wie ein offene Comic (Seiten offen und liegt auf holz oder so was...)

wegen animation, finde ich das ganze nicht so gut. Wir werden (wahrscheinlich) keine vernunftige bekommen die richtig gut aussehen... also lieber die Zeit sparen und weiter machen (gibt genug noch zu tun, haaha)

Sound und Musik: stimme auch jetzt nur halb von dein hlab, ha ha ha...hohohoho...( lustig) 
für eine Intro finde ich ziemlich wichtig... aber das ist ein anderes topic...

**Comment by ghost** [comment]
![storyboard](https://cloud.githubusercontent.com/assets/7753856/5235890/9baf4fc0-7819-11e4-826d-0bf12a2fb7da.jpg)
also, ich würde es so lassen (wenn es für dich gut ist...)
für die Animation, hätte ich eine Alternativ:
wir Animiren nur die Onomatopeia (Sie bewegen sich leicht und werden ein und aus-geblendet...)

wäre ganz gut wenn du mir sag welche göße du brauchst für das Finale Dokkument.
ist es besser ein Grosses, oder mehere kleine? dann kann ih das im Drop box legen....

**Comment by Waog** [comment]
**Größe:** keine Ahnung. Schicks mir erstmal ein Bild in voller Größe. Ich muss ausprobieren was da klappt.

**Onomatopeia:** ich glaube der blur-effekt sieht doof aus zusammen mit automatischen Animationen. und ich finde den auch sonst nicht so geil. Ich würde sagen, lass das blur weg und dann animieren wir die. Denk dran, dass ich die dazu einzeln brauche und dass sie nicht mehr im Hintergrund hängen dürfen.

**weitere Animationen:** Also wenn wir am Ende noch Zeit haben könnten wir hier richtig geile Sachen animieren. Aber du hast recht, hat erstmal keine hohe Priorität. Trotzdem ein paar Sachen die du mir jetzt schon separat schicken könntest, damit ich mal probieren kann die zu animieren, wenn es für dich nicht zu viel arbeit macht.
- Bild 4: Glas, Hand und Hintergrund als 3 Bilder. Dann kann ich hier sonen parallax oder zoom-effekt versuchen.
- Bild 5: Die schwarzen streifen separat, die kann ich dann so flimmern lassen.
- Bild 7: den Schweißtropfen auf der stirn separat. Lass ich dann so auftauchen wie in animes.
- Bild 18: Den Hydran und die verschwommenen Hydranten-Umrisse separat. Ich kann mal versuchen den zittern zu lassen. Aber das sieht glaub ich kacke aus.

**Sonstiges:**
- Schick mir mal zusätzlich zur zerstückelten Version auch eine Verison, in der alle Onomatopeia und sonstigen Animationen fest drin sind.
- Der Text oben links muss weg. Wieder das Übersetzungs-Problem. Und selbst wenn man englisch kann, hilft es kein bisschen beim Verständnis des Comics.
- Wir brauchen noch irgend einen Rand drumherum. Wir haben viele Bilder im Hochformat und Displays mit verschiedenen Größen. Das heißt man wird oft den Rand vom Comic-Heft sehen. Vielleicht einfach eine Tischplatte worauf der Comic liegt?

**Comment by ghost** [comment]
Onomatopeia: mit dem Blur und Animation finde ik och.
weitere Animationen: jep, mache ich
Sonstiges: wie noch immer  (Simple Texts vs Nothing)..."Übersetzungs-Problem" ist für mich nicht ein guten Argument.("Da wir nirgendwo Text im Comic haben, braucht man es auch nicht hier" macht für mich mehr Sinn... :)
Yep, ich wersuche ein Holztexture runter zu packen...

Ich versuche das für Morgen oder Mittwoch im Drop zu legen...
wie ist es Zeitlich für dich? da es ein grosser topic ist, wann hättest du Zeit dafür?
auf meine Seite, hab ich noch genug "grafik tasks" todos und mache einfach weiter...

**Comment by Waog** [comment]
Bei mein Terminplan ist jetzt noch bis 20.12. total dicht und ich habe bis dahin vorraussichtlich keine Zeit.
Aber ab 20. habe ich ein paar Wochen frei (minus Weihnachten und Silvester). Ich will in der Zeit so viel wie möglich fertig machen. Also alles was bis dahin an Grafiken und Tasks verfügbar ist baue ich dann auch ein.

**Comment by ghost** [comment]
Hab erstmal den "Top Table" so in drop gelegt, plus ein vierer "Ausgeschnitten in 4 Stück, mit überlappung...)
werde Morgen und Sonntag mit die anderen to dos weiter machen...

![storyboard_toptable_final_72dpi](https://cloud.githubusercontent.com/assets/7753856/5513411/cd717f7c-87f2-11e4-9067-0710f61aaf63.jpg)

**Comment by Waog** [comment]
Ich glaube die sind viel zu groß und viel zu gut aufgelöst. Aber ich probiere es erstmal damit.

**Comment by Waog** [comment]
intro-(replay-)button fürs main menu fehlt noch.

**Comment by Waog** [comment]
Habe den Comic jetzt eingebaut.... erstmal mit schlechter Auflösung. Für die volle Auflösung muss ich mir noch einen Trick einfallen lassen, weil viele Geräte keine so großen Bilder unterstützen.

Der Wechsel Comic -> Gameplay-Tutorial -> Comic -> Gameplay ist auch noch nicht eingebaut. weil dazu erst #73 fertig gemacht werden muss.

**Comment by Waog** [comment]
Waiting for #73

**Comment by Waog** [comment]
eingebaut.... erstmal nur mit Low Quality Story Book... aber alles geht erstmal :D
