### ISSUE TITLE
Browser Autosize

### ISSUE THREAD

**Issue by ghost** [Waog/towelGuy#54]
Wir haben zwei schwarze Balken (links und rechts) kann man ein art "autosize" im Browser einfügen?

**Comment by Waog** [comment]
Habe einen artikel gefunden wie es in construct geht (https://www.scirra.com/tutorials/73/supporting-multiple-screen-sizes/page-1).

Wenn alles so klappt wie beschrieben, dann müsste autosize klappen.

**Comment by Waog** [comment]
habe auto resize eingebaut.

**Comment by ghost** [comment]
:+1:
