### ISSUE TITLE
Game Logo

### ISSUE THREAD

**Issue by ghost** [Waog/towelGuy#55]
sieht erstmal nicht so wichtig aus, ist doch aber totzdem :)

**Comment by ghost** [comment]
Beispiele:
![262746](https://cloud.githubusercontent.com/assets/7753856/3326922/7a127bf2-f7a5-11e3-8bcc-99ae5b1aabbf.jpg)
![game-logoscan-you-name-the-video-games-by-their-logos-silhouettes--quiz-by-tmkztamp](https://cloud.githubusercontent.com/assets/7753856/3326932/91f0b158-f7a5-11e3-88b9-3d5099f04bc7.jpg)

**Comment by Waog** [comment]
Es gibt bereits einen Issue zu dem Thema, siehe #22
