### ISSUE TITLE
Themen beim Treffen

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#56]
Wenn wir uns treffen müssen einige Topics gemeinsam bearbeitet werden. Hier können wir die hinschreiben, damit wir nix vergessen.

**Comment by Waog** [comment]
1. alle Partikel nochmal zusammen angucken bearbeiten.
2. flugzeug: horizontal vs, gerade

**Comment by ghost** [comment]
- timing Animation (Lose, Win)

**Comment by Waog** [comment]
- positionierung der elemente im hauptmenü.
