### ISSUE TITLE
Preload Assets

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#58]
When screen is entered for the first time, the loading times are too long. this is propaply assets are fetched with lazy loading.

figure out how preloading works and implement it.

**Comment by Waog** [comment]
alternatively use loading screens between layouts:
https://www.scirra.com/tutorials/318/how-to-use-loader-layouts-to-make-custom-loading-screens

**Comment by Waog** [comment]
Waiting for an answer here:
https://www.scirra.com/forum/viewtopic.php?f=146&t=76836&p=812921#p812921

**Comment by Waog** [comment]
Memo @Waog: Check out this:
https://www.scirra.com/forum/fade-in-to-another-layout_t65360

**Comment by Waog** [comment]
@nostoner We can have an individual load-screen instead of constructs predefined _gears + bar_.
Would you like to make an individual graphic?
The graphics sould be very small, since the loading screen should appear as fast as possible. So no backgrounds or good resolutions.

For example we show a hydrant and use a fontain as loading bar.
Or to have a horozontal bar, we could use the guy and a lightning-beam as loading bar.

In any case, the graphics shouln't be in the resolution of the screen, but maybe 2-3 graphics of up to 50x50px. I can scale them programatically or display multiple instances of them, if nesseccary. For you that would mean, to design assets, which still look good, if scalled to bigger size.

What do you think?

**Comment by ghost** [comment]
yep cool...
will try your both ideas.

it's ok if (exemple: guy) we have a small animated gif (for the guy) and a separate element for the loading bar? not too big?

**Comment by Waog** [comment]
- seperated graphics may be ok (i dont really know yet)
- animated graphics are propably to much... if neccessary anyway, restrict yourself to a maximum of 3 frames.

And don't invest to much time into this issue. If i understand it correct, this screen will only be shown when:
1. the game is played online (i.e. in a browser, not installed on a mobile) AND
2. the game is loaded for the first time (after that the browser caches the game and the next time the website is visited, there's no need to load the game again).

**Comment by ghost** [comment]
ok!

**Comment by ghost** [comment]
we can use this:
-var1
![preloader_hydrant_var1](https://cloud.githubusercontent.com/assets/7753856/3803515/711172fc-1c1b-11e4-96e5-90b6b7f01df0.gif)
it's in mood of the game (but with 7 frames) and the loading bar works like the "construct2" one.

-var2
alternative could be just the water hydrant without animation (but pixel art style)

-var3
or this one illustrated (from the key visual) but also static...
![screen shot 2014-08-04 at 23 06 16](https://cloud.githubusercontent.com/assets/7753856/3803556/ee4fe42e-1c1b-11e4-9cf8-65fc308387f1.png)

question:
-it's probably possible to chage the BG color,no? (other than black, hexadecimal nr.?)
-what kind of visual you need for the loading banner? just a square colored png? (and programming scale it or so?)

what do you think? (i like the first one)

**Comment by Waog** [comment]
- I like the third one most. Maybe with only half the resolution. We decided for the epic main menu, to generate a _wow_-effect when the app is started. So starting with the pixel art would eliminate this effect somehow.
- I don't like the colors of the loading bar. I'm not sure if i can change them. But they look like chosen from the 16 colors palette of windows 3.1 :smile:  
- Changing the background color programmatically is possible. At least I hope so...
- Yes just give me a semitransparent png and tell me, what size I shall scale it to.

**Comment by ghost** [comment]
ok good for the third.

**Comment by ghost** [comment]
the visual is in Drop box (Preloader_visual.png)

but you don't need the small blue banner with the outline right?
