### ISSUE TITLE
Loading visuals between layouts.

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#59]
A "loading" graphic or animation between each layout (e.g. between main menu and gameplay, or between main menu and credits) may be required. Something with the symbolic meaning of an hourglass.

Maybe this issue will not be neccessary, if we can enforce loading of **all** assets in the load screen. Wait for result of #58

**Comment by Waog** [comment]
I still have no anwser on how to prevent the long loading times between layouts. So I'll propably implement some kind of fading effect between the layouts.

Between the layouts, I don't have any kind of "loading progress" available.
Instead I can _tear down_ the first screen and _set up_ the next screen.

For example in _plants vs zombies_ they do it like this:
- to tear down a layout, they fade in a flower and background to cover the old layout. The flower grows petals: [Youtube](https://www.youtube.com/watch?v=Z74gqIE5NPM)
- the next layout starts with the fully grown flower and background covering the new layout. Then the flowers petals are ripped out. Flower and background are faded out, until the new layout is visible.

So we either need:
- a static visual which covers the whole screen, which is faded in and out between the scenes, or
- some very short _tear down_ and a _set up_ animations, which cover the whole screen.

Between the layouts, there are no restrictions to the size of the picture or number of frames. It's up to you, how complex you want it.

**Comment by ghost** [comment]
ok... lets take some times to think about it....

**Comment by Waog** [comment]
I'll experiment a little bit with it. Maybe we can use random animations:
- One time an animated car is faded in and out
- next time a running guy is faded in and out
- next time the photographing people are faded in and out...

the background would alsways be black or in one other color.

**Comment by ghost** [comment]
yep cool...

**Comment by Waog** [comment]
Ok, I integrated a first version of fading now. Construct isn't as good as required here.

The problem when fading is, that the fade-animation gets stuck for one moment until it continues playing (try the latest version, to see what i mean). This can't be prevented.

So we need fading-animations that don't require continuous playing. The animations need some frame at which they can be stopped without bothering the user. Any ideas?
- Maybe the guy starting to watch his clock... pause ... then he looks up again?
- or simply non-animated fading-pictures?

**Comment by ghost** [comment]
-it stuck because of the "fade" tool? if it was a straight cut (but with animation in) , does it changes somethig?

-do you think it's possible to avoid some of these fading/loading? (as you say on the top, and include some assets in the main loading). Splitting it: some in fading and some loading at the beggining?
because for example:
between MAIN MENU and GAME PLAY, it's cool, 
but
between LOSE (game play) and LOSE FINAL (animation with newspaper) it's not so great to see something between both... the best will be a short cut (without loading time).

-For my taste, whether  the fade in/out takes to long or we need just straight cuts (will be much better)... but what you did was just for test right?

**Comment by Waog** [comment]
- _it stuck because of the "fade" tool? if it was a straight cut (but with animation in) , does it changes somethig?_ ... sry, i don't get the question. It stucks, because construct is loading the assets when switching to a layout for te first time.
- avoiding some of the loading screens could be possible. I have to experiment with that further.
- yes, the fading time is set up too long, because i forgot to shorten it again after experimenting. Some more direct Fading could also be possible, but is not THAT easy. I'll do some more experiments.

**Comment by ghost** [comment]
if it wasn't a "fade" action, would it make the stuck anyway?  like a straight cut can avoid it? 
anyway, it's not thaaaat bad... 

have fun with experiments Viktor Frankenstein... :) (joke!)

**Comment by Waog** [comment]
sry, i don't understand the question.

**Comment by ghost** [comment]
forget it :)

**Comment by ghost** [comment]
was hältest du davon als loading asset:

![floppy_disc](https://cloud.githubusercontent.com/assets/7753856/4178996/af4bd448-36b2-11e4-8eef-5dfc18c6f0ca.gif)

**Comment by Waog** [comment]
finde animationen aus dem spiel schöner.

**Comment by ghost** [comment]
hmm... 
mit einem floppy disc, finde ich persönlich besser.
man versteht sofort das man auf was warten muss. Dazu, bin ich nicht sehr fan den run cycle wieder zu benutzen... ist mir ein bisschen "der grafiker war zu faul was anderes zu bauen..."
und das floppy disk ist gelio mit unsere key colors!

villeicht ist das Spinning wheel nicht ganz coolio?

**Comment by Waog** [comment]
ok, dann meinetwegen die floppy... aber dann lass die animationen weg... ich fade das nur rein und raus. Ist eh besser, wenn wir was statisches haben.

**Comment by ghost** [comment]
ok cool...
ohne was annimiert ist langweilig ne? ein balken "Knight Rider" style zusätzlich vom floppy wäre gut...
ich probiere einfach nochmal...

**Comment by Waog** [comment]
ohne animation ist das einzige was funktioniert... weil die animation immer an einer stelle stehen bleiben wird.

**Comment by ghost** [comment]
ich habe das so gelöst.
liegt in drop box; einmal: 
- Background
- floppy disc
- busy

ich finde besser mit Animation (trotz stuck) mach was irgendwie cooler, und es ist gelernt dass man warten muss...

![loading](https://cloud.githubusercontent.com/assets/7753856/4206481/af1da01a-384b-11e4-8d38-4d924e2bb189.gif)

**Comment by Waog** [comment]
kk, baue ich so ein.

**Comment by Waog** [comment]
done
