### ISSUE TITLE
High Score

### ISSUE THREAD

**Issue by ghost** [Waog/towelGuy#60]
beim score (ist gar nicht gelayout, aber ich finde jut wenn mann durch:"time" und "number of hits" im ranking ist... ist es möglich? wat denkste?
![screen shot 2014-08-09 at 00 13 31](https://cloud.githubusercontent.com/assets/7753856/3863466/6930785e-1f49-11e4-8a3f-835f5edb5aa9.png)

**Comment by Waog** [comment]
Finde ich gut, machen wir.
- Beim High-Score hätte ich gerne wenig action und passanten, um so ein Gefühl zu vermitteln von *hier ist schon lange nix mehr passiert und alles ist total langweilig. Geh lieber das spiel spielen!"
- Als Animationen (zusätzlich zu den scheißenden Tauben) vielleicht:
  - eine Oma die da steht/sitzt und tauben immer Körner hinwirft
  - Ein Stohballen der da langrollt weil nix los ist.
  - Irgendwas hinten in der Stadt, was noch mehr von der Statue ablenkt und einen hinweis gibt warum die Statue keinen mehr interessiert. Z.B. blau-licht oder hier vielleicht godzilla oder so?

**Comment by ghost** [comment]
yep... villeicht kann man sogar Grünes Zeug auf der Statue wachsen lassen... und der glanz reduzieren... :)

**Comment by Waog** [comment]
:+1:

**Comment by ghost** [comment]
![bg_game_small-sze_72dpi](https://cloud.githubusercontent.com/assets/7753856/3918738/d4404c16-239d-11e4-9dfc-2cc3dc90fa1b.gif)

Einzeln Tauben und Oma muss ich dir Separat vorbereit, ist viel besser...

**Comment by Waog** [comment]
Das erkennt man wieder nicht auf dem Handy... zoome mal raus.

**Comment by ghost** [comment]
finde Grenzwertig aber OK... folge #49

**Comment by Waog** [comment]
HighScores funktionieren jetzt. Das war ein richtig kranker akt. Construct hat hier gleich zwei bugs und einige fehlende funktionalität, so dass ich mehrere workarounds zusammenhacken musste. Änderungen hieran sind echt zeitaufwändig und ich würde gerne nur noch das layout anpassen.

Anzahl der Treffer wird nicht angezeigt... würde ich auch sehr niedrig priorisieren.
