### ISSUE TITLE
Automaischen Zoom probieren

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#61]

**Comment by ghost** [comment]
von  #49 "Und dann sogar noch mitten im Spielgeschehen zoomen zu müssen wäre das letzte."
mein Gendank ist nicht das man es "machen muss" sondern bei side, wenn man das will, (um denhero besser sehen zu können, details im Spiel erkennen...) "machen kann"
Finde ein vichtiger Punkt da ein Samrtfone Bildschirm so klein ist.
