### ISSUE TITLE
Sound Switches

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#62]
We need buttons to turn off and on the music and sound.

**Comment by ghost** [comment]
yep mache ich...

**Comment by Waog** [comment]
habe es jetzt mit platzhaltern eingebaut...

**Comment by ghost** [comment]
hab die beide wie pause button gemacht (liegt in DB)

![button_music_small](https://cloud.githubusercontent.com/assets/7753856/4178903/53b00ff0-36ad-11e4-9f49-c6a6c9f13b39.png)
button music
![button_sound_small](https://cloud.githubusercontent.com/assets/7753856/4178904/53b97734-36ad-11e4-8dc3-c243f9941124.png)
button sound

**Comment by Waog** [comment]
Ok, hab sie eingebaut
