### ISSUE TITLE
Tool Menu (Pause, Sound & Music)

### ISSUE THREAD

**Issue by ghost** [Waog/towelGuy#63]

**Comment by ghost** [comment]
Momentan wirken die Buttons: Pause, Sound und Music so verteilt, dass es je nach Hinterground (und angehörige andere Buttons) sehr unruhig.
![tool menu](https://cloud.githubusercontent.com/assets/7753856/4184456/30c05bba-374a-11e4-9880-a7dfbe8c2dc3.png)

ich finde ganz gut wenn wir die Möglichkheit ein art "drop down menu" hätten, anstatt die drei Buttons.

![screen shot 2014-09-08 at 13 21 08](https://cloud.githubusercontent.com/assets/7753856/4184481/7fab2502-374a-11e4-9286-3d4b262c11a4.png)
![screen shot 2014-09-08 at 13 21 21](https://cloud.githubusercontent.com/assets/7753856/4184483/842ab8b8-374a-11e4-8e87-fdc3da2e4da4.png)

und soweit man drauf roll over, wäre auch ein art "Game freeze" eingefügt, bis man es roll out.

was denkste?

**Comment by Waog** [comment]
- dropdown menü finde ich zu umständlich. 2 interaktionen statt eine. wo ist der vorteil?
- Sonst gebe ich dir recht.
  - Wie die Buttons positioniert werden würde ich gern im treffen klären. Weil es immer so 5 minuten arbeit macht einen button anders zu platzieren. Wir können die auch in jeder szene anders platzieren.
  - Dass die Buttons manchmal verdeckt sind, muss ich als eine der letzten dinge anpassen. Hier ist construct etwas kacke... wobei ich habe grade eine idee wie man es besser machen kann. Memo an oli: _buttons nicht global machen, sondern eine instanz pro szene._

**Comment by ghost** [comment]
ich hab nochmal alle screen angeschaut und denke trotzdem das ein "drop down menu" ist die beste Lösung 

"2 interaktionen statt eine. wo ist der vorteil?" ist eigentlich nich ganz richtig... ich stelle mir  das so vor:
aufs Menu haben wir die drei Buttons: 
Music - Sound - Pause
soweit mal drauf "rollover" (oder click, ist tbd) es freeze das gameplay (weil man natürlich kein Lust hat das es weiter spielt, wenn man auf das "Menu Tool" konzentriert ist.) wenn man nich mehr drauf ist... geht alles wieder weiter (mit gewünschte aktion: sound off, music on, etc...)
wir können trotzdem anbieten das die taste "P" für pause auch funktionnert.

wie gesagt, wenn ich alle screen anschaue, ist mir leider alles zu unruhig. 
z.B.
- INTRO: 5 Knöpfe mit unterschiedliche wert ist mir zu viel.
- Zeitchrift spinning: finde eigentlich nicht gut das Sie aufs Visual Integriert sind.
- CREDITS: passt auch nicht aufs Visual.
  etc.
  also, "menu tool" wäre ein guter Kompromiss (wenn man sich alle steps des Spieles anschaut)

wenn du den Weihnachtsman wäre, würde ich dir beten... "ein TOOL MENUUUUU bitte, bitte, bitte!!!!" :)

was denskte? ("ein TOOL MENU, oh ja, gerne! ")  :)

**Comment by Waog** [comment]
nee, bin immernoch nicht überzeugt... rollover gibts auf dem touchscreen nicht. da gibts nur klick oder nicht-klick.

Aber wir können einen großteil der buttons ausblenden, da stimme ich zu.
Im Gameplay könnten sie buttons nur im pause-menü sein. In Zeitung und Win-/Lose-/HighScore-Scren braucht man die auch nicht unbedingt. Im Hauptmenü finde ich die ok... aber würde sie anders anordnen.

**Comment by ghost** [comment]
ok... aber d.h. Win-/Lose-/HighScore-Screen kann ich nicht den ton an und aus machen? es mach nicht so richtig Sinn,  diese Option sollte durch das spiel benutztbar sein.

"Im Gameplay könnten sie buttons nur im pause-menü sein" und warum können wir das Pause button nicht überall anbieten? wäre eine gute Lösung... und dann hätten wir drin wie du sagt, die zwei SOUND/MUSIC buttons.

**Comment by Waog** [comment]
weil ich es aus keinem spiel kenne, dass man während "film-sequenzen" ein vollständiges user-interface zur verfügung hat.
