### ISSUE TITLE
Pause Menu

### ISSUE THREAD

**Issue by ghost** [Waog/towelGuy#64]
Programm:

Pause menu bauen

Grafik:
-button sound high res (on-off)
-button music "
-button RETRY "
-button "RETURN MENU" "

-tutorial Bild (zusammen Fassung:
1.controls space
2. controls arrow
3. spiel Ziel ("ex. destroy blah blha..) 
simple gifs visuals
4. Tropfen sind böse... 
simple gif visual

**Comment by ghost** [comment]
Buttons Highres liegen in drop...

**Comment by Waog** [comment]
:+1:

**Comment by Waog** [comment]
integrated the provided buttons.
Still missing graphics of the pause-menu-window itself, the button to open the pause menu (or do we use the normal "menu" button here?) and the return to main menu button.

**Comment by ghost** [comment]
Bin an die "Pause" Animation dran... Am besten liefere ich dir (wenn es fertig ist) ein kompletes animated gif.

![pause-animation](https://cloud.githubusercontent.com/assets/7753856/6136846/8ef3dc94-b174-11e4-8d09-62eb8880096b.gif)

muss noch:
-bewegung zwichen tropfen
-attack hydrant
inzinieren...

![screen shot 2015-02-10 at 22 31 46](https://cloud.githubusercontent.com/assets/7753856/6136859/a627734e-b174-11e4-9972-a319d313e10c.png)
die Anim/Pause würde ich auf ein weiss (weich transparent) hintergrund packen... + buttons drauf.

**Comment by Waog** [comment]
ist das nicht viel zu klein um irgendwas zu erkennen? meinetwegen könnten die figuten locker 2-3 mal so groß sein

**Comment by nostoner** [comment]
hab das gesamtes grösser gemacht (ca. 2X) liegt in drop.
Gück mal ob du damit schon wat machen kannst. 
Später kann man die Animation verändern falls wat nicht geilo ausshiet oder neue ideen kommen...

![pause-animationx5](https://cloud.githubusercontent.com/assets/7753856/6156814/0f5f7258-b23d-11e4-896d-f2fe533e14a0.gif)

**Comment by Waog** [comment]
The graphics are still missing in dropbox.... we also need a menu-window/-frame, not only the buttons.

**Comment by ghost** [comment]
hmm, "Pause-Animationx5.gif" liegt in drop box.
was meinst du mit: "menu-window/-frame"?

**Comment by Waog** [comment]
Fenster: irgend ein "Hintergrund" auf dem die Buttons + Tutorial-gif angezeigt werden. Idealerweise mit einem kleinen x-Button oben rechts. 

Das alles einfach nur über dem Gameplay anzuzeigen sieht doof aus.

**Comment by ghost** [comment]
wenn wir sowas machen? 
finde nicht so schlecht...

BG ist unser violet (#7a0184) auf 40%

![screen shot 2015-03-01 at 16 53 07](https://cloud.githubusercontent.com/assets/7753856/6431560/87fe9730-c033-11e4-9513-7d2fb0bde2ed.png)

:warning: **currently in dropbox** :warning:

**Comment by Waog** [comment]
gefällt mir gar nicht.... sieht sehr unfertig und nach schlechtem prototyp aus.

**Comment by ghost** [comment]
"gefällt mir gar nicht...." hmm... deshalb bist du Programmierer ahahahah
das nennt man Bauhaus, schlicht und clean...

Witz gemacht, sowieso haben wir die drei Buttons oben Rechts (hatten wir gesagt, oder?)

Ich probiere mit nem Rahmen und sowas auf den "Tutorial gif", aber das "Transparent Violet" finde ich eine gute Lösung (meinetwegen, kann es auf weiss oder eine andere Farbe sein..)

**Comment by ghost** [comment]
ok, ich habe das in meine Weinhnachtstasche.

![screen shot 2015-03-02 at 21 48 15](https://cloud.githubusercontent.com/assets/7753856/6450349/78cee5cc-c127-11e4-8f71-f6fc460fbe74.png)

![screen shot 2015-03-02 at 21 51 28](https://cloud.githubusercontent.com/assets/7753856/6450340/6c67b00c-c127-11e4-9252-565520ee6747.png)

:warning: **required in dropbox** :warning: 

Frame (Pause_animation_Frame.png) findest du im Ordner 150227.
es gibt ein neues "Pause-Animation" gif: 
"Pause-Animationx5b" (5,1MB) oder "Pause-Animationx5c" (78 KB :)

**Comment by Waog** [comment]
nee, das mit oben rechts hatten wir glaube ich nicht gesagt... wir hatten eine ganz andere Anordnung. Eigentlich hatten wir ein richtiges Fenster und das Tutorial hat nur so 30% vom Fenster eingenommen... wie ein kleiner Bildschirm im Menü. Aber ich glaube die Grafiken sind zu klein, um sie noch weiter runter zu skalieren. Ich nehme jetzt erstmal das aus deiner Weihnachtstasche...

**Comment by ghost** [comment]
ja, nimmt doch allet aus deiner Weihnachtstasche... (aber die 200€ sind meine!)

wir haten doch jesagt dass die icons: "Sound - Music - Pause" oben rechts stehen (überall: Gameplay, intro,etc.) wenn nicht, lass uns es erstmal das so machen und können später immer verbessern.

**Comment by Waog** [comment]
ja, ich baue es erstmal so ein

**Comment by Waog** [comment]
die aktuellste version liegt noch nicht in dropbox...

**Comment by Waog** [comment]
ok, habs jetzt erstmal für die alten grafiken eingebaut.

**Comment by ghost** [comment]
sorry, verstehe nicht was gemacht würde... (und warum es wieder "Graphics" task ist)

**Comment by Waog** [comment]
es liegen noch veraltete grafiken in dropbox.... gucke mal die vorherigen kommentare an, habe dort einige mit "warning signs" editiert, ums nochmal deutlich zu machen.

**Comment by ghost** [comment]
"Pause-Animationx5c.gif" ist das richtige.

**Comment by Waog** [comment]
ah, I see, thx :)

**Comment by Waog** [comment]
okay, habs ausgetauscht.
