### ISSUE TITLE
Credits anpassen

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#66]
- [x] Avatar for https://www.discogs.com/es/artist/2166249-Rolemusic
- [x] Image/Name "Sound by sawsquarenoise"

**Comment by ghost** [comment]
![screen shot 2016-04-22 at 21 59 40](https://cloud.githubusercontent.com/assets/7753856/14753412/9fbdef10-08d5-11e6-97e9-bcc18fbf95a0.png)
in Dropbox > Credits

**Comment by Waog** [comment]
done
