### ISSUE TITLE
Animated Moon

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#67]
clouds or something?

**Comment by ghost** [comment]
war was wie so wat, was du mit dem Mond gemeint hast?

![fog2](https://cloud.githubusercontent.com/assets/7753856/4276798/99e36876-3d08-11e4-9e0a-40733e65632f.gif)

**Comment by Waog** [comment]
jo, jut.
sieht nur teils zu sprunghaft oder schnell aus. könnte am gif liegen.

**Comment by Waog** [comment]
- [ ] nochmal mit 3 mal so vielen frames probieren (animation langsamer)... wenn kacke -> einfach doch keine animation.
- [ ] sprung (loop) fixen

**Comment by ghost** [comment]
hab das geschaft. Da ich kein "gifs" mit alpha canal/transparenz machen kann, musste ich das ganze schnitt (viereck) rendern. ist es ein Problem für dich das Pixel genau dauf dem Background zu positionieren? sonst sihet es natürlich blöd aus... (und die anim ist 1MB groß...)

![credit_fog_anim](https://cloud.githubusercontent.com/assets/7753856/6492832/71498ede-c2b6-11e4-93f1-2e505c27c517.gif)

liegt trotzdem in drop.

**Comment by Waog** [comment]
1MB ist echt viel für mobile. Aber ich probiere es erstmal... Alternativ könntest du mir vllt auch einen Spritesheet mit alpha-channel geben, wenn Construct das kann...

**Comment by ghost** [comment]
YEP, also ich hab wat neuet.

ein PNG Streife als cache (muss nur 1 zu 1 gleich positionniert wie Himmel/nacht)
und ein PNG (die Nebel) die du animieren muss.
aber ist auf jedenfalls nicht 1MB :)

![screen shot 2015-03-07 at 17 49 22](https://cloud.githubusercontent.com/assets/7753856/6542194/5d434e28-c4f2-11e4-90b5-2b2d1b84bbf6.png)
![screen shot 2015-03-07 at 17 49 13](https://cloud.githubusercontent.com/assets/7753856/6542195/63107448-c4f2-11e4-8a86-139d28fdff03.png)

**Comment by Waog** [comment]
beim foreground fehlt der rechte rand und der linke ist auch zu kurz... der nebel wird immer wieder dahinter vorkommen...

**Comment by Waog** [comment]
der fog ist falsch skaliert

**Comment by Waog** [comment]
okay, habe die grafiken jetzt selbst in konstrukt gezeichnet und skaliert.... sieht ganz gut aus:
![image](https://cloud.githubusercontent.com/assets/5098472/7439132/8028765c-f071-11e4-9231-7a54de2d25dd.png)
