### ISSUE TITLE
Pixel-Buttons an HQ-Buttons angleichen

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#68]
- [x] pause button
- [x] intro button

**Comment by Waog** [comment]
überall HD buttons

**Comment by Waog** [comment]
denk auch an pause button

**Comment by Waog** [comment]
auch skip button fürs intro

**Comment by ghost** [comment]
"Pause" Button und "Skip" sind in drop...

**Comment by Waog** [comment]
Brauche noch den Intro-Button.

**Comment by ghost** [comment]
intro button? sollte kein sein...

**Comment by Waog** [comment]
doch fürs main menü

**Comment by ghost** [comment]
weiss ich nichtmehr wann er kommt aber ok.
liegt in drop (Buttons)

![button intro grey](https://cloud.githubusercontent.com/assets/7753856/6546441/f51358ee-c5b3-11e4-99e6-7608f9a40dea.png)

**Comment by Waog** [comment]
:+1:

**Comment by Waog** [comment]
eingebaut
