### ISSUE TITLE
Highscore design vorschlag

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#69]
Top 5.
- anzahl treffer/herzen darstellen oder nicht?... mal gucken was wie aussieht
- auch bedenken wie einzelner (1 high-score) dargestellt wird.
- wo soll der Menu-Button hin?

**Comment by ghost** [comment]
![screen shot 2014-09-15 at 19 16 45](https://cloud.githubusercontent.com/assets/7753856/4275365/1d02ecb6-3cfc-11e4-9db8-40775ea7835d.png)

finde nicht schlcht so... du?

menu muss #68

**Comment by Waog** [comment]
jo, ist ganz geil. n paar kleinigkeiten noch:
- 1. text vermeiden (~~hero~~), icon statt dessen... mach ne goldene siegertreppe oder nen pokal oder so.
- ~~2. nummern vor den namen wären geil (1. bis 5. oder 1st bis 5th)~~
- 3. die position vom menu-button gefällt mir nicht, wirkt zu assymetrisch.... ein quadratischer button mit icon wäre hier richtig geil :stuck_out_tongue_closed_eyes:

**Comment by ghost** [comment]
![screen shot 2014-10-16 at 20 16 15](https://cloud.githubusercontent.com/assets/7753856/4668596/7f7d0ae8-5566-11e4-8911-bd5df61d3f3d.png)

Tabelle HIGH SCORE WIN liegt im Drop Box:
141016 > highscore plate

**Comment by Waog** [comment]
done :)
