### ISSUE TITLE
tutorial keyboard

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#73]
## Art:
- finger/hand visual testen
- Unterhose auf dem hydranten
  - kommt angeflogen-animation
  - liegt unberüht rum (weht lahm im wind) -animation
  - unter einfluss von 1x telekinese (kurzes zucken richtung spieler, dann zurück zum hydrant) - animation
  - unter einfluss von 5x telekinese (fliegen zum spieler) - animation
- hydrantenkopf wackel/vibrier-animation
- guy in staubstauger-position (copperfield) mit blitz - animation
- weniger menschen als im gameplay
  - ein passant mit walk-cycle, der dann stehenbleibt und jubelt

wenn fertig, weiter #74 bearbeiten...
## Programming
- neue graphiken (sihe oben) einbauen
- je 1sekunde in summe pro richtung -> yeah-sound -> next tutorial-step
- 1x space -> yeah-sound -> 2s wait -> next tutorial-step
- 5x space in 3 sekunden -> yeah-sound -> back to comic (siehe TODO)
- passanten mit zufalls-größe einbauen.
## Sounds
- Yeah-Sound (oder alternative)
- chillige mucke
- auto/passanten
- sanfter/erfolgreicher telekinese-sound

**Comment by ghost** [comment]
Hi there,

also hab in dropbox(150227): 
- underwear_flying : ist ein gif mit loop von drei bilder. dann muss du ein Pfad geben ür die animation druch den Bildschirm)
- underwear_hydrant : ist ein png der als frame auf dem hydrant geht wenn die anim fertig ist.
- bg_building_day: ist ohne leute im hintergrund aber man muss auch "subway_station.png" als layer drauf legen.
- People_BG1...taucht auf, dann + People_BG2,..+ etc. (um zu inzienieren das es immer mehr Leute kommen)

"finger/hand visual testen" lass uns es au der Seite legen.

"guy in staubstauger-position (copperfield) mit blitz - animation" ist ein kompletes neues gif. würde erstmal mit "attak 1" animation machen.

"ein passant mit walk-cycle, der dann stehenbleibt und jubelt" ist nicht wichtig (nochmal ein gif...) da wir die Leute im BG haben.

**Comment by Waog** [comment]
wie soll ich die Leute einblenden? langsam rein-faden lassen?
Es wäre sinnvoller wenn du mir die Leute als einzelne Bilder schickst, dann haben wir nicht noch mehr unnötig große Grafiken und ich könnte die zufällig platzieren.

**Comment by ghost** [comment]
Ich habe die einzelne gespeichert.

Einblenden? hmm...langsam reinfaden (1sec?) wäre cool.

**Comment by Waog** [comment]
okay, baue ich so ein.

**Comment by Waog** [comment]
ich brauche noch eine unterhosen-grafik, die klarmacht, dass der player gerade mit telekinese dran _zieht_ .... sonst sieht es einfach aus als wolle der guy die unterhose mit blitzen abschießen

**Comment by ghost** [comment]
wenn man ein art bubble herum baut wäre eine Lösung...

![screen shot 2015-03-08 at 17 44 03](https://cloud.githubusercontent.com/assets/7753856/6546614/ce6d040e-c5ba-11e4-83f4-ab7e3e00c20d.png)

**Comment by Waog** [comment]
ich fänds cooler wenn sie so langgezogen würde und so blitze (in finger-form?) am ende hat.
Etwa so, nur mit deiner skill:
![image](https://cloud.githubusercontent.com/assets/5098472/6546628/3fde05f2-c5bb-11e4-8da5-e55716ea2917.png)

**Comment by ghost** [comment]
"finger forme/blitz" ist lustig aber nicht erkenbar mit pixel.
Bubble (mit blitze herum vielleicht?) finde ich eine bessere Lösung.

aber was man noch brauch ist einmal "Unterhose" die nach unten geht (fällt runter) oder?

**Comment by Waog** [comment]
jap... aber was soll ich mit einer bubble machen, wenn der player nicht schnell genug drückt? die schwebt dann dort in der luft oder was?

**Comment by ghost** [comment]
wenn er nicht schnell genug druckt die bubble Blendet aus und die Unterhose geht wieder auf die Hydrant. oder?

**Comment by Waog** [comment]
fliegt die dann immer so hin und her.... über dem müllsack?

**Comment by ghost** [comment]
"unterhose und Bubble" wackelt (minimal links-rechts-oben-etc.) und gleichzeitig duch die Telekin. bewegt sich langsam richtung müllsäcke.

**Comment by Waog** [comment]
ich habe nochmal verglichen wie es im comic ist.... kannst du blitze statt einer durchgehenden kugel machen? also **ungefähr kugelförmig** hauptsache die umranden so die unterhose.... die kugel finde ich ist zu viel magie...

**Comment by ghost** [comment]
dann sowat finde ich okay...

![bubble](https://cloud.githubusercontent.com/assets/7753856/6546735/5253ec2a-c5bf-11e4-936b-0d0bdecb486e.gif)

**Comment by Waog** [comment]
ohne die kugel wäre besser.... im comic ist auch keine kugel hingemalt

**Comment by ghost** [comment]
ist wie ein "force field", sonst sieht es blöd aus (als animation)...
hab das noch reduziert, sieht "Perfekt" aus :)

![bubble](https://cloud.githubusercontent.com/assets/7753856/6546749/8513f35c-c5c0-11e4-8627-fddf3c49e7a0.gif)

**Comment by Waog** [comment]
najut... kannst du die unterhose noch da reinmachen? brauche in dem fall keine getrennten grafiken.... dann kannste so zu dropbox hochladen... bin jetzt genau an dem punkt wo ichs einbauen will

**Comment by ghost** [comment]
kann man nicht separat machen und den Kugel einblenden kurz nach die Unterhose schwebt?
(1x Kugel anim mit sparks als layer uber die Unterhose?

**Comment by Waog** [comment]
kann ich auch machen... dennoch brauche ich irgendeine schwebe-animation der unterhose.

**Comment by ghost** [comment]
aber dafür kannste dite benutzen oder? (ist in drop)

![underwear_flying](https://cloud.githubusercontent.com/assets/7753856/6546808/77065a0a-c5c2-11e4-817f-dcbdca592184.gif)

**Comment by Waog** [comment]
kann ich machen, wenn das gut aussieht.

**Comment by Waog** [comment]
achso.... das mit dem einblenden ist doch quatsch... das buttonmasching ist viel zu schnell, dass man die einblende-animation wirklich sehen kann

**Comment by ghost** [comment]
sonst kann man auch nur ein frame vom gif nehmen und mit programmierung ein effect drauf legen (geht langsam unten-oben-unten...)

**Comment by Waog** [comment]
das neue **bg_buildings_day.png** hat keine menschen mehr davor, wie bisher.
Kannst du mir davon eine zweite version fertig machen, mit menschen davor? (fürs haupt-gameplay)

**Comment by ghost** [comment]
Wolltest du nicht den Random durch Programmierung plazieren? 
die sind als einzel gespeichert (people simple BG1,2,3...) + subway station.png (geht layer über)

**Comment by Waog** [comment]
nur im tutorial... im gameplay ist besser wenn alles ein bild ist, wegen der performance.

**Comment by ghost** [comment]
ok, liegt in drop: bg_buildings.png

**Comment by Waog** [comment]
ok, habs eingebaut
