### ISSUE TITLE
tutorial touch

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#74]
zuerst #73 fertigstellen, dann:
## art
- hand/finger (ggf. verschiedene) - animation
- Flächen-grenzen (smiley, werden skaliert) ... verschiedene flächen - pngs
- ggf. icons für die flächen (pfeile, stichmännchen)
## programming
- arts oben einbauen
## sounds

wie #73

**Comment by ghost** [comment]
"Flächen-grenzen (smiley, werden skaliert)"
was war "smiley" nochmal???

euh...
"ggf. icons für die flächen (pfeile, stichmännchen)" 
das auch verstehe ich auch nicht...

**Comment by Waog** [comment]
beim touch gibt es 3 bereiche die man zum steuern anklicken muss (links vom guy, rechts vom guy und hydranten-region). Diese Flächen müssen wir im Tutorial visualisieren, damit der Spieler weiß wo und wie schnell er tippen muss.

Wir haben uns geeinigt, dass wir einen Rahmen um die Regionen zeichnen = Flächen-grenzen.
Warum da "smiley" steht, keine Ahnung.

Ggf. icons für die flächen (pfeile, stichmännchen), heißt dass die Zwei flächen neben dem Guy z.B. ein Icon mit einem Rennenden männchen in der Mitte bekommen und die rechts fläche einen Blitz.

**Comment by ghost** [comment]
mmmmkay...
![screen shot 2015-02-27 at 21 49 33](https://cloud.githubusercontent.com/assets/7753856/6420899/8f66db1e-beca-11e4-9dd7-e950a32443b9.png)

wenn wir sowas machen:
-"hand icon" blend ein, geht nach links (+ Pfeil, wie eine spur) > user tip.... (die grüne Grenze/Fläche passt sich an)
-"hand icon" blend ein, geht nach rechts (+ Pfeil, wie eine spur) > user tip... (die grüne Grenze/Fläche passt sich an)
-"hand icon" blend ein, tip auf "Hydrant Fläche" (+ waves) > user tip (aktiv "attak" auf Hydrant)

**Comment by Waog** [comment]
- die zonen sind in wirklichkeit größer, es gibt diese weißen zwischenräume nicht.
- der pfeil impliziert für mich "swiping", not touching. Wenn der Pfeil nur bedeuten soll, dass der Guy sich bewegen wird, dann finde ich ihn eher verwirrend.
- den usertip brauchen wir nicht, wenn wir die fläche nicht sofort ausblenden, sondern mitbewegen, während sich der user bewegt.
- auch die waves finde ich nicht aussagekräftig, das impliziert für mich nur "touch here", aber nicht "touch fast!".

Also von mir aus reichen nur die 2 Hände + die Farbcodes für die Zonen. Außer du machst noch richtige (skalierbare) Grenzen für die Flächen.

**Comment by ghost** [comment]
-die weisse one sind zone wo man nichts machen kann (da es die Grenze gulli/Mühl gibt) aber ja, braucht man nicht unbedingt...
-Pfeil:ok
- ok..
  -yep

**Comment by ghost** [comment]
die Hand liegt im Drop.
color code:
Fläche violet: #7a0184
Lignie grün (Grenze): #acfa76

bei die Violete Flächen ist eine mit 80% Transparenz und die andere mit 40% Transparenz

**Comment by Waog** [comment]
Cool. Könntest du noch den Finger animieren? Also einfach einen zweiten Frame mit kurzem Finger / Finger drückend. Ich kann dann unterschiedlich schelle Animationen abspielen.

**Comment by ghost** [comment]
Liegt in drop 
![hand_anim](https://cloud.githubusercontent.com/assets/7753856/6431471/17aeb804-c031-11e4-9f35-1b86442581c1.png)

**Comment by Waog** [comment]
eingebaut...
