### ISSUE TITLE
buitify lifebar

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#75]

**Comment by ghost** [comment]
![screen shot 2014-09-15 at 18 41 56](https://cloud.githubusercontent.com/assets/7753856/4274860/69eceb44-3cf7-11e4-9f03-b7f215f4ad9b.png)

ausser wenn es dich richtig ankotz ( :+1: ) würe ich das so machen... für hydrant life bar und #89 

hero hat 3 herz (2try9 und life bar besteht aus 100 stripes...

**Comment by Waog** [comment]
jo, würds nur anders auf dem bildschirm anordnen... hero leben nach links...

Wie wärs, wenn sich der dunkel-rote teil der life-bar kontinuierlich bewegt und die hellroten streifen aber nur verschwinden und auftauchen?

**Comment by Waog** [comment]
wir brauchen:
- [x] hydrant:
  - [x] einen hellroten balken, der immer wieder programmatisch gezeichnet wird
  - [x] dunkelroter balken, der programmatisch skaliert wird
  - [x] background
- [x] player

**Comment by ghost** [comment]
im Drop box: 141016 > energy gameplay

**Comment by Waog** [comment]
player lifebar fertig... hydrant lifebar TODO

**Comment by Waog** [comment]
done
