### ISSUE TITLE
new fontain

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#76]

**Comment by Waog** [comment]
animations + particle, wenns gut aussieht

**Comment by ghost** [comment]
liegt in drop:
Hydrant_flow.   SIze S(small) Size M(medium) Size L (Large)

![hydrant_flow_l](https://cloud.githubusercontent.com/assets/7753856/6542144/b4940b10-c4f0-11e4-8f4a-f83f28690322.gif) ![hydrant_flow_m](https://cloud.githubusercontent.com/assets/7753856/6542145/b4986304-c4f0-11e4-9362-de075c8e30f5.gif) ![hydrant_flow_s](https://cloud.githubusercontent.com/assets/7753856/6542146/b499bdda-c4f0-11e4-9235-8655c7885803.gif)

**Comment by Waog** [comment]
hmm, ich finde die sehen fast gleich aus... die unterschiede dazwischen sollten _viel deutlicher_ sein.

**Comment by ghost** [comment]
Villeicht... 
lass uns es erstmal das so bauen und wenn die Runde fertig ist anschauen was man optimieren kann.

**Comment by Waog** [comment]
habs eingebaut... aber ist wie ich gesagt habe... man sieht keine unterschiede... und dann wenn man gewinnt ist die fontaine mit einem schlag weg, weil sie vorher zu groß/stark war:
![image](https://cloud.githubusercontent.com/assets/5098472/7438710/f09b57b4-f068-11e4-9e2b-a9db3ab56565.png)

**Comment by Waog** [comment]
Achso, außerdem bräuchte ich die Bilder ohne den Hydranten... Ich editiere es jetzt mal händisch in construct nach.
