### ISSUE TITLE
themen fürs näääächste treffen

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#79]
- animationsgeschwindigkeit
  - menschenmassen
  - flash
  - autos
- große tropfen (schlecht erkennbar, zu unwichtig)
- durchgehender blitz

**Comment by ghost** [comment]
wann treffen wir uns wieder eigentlich? wann hättest du Zeit? (am W.E kann ich leider nicht)

**Comment by Waog** [comment]
lass mich erstmal meine neuen issues fertig machen... könnte 0-2 wochen dauern. dann können wir nochmal n termin machen, k?

**Comment by Waog** [comment]
issue ist nicht mehr wichtig... steht in anderen issues oder ist geklärt
