### ISSUE TITLE
grenzen links rechts

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#81]
- ausweich animation

**Comment by Waog** [comment]
wenn möglich, eine animation für beide seiten gleichzeitig

**Comment by nostoner** [comment]
ich versuche dieses Topic für Freitzag/Samstag fertig zu machen.
Wäre ganz gut wenn du die "Programming" Tasks am W.E auch hinkriegst, dann können wir endlich dieses Milestone schliessen... :)

**Comment by Waog** [comment]
ich gebe mein bestes... aber ich wäre nicht überrascht, wenn ich dir noch einige Tickets zurückgebe, weil irgendwas nicht so geht wie gedacht... bezweifle also dass wir dann schon fertig sind.

**Comment by Waog** [comment]
@nostoner wie sieht's aus mit diesem Issue? Ich habe es jetzt erstmal so gemacht, dass der Guy am Rand einfach stehenbleibt, auch wenn der Spieler weiter gegen die mauer rennen will.

Willen wir hier jetzt noch Ausweich-Grafiken einbauen? Sieht etwas langweilig aus, wenn er einfach nur stehen bleibt.

**Comment by Waog** [comment]
We need an animation like _stand_, which doesn't end or move the guy.

As a programmer I just want to activate the new animation instead of stand and it should work...

**Comment by ghost** [comment]
![avoid_cycle](https://cloud.githubusercontent.com/assets/7753856/7524582/53df9742-f503-11e4-8b9a-1598833d8175.gif)
ist ein 3 frame anim + "stand" am anfang"
![screen shot 2015-05-07 at 21 53 34](https://cloud.githubusercontent.com/assets/7753856/7524613/8506d8ee-f503-11e4-90f8-70da7c871fa0.png)

bevor ich die andere bau, wäre gut wenn du erstmal damit ein test macht...
liegt in drop: avoid_1.png

**Comment by Waog** [comment]
jop, baue ich dann erstmal für alle 3 zustände ein.

**Comment by Waog** [comment]
habs eingebaut, sieht so mittelmäßig aus.... 2 vorschläge:
- dass er die hände nach oben nimmt sieht irgendwie aus als ob er denkt _hm, keine Ahnung_ und nicht als ob er sich ekelt. Kriegst du es hin, dass er die Arme so schräg nach vorne/unten streckt, als ob er sich schützen will?
- wenn der fuß maximal weggezogen ist (frame 4), dann sollte er kurz so stehen bleiben, ohne immer sofort wieder den fuß vorzustrecken. Ein 5. Frame, wo das Bein hinten bleibt und er einfach nur atmet wäre gut.

![image](https://cloud.githubusercontent.com/assets/5098472/7552207/8e97d0e2-f6a8-11e4-9bc3-9e7ee4a89226.png) ![image](https://cloud.githubusercontent.com/assets/5098472/7552211/b42232f8-f6a8-11e4-8962-3dafe0eeac01.png) ![image](https://cloud.githubusercontent.com/assets/5098472/7552227/05ba6900-f6a9-11e4-9baf-a4be8c39696a.png)

**Comment by Waog** [comment]
like this: http://i.istockimg.com/file_thumbview_approve/18174442/3/stock-photo-18174442-scared-and-disgusted-young-woman.jpg

**Comment by Waog** [comment]
habe mal eingebaut, dass die fliegen um den guy kreisen, wenn er zu nah am müll ist. Beim Müll siehts jetzt ganz gut aus mit den Armen oben:
![image](https://cloud.githubusercontent.com/assets/5098472/7552269/c3e4c496-f6ab-11e4-8b45-0caa1690e4d5.png)

**Comment by ghost** [comment]
warum ist diese Issue noch offen? (weiss nichtt mehr...) ist allet juti oder?

**Comment by Waog** [comment]
weil ichs nicht so cool fand mit den armen oben am gulli. siehe meine vorschläge oben.

können wir nochmal diskutieren und meinetwegen auch so lassen...

**Comment by Waog** [comment]
@nostoner ist **sehr** zufrieden, wir lassen es so
