### ISSUE TITLE
kontrast spiel-elements - dekoration

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#82]

**Comment by ghost** [comment]
Aktuelle Stand:
![1](https://cloud.githubusercontent.com/assets/7753856/6450738/2e5a1be4-c12a-11e4-9db6-0108f5db89ca.jpg)
Ich würde der Kontrast so pushen, aber nicht mehr...
![3](https://cloud.githubusercontent.com/assets/7753856/6450749/4bc35fba-c12a-11e4-88a0-f19cb1ff5ece.jpg)

**Comment by Waog** [comment]
Ich als Farb-Spongo musste jetzt erst 4 mal vergleichen, bevor ich einen Unterschied bemerkt habe... die Farbauswahl überlasse ich mal besser dir :D 

Aber: Die Autos sollten mehr an den Hintergrund angepasst sein, als an den Spieler, da sie nicht relevant sind für die Spielmechanik, sondern nur Deko. Genauso die Fotografen etc.

Du solltest vor allem probieren wie gut die Tropfen in dieser Farbeinstellung sichtbar sind. Die schlechte Sichtbarkeit der Tropfen war nämlich der Hauptgrund für dieses Ticket.

**Comment by ghost** [comment]
hmmmkay... aber dafür einfach ein weisses Pixel auf das Spiel zu kleben, hilft mir nicht zu beurteilen. Wir mussen deine Magie involvieren. Also Tests machen (eingebaut)...

Ich versuche: Autos, Menschen BG und Buildings BG dunkler zu machen... (aber soviel wird es nicht, da den look immer Tags über sein muss...)

**Comment by Waog** [comment]
wtf? :D habe nix vom ersten absatz gecheckt.... aber du machst das schon :)

**Comment by ghost** [comment]
ahahah! ja so muss es sein...

**Comment by ghost** [comment]
"Contrast_cache.png" ist nochmal ein cache der über die Ebenen: Building/cars & people Background geht.
sollte helfen für den Kontrast.

![contrast_cache](https://cloud.githubusercontent.com/assets/7753856/6542255/59cbe22c-c4f3-11e4-873d-3debb0475e5d.png)

**Comment by ghost** [comment]
und ich habe "bg_buildings_day.png" nochmal ersetz (front Buildings sind ein bisschen dunkler jetzt)

![bg_buildings_day](https://cloud.githubusercontent.com/assets/7753856/6542325/74d9a390-c4f5-11e4-9806-b019a5b6ce29.png)

**Comment by Waog** [comment]
done
