### ISSUE TITLE
schatten große tropfen

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#83]

**Comment by ghost** [comment]
eigentlich ein pixel schwarz reich oder?
dann kannste den die transparenz verändern und die Größe skalieren...

oda?

**Comment by Waog** [comment]
ich habe grad doch nochmal deine dunkelrote lifebar selbst nachgezeichnet, weil construct total kacke ist, wenn man etwas hochskaliert. machs mal 100x100px groß und ich skalliere dann lieber runter.

soll der schatten genau rechteckig sein? nicht oval?

**Comment by ghost** [comment]
eigentlich sollte es in der Richtung sein:
![screen shot 2014-10-17 at 23 12 36](https://cloud.githubusercontent.com/assets/7753856/4686164/62e3fffe-5642-11e4-9108-a5a7b3003761.png)

also lange vierecke...
brauchste trotzdem 100px x 100px?

PS. die Tropfen sehen cool so findeste nicht...? (und besser zu erkennen mit bem BG)

**Comment by Waog** [comment]
das mit den streifen hatten wir schonmal... dann musst du dir was gutes einfallen lassen, wie die streifen verschwinden, wenn ein tropfen auf den boden knallt... es sieht kacke aus, wenn wir die streifen einfach plötzlich weg sind.

Kannst die Schatten auch 30x10 oder so machen... hauptsache ich muss sie nicht größer skalieren...

**Comment by ghost** [comment]
liegt im Drop...

(wegen drop wenn die Spuren nicht zu lange sind und mit transparenz, sollte nicht wirklich stören denke ich... sollte man probieren, was meinste?)

**Comment by Waog** [comment]
probieren können wirs, aber ich denke da werden wir uns irgend nen trick einfallen lassen müssen...
Aber die Kontraste sind durch die Streifen auf jeden fall erstmal besser.

**Comment by Waog** [comment]
habs eingebaut. willste noch was daran machen, oder haste nur vergessen, das Issue label zu ändern?

**Comment by ghost** [comment]
ver...ge...ssen... :)

**Comment by Waog** [comment]
done
