### ISSUE TITLE
guy recover from attack animation

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#85]
## art
- 3x attack to stand animation
## programming
- einbauen

**Comment by ghost** [comment]
![recover_attack_1](https://cloud.githubusercontent.com/assets/7753856/4275833/0085ac78-3d00-11e4-810c-c3ee616e391e.gif)
![recover_attack_2](https://cloud.githubusercontent.com/assets/7753856/4275834/057b11dc-3d00-11e4-9554-4f342487f8f9.gif)
![recover_attack_3](https://cloud.githubusercontent.com/assets/7753856/4275840/0af6009a-3d00-11e4-9e4f-84ef2f6931e2.gif)

in drop box als animated gifs.
recover_attack_1.gif
recover_attack_2.gif
recover_attack_3.gif

villeicht mussen wir erstmal auf eins probieren ob es gut klappt (nicht zu lang...) sonst können wir den kürzer machen (weniger frames...)

**Comment by Waog** [comment]
ich baue sie mal so ein, dann sehen wirs... bisher brauchst du einige frames, nur um die flash-animation kleiner werden zu lassen, bevor der guy sich bewegt. Falls die animationen so zu langsam sind habe ich noch folgenden vorschlag:
- der guy geht unabhängig vom blitz zurück in die stand animation
- der blitz wird in einer seperaten grafik kleiner und verschwindet (verpufft vielleicht so?)

so könnte der spieler schon losrennen (keine verzögerung) aber die blitze verschwinden trotzdem auf eine schönere art und weise.

**Comment by Waog** [comment]
kein seperater blitz.
frames wie oben benutzen, aber nur die hälfte ohne blitz

**Comment by Waog** [comment]
warum zieht der guy nach den angriffen das handtuch wieder hoch? Das muss unten bleiben, sonst haben wir einen sprung, nach dem ende der erholungs-animation.

**Comment by ghost** [comment]
my bad...

**Comment by ghost** [comment]
liegt im drop:
140915

**Comment by Waog** [comment]
ich sehe den task als ziehmlich unwichtig an. Das Spiel ist zu schnell und die Animationen zu langsam und fallen in der Action sowieso nicht auf. Ich verschiebe den Task mal in den Finetuning Milestone und wir können nochmal Diskutieren ob das wirklich gemacht werden muss...

**Comment by Waog** [comment]
Werde diesen Issue nicht erledigen, damit wir mal fertig werden.
