### ISSUE TITLE
graphics for mobile

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#88]
wir haben das wichtigste thema beim meeting nicht geklärt: wie lösen wir das problem, dass die Grafiken zu detailiert sind für mobile?

Es macht keinen sinn, dass du jetzt gleich die nächsten 20 grafiken produzierst, wenn die bisherigen grafiken schon ungeeignet sind für kleine monitore...

**Comment by ghost** [comment]
Ja stimmt...

würde vorschlagen, erstmal focus on was wir jetzt haben; und weiter machen wie es ist (graphics Browser und Ipad) damit wir erstmal was fertig machen können.
und wenn alles steht, wie passen die Graphics für smartphones an (mit automatic zoom, new graphics /grober pixel style, etc...)
sonst geht es nicht richtig voran..

"step by step, OH baby..." (http://www.youtube.com/watch?v=iCrargw1rrM)

**Comment by Waog** [comment]
naja, ich weiß nciht wie sinnvoll das ist... wir machen jetzt lauter arbeit, die wir später wieder wegwerfen, weil sie unbrauchbar ist für mobile. Das ist für mich nicht _voran kommen_, sondern doppelte arbeit a.k.a. _zeitverschwendung_.

Ich habe auch relativ geringes interesse daran, ein browser-game fertig zu haben. Mein primär-ziel ist etwas für tablet und mobile fertig zu haben... das es im browser läuft ist für mich nur ein netter neben-effekt.

**Comment by ghost** [comment]
"primär-ziel " tablte und mobil, haste sicher recht...

für mich ist es so dass wir bis jetzt eine super qualität für browser (aber wie du sagt, browser ist eigentlich egal) haben, aber for allem für Tablet/Ipad, und das ist sehr gut so.

Trotzdem, ist zwichen: Tablet und Smartfone, ein grosses unterschied (resolution, Gameplay problematik/format für Smartphone die am Samstag beschprochen sind, etc.)

bis jetzt haben wir was so:
(browser (ist uns aber egal):        -----> quatlität das wir haben ist sehr gut)
Tablet:                                           ----> quatlität das wir haben ist super
Smartphone:                                -----> ist nicht so gut (muss angepasst werden)

Fürs workflow, ist wichtig erstmal ein von beide fertig zu machen. Da wirg schon sehr weit sind mit (nene ich das so:) "Tablet", schlage ich for: erstmal weiter und fertig machen, und nur danach Smartfone anpassen... 

der Vorteil ist das wir nicht mehr in Modus Probieren-testen-Zeit verschwinden für zwei Platform, sondern focus auf eine Aufgabe und danach Anpassen an Smartfone...

"wir machen jetzt lauter arbeit, die wir später wieder wegwerfen" euhhh... ich sehe nichts das wir später wegwerfen müssen... sowieso muss es so weiter (für Tablet) gemacht werden.

**Comment by Waog** [comment]
die doppelte arbeit ist folgende:
- entweder wir entwickeln jetzt direkt für mobile und man kann es auch auf tablet und browser spielen = 1x arbeit
- oder wir entwickeln jetzt alles für tablet und wenn wir fertig sind, entwickeln wir alles noch ein zweites mal für mobile = 2x arbeit

**Comment by ghost** [comment]
ich sehe das ein bisschen anderes:
das es irgedwie und sowieso "angepass" (für die grunde wir am Samstag schon beschprochen hatten) werden muss, die frage von 1x arbeit oder 2x arbeit stellt sich nicht wirklich.

nochmal, von meinem Blick: 
Format MOBILE ist anderes als TABLET/BROWSER
wir sind "fast" fertig mit TABLET/BROWSER sind, sollten wir einfach das erstmal erlidigen, und next step sollte MOBILE (anpassung) sein.

also von mir aus, 2x arbeit gerne (anpassung) wenn es sein muss (und ich glauuuuuuuube, dass es sein muss ho ho ho! :)

**Comment by Waog** [comment]
naja, wie du meinst... ich denke es wäre besser klare grafiken zu haben, die auch auf mobile gut aussehen und die dann einfach groß zu skalieren für tablet/browser... die sind dort dann auch klar.
