### ISSUE TITLE
Graphics MainMenu

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#9]

**Comment by ghost** [comment]
![key_visual2](https://cloud.githubusercontent.com/assets/7753856/3269316/270d171e-f2eb-11e3-8e75-0752ace5f4ef.jpg)
WIP
test with pixel art mix

**Comment by Waog** [comment]
wow, great work :+1: :+1: 

but i can't see any pixel-art here. what do you mean?

**Comment by ghost** [comment]
it's just on my shopping list... :) (have to do it)

**Comment by Waog** [comment]
Ich finde das Bild bereits richtig geil... was hälst du davon, wenn das Handtuch noch "kuscheliger" ist, anstatt so glatt zu sein.
Damit sähe es vielleicht noch absurder aus, wie der muskulöse superheld da in seinem baby-handtuch steht :laughing: 

![2231848-763977-blaues-handtuch-frottee-weiche-textur-tuch](https://cloud.githubusercontent.com/assets/5098472/3286532/c06f4bf0-f54a-11e3-9404-493a9ecb8a03.jpg)

**Comment by ghost** [comment]
wäre cool jep! :)

**Comment by ghost** [comment]
took yesterady time for finalise the Key visual for the main menu... (almost final)
-we have probably to put the logo #22  on this page, (Logo have to be rethink, but this one could be a good start)
- buttons "Play" and "Credits" have the "Game" look, what do you think? (should be used for all buttons in the game)

![bg_intro_test](https://cloud.githubusercontent.com/assets/7753856/3339426/04f2d6ba-f86c-11e3-9521-dc78982a1c80.png)

**Comment by Waog** [comment]
Very Cool :)
The Button-Style is ok, but the button and logo should be bigger or somehow more obvious. Imagine it on a small handy display...

**Comment by Waog** [comment]
Ah und das Handtuch hat ja noch gar nicht den kuschel-style :)

**Comment by ghost** [comment]
hab versucht, aber muss ich noch rumfummeln... (kriege es sehr schlecht ihn mit dem style... aber ich probiere es noch! i swear!!! )

**Comment by ghost** [comment]
Butons and Logo, aufs Browser ( da es erstmal was wir machen...) finde ich nicht so gut wenn es noch grösser ist. 
Aber recht haste, auf andere Platform ist auf jeden falls nötig....

**Comment by Waog** [comment]
Auch für den browser finde ich es zu klein... auch wenn deine grafik geil aussieht, ist es nicht nicht das primärziel des nutzers deine grafik anzugucken, sondern die menü-funktionen zu benutzen. Und dafür sind die zu klein und unauffällig.

**Comment by ghost** [comment]
mir gehts nicht ganz um mein Grafik ( aber Danke :) 
ich finde die Buttons nicht so unauffälling, aber kann man die natürlich ein kleines bisschen grösser machen. villeicht sind Sie Falsch plaziert, oder nicht grafik passend (kann auch sein :) deshalb muss man noch ein bisschen dran arbeiten.

Ich finde 2x grössere Button(z.B) sehen nicht Professionnel aus.

hab den vergleich mit andere games gemart, ich glaube es händel sich mehr ums Logo....
![2 copy](https://cloud.githubusercontent.com/assets/7753856/3348352/dfa53fa4-f926-11e3-9b6d-e831af30289d.jpg)

aber ich versuche weiter wat passend zu finden...

**Comment by ghost** [comment]
(übrigens, kennst te "another world" and "Flashback". Super geilo Spiele der 90' :)

**Comment by Waog** [comment]
Your examples aren't chosen that well. The problem is, that the control via mouse/computer vs gamepad/console is different: 
- When you only have a game pad and a game console, you push any of your keys and instantly understand it's impact and see the changes in the screen. You don't have to fear to damage your system.
- On the other hand, when you have a keyboard, a mouse and a computer, the default behavior of most users, isn't clicking and typing around wildly. They take a look what to click and it should become visually obvious what it is, just by looking around.

Also your examples seem very biased towards small buttons. When i just google _game start menu_ this are my first results. They have much bigger buttons:
![image](https://cloud.githubusercontent.com/assets/5098472/3350103/c679266c-f98f-11e3-8933-110092a6862e.png)
![image](https://cloud.githubusercontent.com/assets/5098472/3350105/d9792de8-f98f-11e3-8c65-1912032bb9ef.png)
![image](https://cloud.githubusercontent.com/assets/5098472/3350109/ed64e180-f98f-11e3-9698-248e431ddaef.png)
![image](https://cloud.githubusercontent.com/assets/5098472/3350110/fa487b50-f98f-11e3-8269-89d0a6405a4a.png)

**Comment by ghost** [comment]
"Flashback" würe ursprunglich für  AMIGA500 entwickelt...( mehr "Computer game" kann ma nicht machen :) nachträglich würde er für console angepasst (atari, megadrive, snes...) und ist  ein Erfolgspiel.
(also Conputer UI vs. Console UI gerne, aber es Beweis das Gegenteil)

finde deine Beispiel (UI und Design) bringen uns nicht viel mehr. Beispiel 1 und 3 sind jut und haben die (mehr oder weniger) gleiche proportionen wie unsere buttons (bisschen grosser aber egal) und Beispiel 3 und 4 sind für mich kein Vorbild.

Hab nochmal andere Browser game (Proportionnel) mit unsere Interface verglichen.
![a](https://cloud.githubusercontent.com/assets/7753856/3351235/28967464-f9fc-11e3-8c6b-beef9399e5ff.jpg)
![b](https://cloud.githubusercontent.com/assets/7753856/3351236/289cab0e-f9fc-11e3-8c47-6f34f0af9127.jpg)

was denkst du von der Richtung:
![td](https://cloud.githubusercontent.com/assets/7753856/3351256/ea1cec94-f9fc-11e3-92c8-d3e04c5237d3.jpg)

sonst, müssen wir Überlegen ob das Key Visual nicht Überflüssig ist, und wat mit pixel art machen... ( bin mir eigentlich nicht janz sicher.. Piexel art ist nicht sehr Knallig, und eine Geile Illu wie jetzt ist eine bessere Einladung zum Spielen...)

**Comment by Waog** [comment]
so finde ichs schon viel besser. die buttons fallen dort viel mehr auf, vielleicht weil der hintergrund homogener ist. Also ich mags so, auch die farben find ich besser.

**Comment by ghost** [comment]
hab noch eine andere variante...
![screen shot 2014-06-23 at 14 52 53](https://cloud.githubusercontent.com/assets/7753856/3357782/17ad372a-fad6-11e3-8db8-cf3bb9a256a8.png)
bin mir nicht janz sicher ob es besser oder schlechter ist...

wat meinste?

**Comment by Waog** [comment]
- jetzt wo ich gerade über autosize gelesen habe: du musst auch daran denken, dass die benutzer alle verschiedene ratios haben... also du musst auch hier so designen, dass es noch einen "unwichtigen Rand" gibt.
- ich finde die vorherige variante (ohne lila rand) etwas besser. Können wir die buttons noch in y-richtung auf 1.5 fache bis 2 fache größe skalieren? Vielleicht auch nur den Play Button und Credits klein lassen.

**Comment by ghost** [comment]
- Stimmt
- Ok (ist es eigentlich lustig wenn wir "Plaaay!" or "Let's play!" schreiben, oder nicht so?)

**Comment by ghost** [comment]
hab erstmal dieses Menu im Dropbox reingelegt...
![intro_0000_v1](https://cloud.githubusercontent.com/assets/7753856/3369678/8450d98c-fb84-11e3-9da0-2f61753d3f84.png)
hab noch nen paar andere Variante, villeicht kann man demnächst noch nach denken UI mässig...
![intro_0001_v2](https://cloud.githubusercontent.com/assets/7753856/3369708/cdf3acb8-fb84-11e3-8b43-50bd98ffac86.png)
![intro_0002_v3](https://cloud.githubusercontent.com/assets/7753856/3369709/cdf4dee4-fb84-11e3-9b01-2d64b0fb20cf.png)
![intro_0003_v4](https://cloud.githubusercontent.com/assets/7753856/3369710/cdf6e1da-fb84-11e3-993d-05cda9d885f3.png)
![intro_0004_v6](https://cloud.githubusercontent.com/assets/7753856/3369711/cdfb4ebe-fb84-11e3-8ad8-256a262d6c77.png)

**Comment by Waog** [comment]
keine Ahnung ob das lustig ist, oder eher gezwungen wirkt. Ich würde sagen wir bleiben bei "Play"... wenn wir den witz erst engineeren müssen, dann ist er glaub ich einfach nicht so geil.

Ich mag die erste Variante am meisten. Vielleicht die Schriftgröße noch angleichen? Ich glaub der Play-Button hat jetzt zu viel Padding.

**Comment by ghost** [comment]
- Ok.
- "Schriftgröße "
  Würde ungern zwei unterschidliche Font größe benützen, macht typografisch nicht Sinn.
  Hänlich, finde ich auch fürs Button Größe. sollte eigentlich am besten wie das zweite Beispiel sein. 
  Da wir benutzen "Play" und "credits" auf die gleiche "Ebene wichtigkeit" sollte es auch als Corporate Design Hänlich sein.

sonst sollten wir eine Starke Diferenzierung zeigen, und mehr in der Richtung "Beispiel 3" gehen... (z.B. Groß "Play" button mit eine farbe, small "credits" button mit eine andere farbe oder so was...)

wat denkste te?

**Comment by Waog** [comment]
Verstehe... dann finde ich das letzte Beispiel glaube ich am besten. Da sieht der Play-Button nur irgendwie so "einsam" aus :)

Das Problem ist: Play und Credits sind inhaltlich nicht gleich wichtig... 95% der clicks werden auf Play gehen, vllt 5% auf credits. D.h. Die user wollen spielen und interessieren sich nen scheiß für credits. Daher würde ich die Buttons auf keinen Fall gleich darstellen.
Aber credits sollte auch nicht so unauffällig sein wie im dritten Beispiel glaube ich... also man sollte zumindest auf den ersten flüchtigen Blick wahrnehmen, dass da irgendetwas zum interagieren ist. Das ist im letzten Beispiel gut gelungen.

**Comment by ghost** [comment]
![bg_intro_full](https://cloud.githubusercontent.com/assets/7753856/3459100/d6218baa-0208-11e4-9997-ac43df3c8767.jpg)

Hab nochmal die Buttons so gemacht fürs Itro/main Menu (pass viel besser und sieht knalliger aus) für den rest (game, credtis, etc...) bleiben die Buttons wie Piexel.

den BG (illu) finde super mit "retro-game-stripes screen" hab noch ein art fenster spiegelung eingefügt... finde ziemlich cool so.

was häslte davon?

**Comment by ghost** [comment]
Buttons und Layout liegen im Drop Box... (datum: 140707)

**Comment by Waog** [comment]
Hmm... 
- also die Buttons finde ich gut so.
- Die fenster-spiegelung finde ich nicht schön, sie aus wie screenshot mit dem handy gemacht und foto wieder eingfügt. verstehe auch nicht was sich da spiegeln soll? Der raum in dem der automat steht?
- ich finds auch ohne die retro-streifen schöner, aber das ist einfach nur mein geschmack, kein sinnvoller grund. Die retro streifen könnten technisch auch ein wenig problematisch werden: Wenn ich da jetzt partikel-effekte von blitzen reinmache, dann haben die grundsätzlich erstmal nicht diesen streifen-effekt. Da könnte man vielleicht noch tricksen, indem man die blitz-partikel nicht einfach normal zeichnet, sondern (wie ebenen in phtotoshop) drauf addiert oder multipliziert oder so. Oder dass du die streifen als Halbtransparentes png bereitstellst und ich das in den Vordergrund lege. Aber noch lieber wäre mir, die streifen komplett wegzulassen :)
- was ist "stay high for games"? unser imaginaäres label/firma?
- diesen verzerrungs-effekt am rand finde ich übrigens auch sehr cool.

**Comment by ghost** [comment]
- Fenster Spiegelung: "screenshot mit dem handy gemacht und foto wieder eingfügt." ist eigentlich das Ziel... ist eine realistische darstellung. (Wie ob wir in ein " Arcade game" Raum wäre...) 
  zwischen Buttons (scharf) und Display (bisschen unscharf, "retro-streifen", Fenster Spiegelung) gibt eine bessere Tiefe auf die gesamte Interface. Das ist die Idee... 
- "Retro streifen" finde eigentlich ganz gut, hat was besonders im desing und Markieren auch eine Trennung mit Buttons (Buttons sind ein layer über die Streifen)
  ok, ich speichere die separat in png...
- "stay high for games" nimmste keine drogen? (joke) ja, egal ob es "stay high", Pumuckl gaming oder so, sieht viel Profi aus mit eine kleine Line (fake Game production or not)

**Comment by Waog** [comment]
- **fenster:** ok, idee verstanden und du hast die auch gut umgesetzt (sieht sehr echt aus), aber ich mochte die _klare/erkennbare_ grafik lieber. ich würde auch mit nem spiel-automaten nicht automatisch assoziieren, dass sich darin ein fenster spiegelt oder umgekehrt.
- **retro streifen:** ich mag sie zwar auch nicht, aber du bist der grafiker, deine entscheidung :)
- **fake label:** finde ich auch nicht so geil, aber meinetwegen. Ich finde den namen sogar gut, aber würde ich vielleicht trotzdem in etwas ändern, was uns nicht wie zugedröhnte Kiffer wirken lässt, wenn e professionell aussehe soll.
- **dynamische positionierung:** ich kann den credits-button und das label auch dynamisch (je nach ratio) positionieren. sieht vermutlich besser aus, als wenn das label so mitten im bild hängt, bei hohen bildschirmen. Dazu musst du mir die natürlich einzeln als pngs geben und den "schatten" vom hintergrund nehmen.

**Comment by ghost** [comment]
- fenster: "klare/erkennbare grafik" 
  geht mir personlich mehr um ein style zu hinterlassen (wenn man gespielt hat...)  und finde wie es jetzt ist  ziemlich gut. wir haben jetzt ein sehr starkes Key visual der auch klar und erkenbar aussieht (meine Meinug nach).  Ich finde auch nicht das es irgendwo/irgendwie von irgendjemand mit eine  "Neukölnerische Spielotek" assoziiert werden kann. (herlich , ich hab auch in meine Kindheit zu viel Zeit vor "DERRICK" im Fehrnsehen gebracht... ahahaha ik wess wie eine Spielothek aussieht und wir sind ganz entfernt :)
  hab das trotzdem als Separat PNG gespeichert, vielleicht kann man doch probieren...

retro streifen: finde die Geilo (sorry :) sind auch in PNG separat... lass uns das auch probieren, villeicht später mit blitz und musik (und was noch) sieht es kacke aus (glaube ich nicht, haha)
- fake label : "naughty dog" ist meine Meinug der best Aktuell Game entwickler... hat trotzdem ein Kotzkacke Name... ("RockStar games" klingt auch nicht so der super profi auf erstes Blick... )  

sonst mach ich gerne ein Logo für uns stt nur typo... (für einmal ;)
- dynamische positionierung: haste janz recht :)

**Comment by Waog** [comment]
dann stell mir auch schon mal die schrift als seperate grafik bereit, damit ich die schonmal einbauen kann. Und ein logo fänd ich total übertrieben. Der Schriftzug sieht ganz gut aus finde ich.

How about _addicted 2 games_? finde _high 4 games_ besser, aber _addicted 2 games_ klingt weniger als wären wir kiffer.

**Comment by ghost** [comment]
addicted 2 games ist cool...
liegt im Drop box..

**Comment by Waog** [comment]
Top! :+1: 

Die Positionierung der Elemente im Hauptmenü müssen wir dann auch mal zusammen machen wenn wir uns Treffen. Ich machs erstmal so wie ichs schön finde... also hässlich ^^

**Comment by Waog** [comment]
Done.

**Comment by ghost** [comment]
liegt jetzt ein button in drop box für "score"...
![screen shot 2014-08-09 at 00 30 58](https://cloud.githubusercontent.com/assets/7753856/3863619/bb6a1a38-1f4b-11e4-8477-553a7674e45c.png)

**Comment by Waog** [comment]
jut, baue ich ein...

**Comment by Waog** [comment]
alle grafiken eingebaut
