### ISSUE TITLE
Sounds & Music

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#91]
sounds für alles müssen her

**Comment by Waog** [comment]
@nostoner:
"habe villeicht jemand gefunden:
https://soundcloud.com/p0rncop/deep-impact

hoffe er meldet sich demnächst :)"

**Comment by ghost** [comment]
haste wat neuet vom Facebook Pool? ober wat jeanwortet?

**Comment by Waog** [comment]
bereden wir samstag

**Comment by ghost** [comment]
ok :)

**Comment by ghost** [comment]
> Mokba
> https://www.youtube.com/channel/UCf69z7VtcSTygbNKdFn4ELg
> 
> (contact Set)
> http://disconinjaz.net/

https://archive.org/search.php?query=8bit&and
http://www.micromusic.net/

exemples:
https://www.jamendo.com/artist/368781/danjyon-kimura

**Comment by Waog** [comment]
jo, kannst ja mal hinschreiben. das anschreiben liegt noch in dropbox.

**Comment by ghost** [comment]
haste wat von 9heart gehört?

**Comment by Waog** [comment]
Nope, er hat die nachricht am Sonntag gelesen, keine antwort.

**Comment by ghost** [comment]
NES - Turtle Ninja
https://www.youtube.com/watch?v=5kK8mFYbl1s

**Comment by Waog** [comment]
hm? warum closed?

**Comment by ghost** [comment]
same issue as #174...
