### ISSUE TITLE
Discussion & Comments Vol. 2

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#92]
replaces #49

**Comment by ghost** [comment]
Hallllllo!

**Comment by Waog** [comment]
Hier unsere 2 Verabredungen, damit du sie nciht vergisst:
- 7. & 8. März
- 28. & 29. März

**Comment by ghost** [comment]
Ach Kackewurst, ich glaube ich kann nicht mehr Labels editieren und so... hab bestimmt doch wat faslchjemacht am treffen :S
Kann es sein dass ich nicht mehr "Contributor" bin?

**Comment by Waog** [comment]
jo, habe dich neu hinzugefügt. probier mal jetzt

**Comment by ghost** [comment]
cool, läuft :)

**Comment by Waog** [comment]
Wie läuft der erste Milestone? Spätestens nächstes Wochenende brauche ich die Grafiken, wenn wir pünktlich fertig sein wollen.

**Comment by ghost** [comment]
Yep, hatte viel zu tuhn. Habe schon angefangen und sollte für Freitag alles fertig haben.

**Comment by Waog** [comment]
Na dann lad hoch was schon fertig ist! vielleicht nehme ich mir auch unter der Woche schon Zeit.

**Comment by ghost** [comment]
Yep. (wird schwierig, wir Pitchen (Arbeit) gerade...)

**Comment by Waog** [comment]
Wie siehts aus? Scheinbar müssen wir die Milestones nach hinten verschieben. Nochmal 2 Wochen auf alle Termine drauf addieren?

![unbenannt](https://cloud.githubusercontent.com/assets/5098472/6213619/f9b314c4-b5f1-11e4-88fa-8371c02ec56f.png)

**Comment by ghost** [comment]
Hi, leider war sehr viel zu tuhn letzte Woche und ich bin jetzt krank seit Freitag. Bin die ganze Woche krankgemeldet. Also, so schnell ich mich besser fühle gebe ich Gaz.
Lass uns die Milestones so behalten, wir kriegen es hin.

**Comment by Waog** [comment]
Oh, dann gute Besserung. Ich war letzte Woche auch krank, genauso wie mein ganzes Büro und meine WG... scheint irgendwas ultra ansteckendes zu sein

**Comment by ghost** [comment]
Hatte die GRIPPPPPPPE!!!!! Kackewurst... ich hasse dite! aber geht jetzt viel besser, thx...

**Comment by Waog** [comment]
Ich denke das Meeting dieses WE können wir ausfallen lassen. Ich würde die Zeit lieber zum Einbauen der neuen Grafiken nutzen... Was meinst du?

**Comment by ghost** [comment]
yep...

**Comment by Waog** [comment]
So, Milestone 1 ist fertig... habe ihn gerade geschlossen.
Habe dir einen Link mit der aktuellen Version des Games per Skype geschickt... kannst du mir mal eine E-Mail-Addy für sowas geben?

**Comment by ghost** [comment]
mien Skype kackt ab, kann mich nicht einloggen...
kannst du mir das an:
nostoner@yahoo.com
schicken?

**Comment by ghost** [comment]
Yey! sieht richtig cool aus, und läuft super :) i like it!

Fog moon, neue Hydrant flow uns sowas... haste trozdem eingebaut?

**Comment by Waog** [comment]
nee, noch nicht geschafft... habe erstmal nur den ersten Milestone gemacht...
Aber wir müssen dringend mal die Performance verbessern. Es läuft nicht _so_ super... fürs Tablet und Handy ist es viel zu inperformant.

**Comment by ghost** [comment]
okay Doc! dan machen wir das mit Milestone "Finetuning round1"...

**Comment by Waog** [comment]
@nostoner hey, nach längerer pause habe ich kommendes Wochende viel Zeit für unser Game. Freue mich schon endlich mal weiterzumachen :)

Wie läufts bei dir?

**Comment by ghost** [comment]
Hey hey!
coolio, läuft auch gut :) 
Freue mich och und werde auch Morgen weiter machen da wir frei haben, yey!

**Comment by Waog** [comment]
Wollen wir uns heute oder morgen mal treffen? Habe viel Zeit...

**Comment by ghost** [comment]
Yey! 17h bis... 20h Heute? bei dir?

**Comment by Waog** [comment]
jo, klingt gut... bis nachher :)
