### ISSUE TITLE
highscore tabelle

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#93]
wie hero-schild an der statue
- platte mit farbe wie hero schild
- darüber schrift mit siegern
- darüber wuchern pflanzen (unanimiert)

**Comment by ghost** [comment]
![screen shot 2014-10-16 at 20 40 43](https://cloud.githubusercontent.com/assets/7753856/4668621/a1bab092-5566-11e4-9fab-b352827a922c.png)

liegt och in Drop Box... mit Pflanzen Separat.
141016 > highscore plate

**Comment by Waog** [comment]
finally done :)
ich lege dir mal die bitmap fonts in dropbox
