### ISSUE TITLE
fix blitz im lose screen

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#94]

**Comment by Waog** [comment]
blitz ist immernoch im asset. see `park_lose_bg_buildings.png`

**Comment by ghost** [comment]
erledigt mit #95

**Comment by Waog** [comment]
don't just close the issue, I have to integrate your new graphics into the game first :)

**Comment by ghost** [comment]
this issue is not relevant anymore, we have the issue #95 who englobe this problem anyway... but okay!

**Comment by Waog** [comment]
ah, didn't know that... you're right
