### ISSUE TITLE
wolken lose screen

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#95]
- wolken tiefer und zwischen den gebäuden.
- [x] gebäude in 2 ebenen aufteilen
- [x] wolken noch schöner machen

**Comment by ghost** [comment]
liegt in Drop box:
141016 > park

(muss man leider noch ein Layer mit der Fence (park_lose_fence.png), da den blitz hinter sein muss...

**Comment by Waog** [comment]
- zusätzliche layer sind kein problem mehr, seitdem wir die pro version von construct haben... aber dass du immer winzige grafiken in pngs mit 1424 x 1168 px packst, könnte später ein performance-problem werden. z.B. der fence. Aber das lösen wir, wenn es wirklich ein problem ist.
- done
