### ISSUE TITLE
Bitmapfont einfärben

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#96]
Ich habe die bitmap font in die dropbox gelegt.
Kannst du die mal einfärben?

Du kannst da auch die glänzenden Ränder dranmachen, die du bei den Highscore plates hast.
Gerne auch zwei bitmap fonts, wenn du verschiedene farben für high score und win screen willst.

Dannach wieder mit programming labeln

**Comment by ghost** [comment]
![highscorebitmapfont_test](https://cloud.githubusercontent.com/assets/7753856/4684368/bda9a604-562f-11e4-9e50-fd5de5aa3568.png)

hab die Font mit dier andere Ersetzt (plus Buchstaben abstand verändert) ... kannste villeicht probieren ob es geht?
liegt in Bropbox...

**Comment by Waog** [comment]
Du hast scheinbar über die Ränder gemalt. Oben bei jedem Buchstaben sind jetzt immer ein paar Pixel von einem anderen Buchstaben. Und warum geht der Glanz-Effekt in die andere Richtung als bei den Vertiefungen auf dem Schild? Wäre es nicht logischer, wenn der Glanz-Effekt in die gleiche Richtung ginge?

![image](https://cloud.githubusercontent.com/assets/5098472/4684391/01e0cad2-5630-11e4-9f58-103437465523.png)

![image](https://cloud.githubusercontent.com/assets/5098472/4684406/3d0b844e-5630-11e4-936a-318806d5b72d.png)

**Comment by Waog** [comment]
passt jetzt, aber ich finde die farben im high score sehen noch nicht gut aus. im win siehts gut aus.

![image](https://cloud.githubusercontent.com/assets/5098472/4684715/4c29f7be-5633-11e4-919a-57f32383c277.png)

![image](https://cloud.githubusercontent.com/assets/5098472/4684730/683bfa24-5633-11e4-8ae2-544babe8fbbb.png)

**Comment by ghost** [comment]
hab wat neuet im Drop...

der Glanz effekt ist geprägt, dh. wie beim platten auf der Statue Highlights unten und links vom pregung...
die Grosse Plate ist zB. in Volume, dann Highlights oben und rechts... (aber stimmt, die  High lights Farben aufs Stripes betwenn name-heart-timer sind nicht genug hell, oder ich invertiere es... für eine Prägung. Haste recht)

**Comment by Waog** [comment]
habe noch nen Kommentar genau vor dir... nicht ausversehen überlesen ;)

**Comment by ghost** [comment]
okay....

hab nochmal im Drop Box:
- die Grosse Platte Ersetzt (eine für WIN und eine HIGH SCORE)

und 
- Eine Font für WIN
- Eine Font für HIGH SCORE

ist juti so oder?

**Comment by Waog** [comment]
moment, kriegst gleich screenshots

**Comment by Waog** [comment]
Sieht jut aus, bau ich so ein :)

![image](https://cloud.githubusercontent.com/assets/5098472/4685016/81866a5c-5636-11e4-82bf-129911d0c540.png)

![image](https://cloud.githubusercontent.com/assets/5098472/4685023/a3790e26-5636-11e4-995c-5e743aeb99b8.png)

Oli TODO: zwei verschiedene bitmap fonts für highscore einbauen.

**Comment by ghost** [comment]
Ist es dann Möglich für HIGH Score, ein andere PNG für die Herzschen zu machen?
würde ich dann wat unsaturiert machen, würde besser passen...

**Comment by Waog** [comment]
jop, hab ich auch schon gedacht... mach mal

**Comment by ghost** [comment]
coolio, liegt:
141016 > highscore_plate

**Comment by Waog** [comment]
done
