### ISSUE TITLE
Große tropfen Streifen

### ISSUE THREAD

**Issue by ghost** [Waog/towelGuy#97]
![screen shot 2014-10-17 at 23 12 36](https://cloud.githubusercontent.com/assets/7753856/4686444/ddefc18a-5645-11e4-834e-931bfb519c43.png)

**Comment by ghost** [comment]
ok, hab ne Drop in "dropbox" gespeichert. Die Spur ist genug groß um visuell mehr zu popen und genung klein wenn Sie verschwindet (colision am boden oder hero) das sollte nicht zu blöd aussehen...
![drop 1](https://cloud.githubusercontent.com/assets/7753856/6493065/59411f08-c2b8-11e4-83fc-eae51258fcde.jpg)
kannste wat damit angafen (Testen?)

**Comment by Waog** [comment]
Tropen müssen noch animiert werden. Und vllt könnte ich den Schweif durch partikel-effekte machen, anstatt dass du den zeichnest. Sähe glaub ich besser aus. Aber habs jetzt erstmal so eingebaut und selbst animation hinzugefügt... sieht ganz okay aus:
![image](https://cloud.githubusercontent.com/assets/5098472/7438875/5fa8a636-f06c-11e4-82e1-7a04d18d5b90.png)
