### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by ghost** [Waog/towelGuy#98]
Hi there,

Hoffe der Weihnachtsman hat dir viele $$$ mit gebracht... :) (Geschenke sind immer doof... hahha)
haste Zeit nächste Woche für ein treffen? wäre ziemlich gut für to does, und da wir lanage nichts gemacht haben gehen frische Informationen weg...

Dazu müssen wir ein Zeitplan/Timing festtellen, sonst befürchte ich dass wir dieses Projekt nie zur Enden werden.

**Comment by Waog** [comment]
Hiho,

@nostoner I'm back :)

habe die letzten Wochen Vollgas bei meiner Abschlussarbeit gegeben und jetzt endlich abgegeben. Habe jetzt wieder viel Zeit für unser Game. Ein Treffen klingt gut... lass mich erstmal in Ruhe die ganzen Updates lesen und abarbeiten. Nächste Woche irgendwann abends/nachts? Ich glaube am Wochenende wäre etwas zu früh.

**Comment by ghost** [comment]
Helllllo!

cool von dir zu hören :)

werde versuchen diese Woche den Aktuel Stand zu bearbeiten (muss wieder ins Thema rein :) und einfach weiter machen.
Hättest du Zeit am Donnerstag oder Freitag Abend für ein Treffen?

**Comment by Waog** [comment]
Donnerstag ginge es ab 21:15 für ca. 3 Stunden, dann will ich pennen.
Freitag so ab 19:15 bis open end.

**Comment by ghost** [comment]
Freitag klingt gut. Wieder bei dir? (ich arbeite sowieso in Mitte...) 19h15, 19h30 ist gut.

**Comment by Waog** [comment]
ok, machen wir so... freitag ab 19:15 bei mir.

**Comment by ghost** [comment]
bin leider noch auf Arbeit, kann nur ab (ungf.) 20h vorbei kommen...
grrrrrrr....

**Comment by Waog** [comment]
np
