### ISSUE TITLE
Buttons Comic Storyboard

### ISSUE THREAD

**Issue by Waog** [Waog/towelGuy#99]
we need:
- play button, after comic
- (tutorial button, in between comic?)

**Comment by ghost** [comment]
liegt in drop

**Comment by Waog** [comment]
@nostoner this one?:
![button play grey](https://cloud.githubusercontent.com/assets/5098472/6429250/3a8f64ec-bfc6-11e4-8156-fefa3bf52330.png)

**Comment by ghost** [comment]
yep

**Comment by Waog** [comment]
was hatten wir genau gesagt wann der button zu sehen ist und warum wir keinen skip-button haben?
Weiß nicht so richtig was ich hier einbauen soll...

**Comment by ghost** [comment]
skip button haben wir schon (liegt im drop)
sonst weiss ich auch nicht mehr wann kommt was.

**Comment by Waog** [comment]
skip-button baue ich nicht extra ein, weil man mit schnell tippen sowieso den comic überspringen kann (siehe #53)
